 K-Fold Cross Validation for Multiple Linear Regression (Least Square Error Fit) 
Download the dataset regarding USA House Price Prediction from the following link: 
https://drive.google.com/file/d/1O_NwpJT-8xGfU_-3llUl2sgPu0xllOrX/view?usp=sharing 
Load the dataset and Implement 5- fold cross validation for multiple linear regression (using 
least square error fit). 
Steps: 
1. Divide the dataset into input features (all columns except price) and output variable 
(price) 
2. Scale the values of input features. 
3. Divide input and output features into five folds. 
4. Run five iterations, in each iteration consider one-fold as test set and remaining four sets 
as training set. Find the beta (𝛽) matrix, predicted values, and R2_score for each iteration 
using least square error fit. 
5. Use the best value of (𝛽) matrix (for which R2_score is maximum), to train the regressor 
for 70% of data and test the performance for remaining 30% data.

In [22]:
import pandas as pd
import numpy as np

In [23]:
df = pd.read_csv("./Data/USA_Housing.csv")
df.head()

,Avg. Area Income,Avg. Area House Age,Avg. Area Number of Rooms,Avg. Area Number of Bedrooms,Area Population,Price
0,79545.45857,5.682861,7.009188,4.09,23086.80050,1.059034e+06
1,79248.64245,6.002900,6.730821,3.09,40173.07217,1.505891e+06
2,61287.06718,5.865890,8.512727,5.13,36882.15940,1.058988e+06
3,63345.24005,7.188236,5.586729,3.26,34310.24283,1.260617e+06
4,59982.19723,5.040555,7.839388,4.23,26354.10947,6.309435e+05

In [24]:
df.columns

Index(['Avg. Area Income', 'Avg. Area House Age', 'Avg. Area Number of Rooms',
       'Avg. Area Number of Bedrooms', 'Area Population', 'Price'],
      dtype='object')

In [25]:
columns = df.columns
for column in columns[:-1]:
    min = df[column].min()
    max = df[column].max()
    den = max-min
    df[column] = (df[column]-min)/den
df.head()

,Avg. Area Income,Avg. Area House Age,Avg. Area Number of Rooms,Avg. Area Number of Bedrooms,Area Population,Price
0,0.686822,0.441986,0.501502,0.464444,0.329942,1.059034e+06
1,0.683521,0.488538,0.464501,0.242222,0.575968,1.505891e+06
2,0.483737,0.468609,0.701350,0.695556,0.528582,1.058988e+06
3,0.506630,0.660956,0.312430,0.280000,0.491549,1.260617e+06
4,0.469223,0.348556,0.611851,0.495556,0.376988,6.309435e+05

In [26]:
x = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [27]:
x

,Avg. Area Income,Avg. Area House Age,Avg. Area Number of Rooms,Avg. Area Number of Bedrooms,Area Population
0,0.686822,0.441986,0.501502,0.464444,0.329942
1,0.683521,0.488538,0.464501,0.242222,0.575968
2,0.483737,0.468609,0.701350,0.695556,0.528582
3,0.506630,0.660956,0.312430,0.280000,0.491549
4,0.469223,0.348556,0.611851,0.495556,0.376988
...,...,...,...,...,...
4995,0.475738,0.754359,0.385619,0.324444,0.326351
4996,0.675097,0.633450,0.444024,0.448889,0.366362
4997,0.507135,0.670026,0.208534,0.028889,0.476515
4998,0.558419,0.420389,0.517579,0.764444,0.611282
4999,0.530715,0.486997,0.472678,0.460000,0.667088

In [28]:
y

0       1.059034e+06
1       1.505891e+06
2       1.058988e+06
3       1.260617e+06
4       6.309435e+05
            ...
4995    1.060194e+06
4996    1.482618e+06
4997    1.030730e+06
4998    1.198657e+06
4999    1.298950e+06
Name: Price, Length: 5000, dtype: float64

In [29]:
foldsize = int(len(x)/5)
len(x),foldsize

(5000, 1000)

In [36]:
folds = []
outputs = []
for i in range(0,len(x),foldsize):
    print(i,i+foldsize)
    temp1 = x.iloc[i:i+foldsize:]
    temp2 = y.iloc[i:i+foldsize:]
    folds.append(temp1)
    outputs.append(temp2)
folds[3],outputs[3]

0 1000
1000 2000
2000 3000
3000 4000
4000 5000

(      Avg. Area Income  Avg. Area House Age  Avg. Area Number of Rooms  \
 3000          0.601991             0.766240                   0.512604
 3001          0.641973             0.285625                   0.644760
 3002          0.540153             0.567609                   0.638675
 3003          0.565501             0.552963                   0.364734
 3004          0.759553             0.509040                   0.470516
 ...                ...                  ...                        ...
 3995          0.365545             0.458034                   0.218307
 3996          0.526623             0.751607                   0.460756
 3997          0.398695             0.271328                   0.597146
 3998          0.421777             0.348402                   0.316320
 3999          0.561379             0.474629                   0.473697

       Avg. Area Number of Bedrooms  Area Population
 3000                      0.728889         0.338638
 3001                      1.000000         0.532800
 3002                      0.982222         0.472349
 3003                      0.108889         0.362968
 3004                      0.517778         0.349529
 ...                            ...              ...
 3995                      0.506667         0.634843
 3996                      0.548889         0.610548
 3997                      0.755556         0.522679
 3998                      0.482222         0.603013
 3999                      0.466667         0.514951

 [1000 rows x 5 columns],
 3000    1.336134e+06
 3001    1.376241e+06
 3002    1.680017e+06
 3003    1.186026e+06
 3004    1.460045e+06
             ...
 3995    8.291287e+05
 3996    1.443228e+06
 3997    6.160570e+05
 3998    8.090575e+05
 3999    1.383938e+06
 Name: Price, Length: 1000, dtype: float64)

In [37]:
params = []
r2s = []
valr2s = []
for i in range(0,5):
    train_set = np.array(pd.concat([folds[j] for j in range(0,len(folds)) if j != i]))
    y_set_train = np.array(pd.concat([outputs[j] for j in range(0,len(outputs)) if j != i]))
    val_Set = np.array(folds[i])
    y_val_Set = np.array(outputs[i])
    train_set = np.c_[np.ones(train_set.shape[0]), train_set]
    val_Set = np.c_[np.ones(val_Set.shape[0]), val_Set]
    ###training
    betas = np.matmul(np.linalg.inv(np.matmul(train_set.transpose(),train_set)),np.matmul(train_set.transpose(),y_set_train))
    train_predictions = np.matmul(train_set,betas)
    r2 = 1 - (np.sum((train_predictions-y_set_train)**2))/((np.sum((y_set_train-np.mean(y_set_train))**2)))
    params.append(betas)
    r2s.append(r2)
    print("Train R2 Score: "+str(r2))

    ### validating
    val_predictions = np.matmul(val_Set,betas)
    r2 = 1 - (np.sum((val_predictions-y_val_Set)**2))/((np.sum((y_val_Set-np.mean(y_val_Set))**2)))
    valr2s.append(r2)
    print("Validation R2 Score: "+str(r2))

Train R2 Score: 0.918041930988685
Validation R2 Score: 0.9175899480765111
Train R2 Score: 0.9173221048597836
Validation R2 Score: 0.9203015496401126
Train R2 Score: 0.9186414845108315
Validation R2 Score: 0.9152429915320013
Train R2 Score: 0.917230839559029
Validation R2 Score: 0.920850383697766
Train R2 Score: 0.9189737185134472
Validation R2 Score: 0.9138111758717504

In [39]:
valr2s

[0.9175899480765111,
 0.9203015496401126,
 0.9152429915320013,
 0.920850383697766,
 0.9138111758717504]

In [40]:
best_index = np.argmax(np.array(valr2s))
best_index

3

In [41]:
best_params = params[best_index]
best_params

array([-1414578.41177661,  1939689.35012524,  1140921.38723207,
         895697.76567999,     4099.75517049,  1058866.32351347])

In [46]:
####on full data
d70 = int(0.7*len(x))
len(x),d70

(5000, 3500)

In [70]:
x_tr = x.iloc[0:d70,:]
y_tr = y.iloc[0:d70]

In [71]:
x_t = x.iloc[d70:len(x),:]
y_t = y.iloc[d70:len(y)]
len(x_t),len(y_t)

(1500, 1500)

In [72]:
foldsize = int(len(x_tr)/5)
foldsize

700

In [73]:
folds = []
outputs = []
for i in range(0,len(x_tr),foldsize):
    print(i,i+foldsize)
    temp1 = x_tr.iloc[i:i+foldsize:]
    temp2 = y_tr.iloc[i:i+foldsize:]
    folds.append(temp1)
    outputs.append(temp2)
folds[3],outputs[3],len(folds[3]),len(outputs[3])

0 700
700 1400
1400 2100
2100 2800
2800 3500

(      Avg. Area Income  Avg. Area House Age  Avg. Area Number of Rooms  \
 2100          0.672974             0.448024                   0.750916
 2101          0.571248             0.261063                   0.459040
 2102          0.648584             0.611885                   0.471158
 2103          0.418426             0.435648                   0.185650
 2104          0.713795             0.400932                   0.497530
 ...                ...                  ...                        ...
 2795          0.850848             0.487144                   0.537336
 2796          0.502103             0.578837                   0.588262
 2797          0.604283             0.514583                   0.626983
 2798          0.429360             0.458083                   0.516326
 2799          0.365601             0.689592                   0.509306

       Avg. Area Number of Bedrooms  Area Population
 2100                      0.911111         0.773931
 2101                      0.444444         0.518463
 2102                      0.251111         0.809288
 2103                      0.086667         0.347283
 2104                      0.084444         0.476785
 ...                            ...              ...
 2795                      0.746667         0.769604
 2796                      0.255556         0.702309
 2797                      0.708889         0.651457
 2798                      0.480000         0.730565
 2799                      0.708889         0.425540

 [700 rows x 5 columns],
 2100    1.988564e+06
 2101    7.998424e+05
 2102    1.813555e+06
 2103    4.929846e+05
 2104    1.325531e+06
             ...
 2795    2.197437e+06
 2796    1.721262e+06
 2797    1.670909e+06
 2798    1.148750e+06
 2799    1.154883e+06
 Name: Price, Length: 700, dtype: float64,
 700,
 700)

In [74]:
params = []
r2s = []
valr2s = []
for i in range(0,5):
    train_set = np.array(pd.concat([folds[j] for j in range(0,len(folds)) if j != i]))
    y_set_train = np.array(pd.concat([outputs[j] for j in range(0,len(outputs)) if j != i]))
    val_Set = np.array(folds[i])
    y_val_Set = np.array(outputs[i])
    train_set = np.c_[np.ones(train_set.shape[0]), train_set]
    val_Set = np.c_[np.ones(val_Set.shape[0]), val_Set]
    ###training
    betas = np.matmul(np.linalg.inv(np.matmul(train_set.transpose(),train_set)),np.matmul(train_set.transpose(),y_set_train))
    train_predictions = np.matmul(train_set,betas)
    r2 = 1 - (np.sum((train_predictions-y_set_train)**2))/((np.sum((y_set_train-np.mean(y_set_train))**2)))
    params.append(betas)
    r2s.append(r2)
    print("Train R2 Score: "+str(r2))

    ### validating
    val_predictions = np.matmul(val_Set,betas)
    r2 = 1 - (np.sum((val_predictions-y_val_Set)**2))/((np.sum((y_val_Set-np.mean(y_val_Set))**2)))
    valr2s.append(r2)
    print("Validation R2 Score: "+str(r2))

Train R2 Score: 0.9182809466814498
Validation R2 Score: 0.9170056919950382
Train R2 Score: 0.9178595105083732
Validation R2 Score: 0.9185110303568388
Train R2 Score: 0.9166093090021042
Validation R2 Score: 0.9226206475535721
Train R2 Score: 0.9190618676346699
Validation R2 Score: 0.9135866311216853
Train R2 Score: 0.9186561188719435
Validation R2 Score: 0.9151040123364312

In [75]:
best_index = np.argmax(np.array(valr2s))
best_index

2

In [76]:
best_betas = params[best_index]
best_betas

array([-1.42153572e+06,  1.94337224e+06,  1.14317264e+06,  9.25642260e+05,
        7.57877046e+02,  1.04537110e+06])

In [77]:
y_t = np.array(y_t)

In [78]:
x_t_1 = np.c_[np.ones(x_t.shape[0]), x_t]
x_t_1.shape

(1500, 6)

In [79]:
test_predictions = np.matmul(x_t_1,best_betas)
test_predictions.shape

(1500,)

In [80]:
r2 = 1 - (np.sum((test_predictions-y_t)**2))/((np.sum((y_t-np.mean(y_t))**2)))
r2

0.9175880102439207

Concept of Validation set for Multiple Linear Regression (Gradient Descent 
Optimization) 
Consider the same dataset of Q1, rather than dividing the dataset into five folds, divide the 
dataset into training set (56%), validation set (14%), and test set (30%). 
Consider four different values of learning rate i.e. {0.001,0.01,0.1,1}. Compute the values of 
regression coefficients for each value of learning rate after 1000 iterations.  
For each set of regression coefficients, compute R2_score for validation and test set and find the 
best value of regression coefficients.

In [85]:
indices = np.arange(0,len(x),dtype=int)
indices

array([   0,    1,    2, ..., 4997, 4998, 4999])

In [93]:
np.random.shuffle(indices)
indices

array([1804,  230, 2087, ..., 4844, 2179, 2990])

In [92]:
x_array = np.array(x)
y_array = np.array(y)
x_array.shape, y_array.shape

((5000, 5), (5000,))

In [94]:
x_array = x_array[indices,:]
y_array = y_array[indices]
x_array.shape, y_array.shape

((5000, 5), (5000,))

In [95]:
train_limit = int(0.56*len(x_array))
validation_limit = int(0.14*len(x_array))
test_limit = int(0.30*len(x_array))
train_limit,validation_limit,test_limit

(2800, 700, 1500)

In [96]:
x_tr = x_array[0:train_limit,:]
y_tr = y_array[0:train_limit]
x_v = x_array[train_limit:train_limit+validation_limit,:]
y_v = y_array[train_limit:train_limit+validation_limit]
x_t = x_array[train_limit+validation_limit:train_limit+validation_limit+test_limit,:]
y_t = y_array[train_limit+validation_limit:train_limit+validation_limit+test_limit]

In [97]:
epochs = 1000

In [98]:
x_t.shape[1]+1

6

In [99]:
x_tr.shape[0]

2800

Training R2: -12.339549070262802 Validation R2: -12.173249629238658

In [ ]:
r2vals = []
alphas = [0.001,0.01,0.1,1]
params = []
for alpha in alphas:
    betas = np.zeros(x_tr.shape[1]+1)
    x_tr1 = np.c_[np.ones(x_tr.shape[0]),x_tr]    
    n = len(x_tr1)
    for i in range(0,epochs):

        ##training
        predictions = np.matmul(x_tr1,betas)
        errors = predictions - y_tr
        gradient = 1/n*np.matmul(x_tr1.transpose(),errors)
        betas = betas - alpha*gradient
        r2t = 1 - (np.sum((predictions-y_tr)**2))/((np.sum((y_tr-np.mean(y_tr))**2)))
        print("Epoch: " + str(i) + " Training R2: "+str(r2t))

    ##validation
    x_v1 = np.c_[np.ones(x_v.shape[0]),x_v]    
    val_predictions = np.matmul(x_v1,betas)
    r2v = 1 - (np.sum((val_predictions-y_v)**2))/((np.sum((y_v-np.mean(y_v))**2)))
    print("Validation R2: "+str(r2v))
    r2vals.append(r2v)
    params.append(betas)

Epoch: 0 Training R2: -12.339549070262802
Epoch: 1 Training R2: -12.281577767527851
Epoch: 2 Training R2: -12.223871003208032
Epoch: 3 Training R2: -12.166427569898868
Epoch: 4 Training R2: -12.109246265706718
Epoch: 5 Training R2: -12.052325894223628
Epoch: 6 Training R2: -11.995665264502296
Epoch: 7 Training R2: -11.939263191031147
Epoch: 8 Training R2: -11.88311849370952
Epoch: 9 Training R2: -11.82722999782297
Epoch: 10 Training R2: -11.771596534018697
Epoch: 11 Training R2: -11.716216938281056
Epoch: 12 Training R2: -11.661090051907214
Epoch: 13 Training R2: -11.606214721482887
Epoch: 14 Training R2: -11.551589798858213
Epoch: 15 Training R2: -11.497214141123717
Epoch: 16 Training R2: -11.443086610586398
Epoch: 17 Training R2: -11.389206074745916
Epoch: 18 Training R2: -11.335571406270892
Epoch: 19 Training R2: -11.282181482975318
Epoch: 20 Training R2: -11.229035187795073
Epoch: 21 Training R2: -11.176131408764542
Epoch: 22 Training R2: -11.123469038993347
Epoch: 23 Training R2: -11.071046976643183
Epoch: 24 Training R2: -11.018864124904763
Epoch: 25 Training R2: -10.966919391974857
Epoch: 26 Training R2: -10.915211691033447
Epoch: 27 Training R2: -10.863739940220984
Epoch: 28 Training R2: -10.812503062615747
Epoch: 29 Training R2: -10.761499986211305
Epoch: 30 Training R2: -10.710729643894078
Epoch: 31 Training R2: -10.660190973421017
Epoch: 32 Training R2: -10.609882917397359
Epoch: 33 Training R2: -10.559804423254514
Epoch: 34 Training R2: -10.509954443228022
Epoch: 35 Training R2: -10.460331934335633
Epoch: 36 Training R2: -10.410935858355488
Epoch: 37 Training R2: -10.36176518180438
Epoch: 38 Training R2: -10.312818875916125
Epoch: 39 Training R2: -10.264095916620045
Epoch: 40 Training R2: -10.21559528451952
Epoch: 41 Training R2: -10.167315964870674
Epoch: 42 Training R2: -10.11925694756112
Epoch: 43 Training R2: -10.071417227088833
Epoch: 44 Training R2: -10.023795802541107
Epoch: 45 Training R2: -9.976391677573597
Epoch: 46 Training R2: -9.929203860389487
Epoch: 47 Training R2: -9.882231363718713
Epoch: 48 Training R2: -9.835473204797317
Epoch: 49 Training R2: -9.788928405346882
Epoch: 50 Training R2: -9.742595991554044
Epoch: 51 Training R2: -9.69647499405012
Epoch: 52 Training R2: -9.650564447890833
Epoch: 53 Training R2: -9.6048633925361
Epoch: 54 Training R2: -9.559370871829941
Epoch: 55 Training R2: -9.514085933980464
Epoch: 56 Training R2: -9.469007631539954
Epoch: 57 Training R2: -9.424135021385036
Epoch: 58 Training R2: -9.379467164696944
Epoch: 59 Training R2: -9.335003126941869
Epoch: 60 Training R2: -9.290741977851408
Epoch: 61 Training R2: -9.246682791403092
Epoch: 62 Training R2: -9.202824645801005
Epoch: 63 Training R2: -9.159166623456494
Epoch: 64 Training R2: -9.11570781096897
Epoch: 65 Training R2: -9.072447299106793
Epoch: 66 Training R2: -9.029384182788233
Epoch: 67 Training R2: -8.986517561062545
Epoch: 68 Training R2: -8.943846537091105
Epoch: 69 Training R2: -8.901370218128635
Epoch: 70 Training R2: -8.859087715504542
Epoch: 71 Training R2: -8.816998144604293
Epoch: 72 Training R2: -8.775100624850923
Epoch: 73 Training R2: -8.7333942796866
Epoch: 74 Training R2: -8.69187823655428
Epoch: 75 Training R2: -8.650551626879437
Epoch: 76 Training R2: -8.609413586051916
Epoch: 77 Training R2: -8.568463253407797
Epoch: 78 Training R2: -8.52769977221142
Epoch: 79 Training R2: -8.487122289637433
Epoch: 80 Training R2: -8.44672995675296
Epoch: 81 Training R2: -8.406521928499817
Epoch: 82 Training R2: -8.366497363676848
Epoch: 83 Training R2: -8.326655424922302
Epoch: 84 Training R2: -8.286995278696324
Epoch: 85 Training R2: -8.2475160952635
Epoch: 86 Training R2: -8.208217048675495
Epoch: 87 Training R2: -8.169097316753781
Epoch: 88 Training R2: -8.130156081072405
Epoch: 89 Training R2: -8.091392526940894
Epoch: 90 Training R2: -8.052805843387167
Epoch: 91 Training R2: -8.014395223140607
Epoch: 92 Training R2: -7.976159862615125
Epoch: 93 Training R2: -7.938098961892376
Epoch: 94 Training R2: -7.9002117247050005
Epoch: 95 Training R2: -7.862497358419958
Epoch: 96 Training R2: -7.824955074021961
Epoch: 97 Training R2: -7.787584086096935
Epoch: 98 Training R2: -7.750383612815604
Epoch: 99 Training R2: -7.7133528759171135
Epoch: 100 Training R2: -7.676491100692754
Epoch: 101 Training R2: -7.639797515969745
Epoch: 102 Training R2: -7.603271354095089
Epoch: 103 Training R2: -7.566911850919521
Epoch: 104 Training R2: -7.530718245781502
Epoch: 105 Training R2: -7.49468978149131
Epoch: 106 Training R2: -7.4588257043151955
Epoch: 107 Training R2: -7.423125263959593
Epoch: 108 Training R2: -7.387587713555437
Epoch: 109 Training R2: -7.352212309642525
Epoch: 110 Training R2: -7.316998312153949
Epoch: 111 Training R2: -7.28194498440063
Epoch: 112 Training R2: -7.247051593055877
Epoch: 113 Training R2: -7.212317408140059
Epoch: 114 Training R2: -7.177741703005314
Epoch: 115 Training R2: -7.143323754320349
Epoch: 116 Training R2: -7.109062842055311
Epoch: 117 Training R2: -7.0749582494667
Epoch: 118 Training R2: -7.04100926308238
Epoch: 119 Training R2: -7.0072151726866565
Epoch: 120 Training R2: -6.973575271305388
Epoch: 121 Training R2: -6.940088855191221
Epoch: 122 Training R2: -6.906755223808841
Epoch: 123 Training R2: -6.873573679820323
Epoch: 124 Training R2: -6.840543529070531
Epoch: 125 Training R2: -6.80766408057259
Epoch: 126 Training R2: -6.774934646493444
Epoch: 127 Training R2: -6.742354542139429
Epoch: 128 Training R2: -6.709923085941979
Epoch: 129 Training R2: -6.677639599443331
Epoch: 130 Training R2: -6.64550340728235
Epoch: 131 Training R2: -6.613513837180384
Epoch: 132 Training R2: -6.581670219927198
Epoch: 133 Training R2: -6.549971889366969
Epoch: 134 Training R2: -6.51841818238434
Epoch: 135 Training R2: -6.487008438890558
Epoch: 136 Training R2: -6.455742001809637
Epoch: 137 Training R2: -6.424618217064627
Epoch: 138 Training R2: -6.393636433563918
Epoch: 139 Training R2: -6.36279600318761
Epoch: 140 Training R2: -6.332096280773959
Epoch: 141 Training R2: -6.301536624105866
Epoch: 142 Training R2: -6.2711163938974455
Epoch: 143 Training R2: -6.240834953780642
Epoch: 144 Training R2: -6.210691670291907
Epoch: 145 Training R2: -6.18068591285896
Epoch: 146 Training R2: -6.150817053787571
Epoch: 147 Training R2: -6.121084468248435
Epoch: 148 Training R2: -6.091487534264103
Epoch: 149 Training R2: -6.0620256326959465
Epoch: 150 Training R2: -6.032698147231221
Epoch: 151 Training R2: -6.003504464370151
Epoch: 152 Training R2: -5.974443973413105
Epoch: 153 Training R2: -5.945516066447807
Epoch: 154 Training R2: -5.916720138336611
Epoch: 155 Training R2: -5.88805558670385
Epoch: 156 Training R2: -5.859521811923219
Epoch: 157 Training R2: -5.831118217105229
Epoch: 158 Training R2: -5.802844208084713
Epoch: 159 Training R2: -5.7746991934084
Epoch: 160 Training R2: -5.74668258432253
Epoch: 161 Training R2: -5.7187937947605345
Epoch: 162 Training R2: -5.69103224133077
Epoch: 163 Training R2: -5.663397343304316
Epoch: 164 Training R2: -5.635888522602811
Epoch: 165 Training R2: -5.608505203786366
Epoch: 166 Training R2: -5.581246814041513
Epoch: 167 Training R2: -5.554112783169222
Epoch: 168 Training R2: -5.527102543572967
Epoch: 169 Training R2: -5.50021553024685
Epoch: 170 Training R2: -5.473451180763775
Epoch: 171 Training R2: -5.446808935263672
Epoch: 172 Training R2: -5.420288236441792
Epoch: 173 Training R2: -5.393888529537038
Epoch: 174 Training R2: -5.36760926232035
Epoch: 175 Training R2: -5.34144988508316
Epoch: 176 Training R2: -5.31540985062588
Epoch: 177 Training R2: -5.289488614246448
Epoch: 178 Training R2: -5.263685633728938
Epoch: 179 Training R2: -5.238000369332206
Epoch: 180 Training R2: -5.212432283778596
Epoch: 181 Training R2: -5.186980842242696
Epoch: 182 Training R2: -5.161645512340146
Epoch: 183 Training R2: -5.136425764116498
Epoch: 184 Training R2: -5.111321070036124
Epoch: 185 Training R2: -5.08633090497117
Epoch: 186 Training R2: -5.061454746190581
Epoch: 187 Training R2: -5.0366920733491485
Epoch: 188 Training R2: -5.012042368476623
Epoch: 189 Training R2: -4.987505115966879
Epoch: 190 Training R2: -4.963079802567125
Epoch: 191 Training R2: -4.938765917367153
Epoch: 192 Training R2: -4.9145629517886595
Epoch: 193 Training R2: -4.890470399574591
Epoch: 194 Training R2: -4.866487756778556
Epoch: 195 Training R2: -4.842614521754276
Epoch: 196 Training R2: -4.8188501951450915
Epoch: 197 Training R2: -4.795194279873503
Epoch: 198 Training R2: -4.771646281130779
Epoch: 199 Training R2: -4.748205706366589
Epoch: 200 Training R2: -4.724872065278709
Epoch: 201 Training R2: -4.70164486980275
Epoch: 202 Training R2: -4.678523634101949
Epoch: 203 Training R2: -4.655507874557002
Epoch: 204 Training R2: -4.632597109755938
Epoch: 205 Training R2: -4.609790860484055
Epoch: 206 Training R2: -4.587088649713876
Epoch: 207 Training R2: -4.564490002595181
Epoch: 208 Training R2: -4.5419944464450595
Epoch: 209 Training R2: -4.519601510738022
Epoch: 210 Training R2: -4.497310727096154
Epoch: 211 Training R2: -4.475121629279312
Epoch: 212 Training R2: -4.453033753175369
Epoch: 213 Training R2: -4.431046636790497
Epoch: 214 Training R2: -4.4091598202395055
Epoch: 215 Training R2: -4.38737284573621
Epoch: 216 Training R2: -4.3656852575838565
Epoch: 217 Training R2: -4.3440966021655845
Epoch: 218 Training R2: -4.322606427934933
Epoch: 219 Training R2: -4.301214285406389
Epoch: 220 Training R2: -4.279919727145982
Epoch: 221 Training R2: -4.258722307761925
Epoch: 222 Training R2: -4.237621583895287
Epoch: 223 Training R2: -4.216617114210717
Epoch: 224 Training R2: -4.195708459387208
Epoch: 225 Training R2: -4.174895182108906
Epoch: 226 Training R2: -4.154176847055952
Epoch: 227 Training R2: -4.133553020895378
Epoch: 228 Training R2: -4.113023272272033
Epoch: 229 Training R2: -4.092587171799559
Epoch: 230 Training R2: -4.07224429205141
Epoch: 231 Training R2: -4.0519942075518935
Epoch: 232 Training R2: -4.031836494767279
Epoch: 233 Training R2: -4.011770732096927
Epoch: 234 Training R2: -3.991796499864475
Epoch: 235 Training R2: -3.971913380309042
Epoch: 236 Training R2: -3.9521209575764953
Epoch: 237 Training R2: -3.9324188177107464
Epoch: 238 Training R2: -3.912806548645083
Epoch: 239 Training R2: -3.893283740193552
Epoch: 240 Training R2: -3.87384998404237
Epoch: 241 Training R2: -3.8545048737413845
Epoch: 242 Training R2: -3.8352480046955586
Epoch: 243 Training R2: -3.816078974156513
Epoch: 244 Training R2: -3.7969973812140916
Epoch: 245 Training R2: -3.7780028267879784
Epoch: 246 Training R2: -3.7590949136193332
Epoch: 247 Training R2: -3.7402732462624932
Epoch: 248 Training R2: -3.721537431076685
Epoch: 249 Training R2: -3.702887076217797
Epoch: 250 Training R2: -3.6843217916301647
Epoch: 251 Training R2: -3.665841189038426
Epoch: 252 Training R2: -3.647444881939383
Epoch: 253 Training R2: -3.6291324855939155
Epoch: 254 Training R2: -3.6109036170189315
Epoch: 255 Training R2: -3.5927578949793535
Epoch: 256 Training R2: -3.5746949399801355
Epoch: 257 Training R2: -3.556714374258326
Epoch: 258 Training R2: -3.5388158217751577
Epoch: 259 Training R2: -3.5209989082081847
Epoch: 260 Training R2: -3.5032632609434424
Epoch: 261 Training R2: -3.4856085090676503
Epoch: 262 Training R2: -3.4680342833604554
Epoch: 263 Training R2: -3.450540216286697
Epoch: 264 Training R2: -3.433125941988725
Epoch: 265 Training R2: -3.4157910962787295
Epoch: 266 Training R2: -3.3985353166311363
Epoch: 267 Training R2: -3.381358242175007
Epoch: 268 Training R2: -3.364259513686493
Epoch: 269 Training R2: -3.3472387735813154
Epoch: 270 Training R2: -3.3302956659072818
Epoch: 271 Training R2: -3.313429836336839
Epoch: 272 Training R2: -3.296640932159658
Epoch: 273 Training R2: -3.2799286022752483
Epoch: 274 Training R2: -3.263292497185616
Epoch: 275 Training R2: -3.2467322689879454
Epoch: 276 Training R2: -3.23024757136732
Epoch: 277 Training R2: -3.2138380595894755
Epoch: 278 Training R2: -3.1975033904935843
Epoch: 279 Training R2: -3.181243222485074
Epoch: 280 Training R2: -3.165057215528482
Epoch: 281 Training R2: -3.1489450311403324
Epoch: 282 Training R2: -3.132906332382059
Epoch: 283 Training R2: -3.11694078385295
Epoch: 284 Training R2: -3.101048051683134
Epoch: 285 Training R2: -3.0852278035265854
Epoch: 286 Training R2: -3.0694797085541747
Epoch: 287 Training R2: -3.053803437446745
Epoch: 288 Training R2: -3.0381986623882176
Epoch: 289 Training R2: -3.022665057058733
Epoch: 290 Training R2: -3.0072022966278213
Epoch: 291 Training R2: -2.991810057747607
Epoch: 292 Training R2: -2.9764880185460374
Epoch: 293 Training R2: -2.96123585862015
Epoch: 294 Training R2: -2.946053259029367
Epoch: 295 Training R2: -2.930939902288817
Epoch: 296 Training R2: -2.9158954723627
Epoch: 297 Training R2: -2.900919654657664
Epoch: 298 Training R2: -2.886012136016222
Epoch: 299 Training R2: -2.871172604710206
Epoch: 300 Training R2: -2.8564007504342377
Epoch: 301 Training R2: -2.8416962642992334
Epoch: 302 Training R2: -2.827058838825944
Epoch: 303 Training R2: -2.8124881679385165
Epoch: 304 Training R2: -2.7979839469580914
Epoch: 305 Training R2: -2.783545872596425
Epoch: 306 Training R2: -2.7691736429495433
Epoch: 307 Training R2: -2.7548669574914193
Epoch: 308 Training R2: -2.740625517067693
Epoch: 309 Training R2: -2.7264490238894044
Epoch: 310 Training R2: -2.7123371815267605
Epoch: 311 Training R2: -2.698289694902935
Epoch: 312 Training R2: -2.6843062702878933
Epoch: 313 Training R2: -2.670386615292244
Epoch: 314 Training R2: -2.6565304388611173
Epoch: 315 Training R2: -2.642737451268081
Epoch: 316 Training R2: -2.629007364109072
Epoch: 317 Training R2: -2.615339890296358
Epoch: 318 Training R2: -2.6017347440525387
Epoch: 319 Training R2: -2.588191640904557
Epoch: 320 Training R2: -2.574710297677749
Epoch: 321 Training R2: -2.5612904324899173
Epoch: 322 Training R2: -2.5479317647454316
Epoch: 323 Training R2: -2.534634015129358
Epoch: 324 Training R2: -2.521396905601612
Epoch: 325 Training R2: -2.5082201593911404
Epoch: 326 Training R2: -2.49510350099013
Epoch: 327 Training R2: -2.482046656148239
Epoch: 328 Training R2: -2.4690493518668624
Epoch: 329 Training R2: -2.456111316393415
Epoch: 330 Training R2: -2.443232279215644
Epoch: 331 Training R2: -2.4304119710559724
Epoch: 332 Training R2: -2.417650123865858
Epoch: 333 Training R2: -2.404946470820188
Epoch: 334 Training R2: -2.3923007463116943
Epoch: 335 Training R2: -2.379712685945391
Epoch: 336 Training R2: -2.3671820265330483
Epoch: 337 Training R2: -2.354708506087678
Epoch: 338 Training R2: -2.3422918638180534
Epoch: 339 Training R2: -2.329931840123255
Epoch: 340 Training R2: -2.3176281765872337
Epoch: 341 Training R2: -2.3053806159734
Epoch: 342 Training R2: -2.293188902219248
Epoch: 343 Training R2: -2.2810527804309917
Epoch: 344 Training R2: -2.268971996878232
Epoch: 345 Training R2: -2.2569462989886477
Epoch: 346 Training R2: -2.2449754353427065
Epoch: 347 Training R2: -2.2330591556684096
Epoch: 348 Training R2: -2.2211972108360465
Epoch: 349 Training R2: -2.209389352852987
Epoch: 350 Training R2: -2.1976353348584903
Epoch: 351 Training R2: -2.1859349111185358
Epoch: 352 Training R2: -2.1742878370206853
Epoch: 353 Training R2: -2.162693869068959
Epoch: 354 Training R2: -2.151152764878743
Epoch: 355 Training R2: -2.139664283171717
Epoch: 356 Training R2: -2.128228183770802
Epoch: 357 Training R2: -2.116844227595138
Epoch: 358 Training R2: -2.1055121766550764
Epoch: 359 Training R2: -2.0942317940472024
Epoch: 360 Training R2: -2.0830028439493766
Epoch: 361 Training R2: -2.071825091615799
Epoch: 362 Training R2: -2.060698303372098
Epoch: 363 Training R2: -2.0496222466104377
Epoch: 364 Training R2: -2.0385966897846535
Epoch: 365 Training R2: -2.0276214024054027
Epoch: 366 Training R2: -2.016696155035343
Epoch: 367 Training R2: -2.0058207192843307
Epoch: 368 Training R2: -1.9949948678046412
Epoch: 369 Training R2: -1.9842183742862116
Epoch: 370 Training R2: -1.9734910134519024
Epoch: 371 Training R2: -1.9628125610527856
Epoch: 372 Training R2: -1.9521827938634506
Epoch: 373 Training R2: -1.9416014896773328
Epoch: 374 Training R2: -1.9310684273020637
Epoch: 375 Training R2: -1.9205833865548403
Epoch: 376 Training R2: -1.91014614825782
Epoch: 377 Training R2: -1.8997564942335305
Epoch: 378 Training R2: -1.8894142073003075
Epoch: 379 Training R2: -1.879119071267748
Epoch: 380 Training R2: -1.868870870932183
Epoch: 381 Training R2: -1.8586693920721804
Epoch: 382 Training R2: -1.8485144214440545
Epoch: 383 Training R2: -1.83840574677741
Epoch: 384 Training R2: -1.828343156770694
Epoch: 385 Training R2: -1.818326441086778
Epoch: 386 Training R2: -1.8083553903485559
Epoch: 387 Training R2: -1.7984297961345588
Epoch: 388 Training R2: -1.7885494509745965
Epoch: 389 Training R2: -1.7787141483454163
Epoch: 390 Training R2: -1.7689236826663768
Epoch: 391 Training R2: -1.7591778492951495
Epoch: 392 Training R2: -1.749476444523435
Epoch: 393 Training R2: -1.7398192655727
Epoch: 394 Training R2: -1.7302061105899331
Epoch: 395 Training R2: -1.7206367786434216
Epoch: 396 Training R2: -1.7111110697185437
Epoch: 397 Training R2: -1.7016287847135878
Epoch: 398 Training R2: -1.6921897254355796
Epoch: 399 Training R2: -1.6827936945961413
Epoch: 400 Training R2: -1.6734404958073559
Epoch: 401 Training R2: -1.6641299335776614
Epoch: 402 Training R2: -1.654861813307761
Epoch: 403 Training R2: -1.645635941286546
Epoch: 404 Training R2: -1.6364521246870454
Epoch: 405 Training R2: -1.6273101715623888
Epoch: 406 Training R2: -1.6182098908417912
Epoch: 407 Training R2: -1.6091510923265528
Epoch: 408 Training R2: -1.6001335866860793
Epoch: 409 Training R2: -1.5911571854539184
Epoch: 410 Training R2: -1.582221701023819
Epoch: 411 Training R2: -1.5733269466458006
Epoch: 412 Training R2: -1.5644727364222497
Epoch: 413 Training R2: -1.555658885304025
Epoch: 414 Training R2: -1.546885209086588
Epoch: 415 Training R2: -1.5381515244061466
Epoch: 416 Training R2: -1.5294576487358187
Epoch: 417 Training R2: -1.5208034003818112
Epoch: 418 Training R2: -1.5121885984796184
Epoch: 419 Training R2: -1.5036130629902367
Epoch: 420 Training R2: -1.4950766146963974
Epoch: 421 Training R2: -1.4865790751988146
Epoch: 422 Training R2: -1.4781202669124536
Epoch: 423 Training R2: -1.469700013062814
Epoch: 424 Training R2: -1.4613181376822295
Epoch: 425 Training R2: -1.4529744656061858
Epoch: 426 Training R2: -1.4446688224696547
Epoch: 427 Training R2: -1.436401034703446
Epoch: 428 Training R2: -1.4281709295305731
Epoch: 429 Training R2: -1.4199783349626398
Epoch: 430 Training R2: -1.4118230797962399
Epoch: 431 Training R2: -1.4037049936093715
Epoch: 432 Training R2: -1.3956239067578764
Epoch: 433 Training R2: -1.387579650371885
Epoch: 434 Training R2: -1.3795720563522842
Epoch: 435 Training R2: -1.3716009573671992
Epoch: 436 Training R2: -1.363666186848492
Epoch: 437 Training R2: -1.355767578988274
Epoch: 438 Training R2: -1.34790496873544
Epoch: 439 Training R2: -1.3400781917922084
Epoch: 440 Training R2: -1.3322870846106878
Epoch: 441 Training R2: -1.3245314843894507
Epoch: 442 Training R2: -1.3168112290701308
Epoch: 443 Training R2: -1.3091261573340263
Epoch: 444 Training R2: -1.3014761085987288
Epoch: 445 Training R2: -1.2938609230147589
Epoch: 446 Training R2: -1.2862804414622224
Epoch: 447 Training R2: -1.2787345055474808
Epoch: 448 Training R2: -1.2712229575998384
Epoch: 449 Training R2: -1.263745640668236
Epoch: 450 Training R2: -1.2563023985179744
Epoch: 451 Training R2: -1.2488930756274401
Epoch: 452 Training R2: -1.2415175171848496
Epoch: 453 Training R2: -1.234175569085016
Epoch: 454 Training R2: -1.2268670779261148
Epoch: 455 Training R2: -1.2195918910064818
Epoch: 456 Training R2: -1.2123498563214126
Epoch: 457 Training R2: -1.2051408225599838
Epoch: 458 Training R2: -1.1979646391018846
Epoch: 459 Training R2: -1.1908211560142652
Epoch: 460 Training R2: -1.1837102240486028
Epoch: 461 Training R2: -1.1766316946375706
Epoch: 462 Training R2: -1.1695854198919364
Epoch: 463 Training R2: -1.1625712525974627

In [102]:
r2vals

[0.21921929920632,
 0.4523696728504252,
 0.8021069465843109,
 -5.0616271487614915e+218]

In [103]:
alphas

[0.001, 0.01, 0.1, 1]

In [104]:
epochs = 5000
r2vals = []
alphas = [0.001,0.01,0.1,1]
params = []
for alpha in alphas:
    betas = np.zeros(x_tr.shape[1]+1)
    x_tr1 = np.c_[np.ones(x_tr.shape[0]),x_tr]    
    n = len(x_tr1)
    for i in range(0,epochs):

        ##training
        predictions = np.matmul(x_tr1,betas)
        errors = predictions - y_tr
        gradient = 1/n*np.matmul(x_tr1.transpose(),errors)
        betas = betas - alpha*gradient
        r2t = 1 - (np.sum((predictions-y_tr)**2))/((np.sum((y_tr-np.mean(y_tr))**2)))
        print("Epoch: " + str(i) + " Training R2: "+str(r2t))

    ##validation
    x_v1 = np.c_[np.ones(x_v.shape[0]),x_v]    
    val_predictions = np.matmul(x_v1,betas)
    r2v = 1 - (np.sum((val_predictions-y_v)**2))/((np.sum((y_v-np.mean(y_v))**2)))
    print("Validation R2: "+str(r2v))
    r2vals.append(r2v)
    params.append(betas)

Epoch: 0 Training R2: -12.339549070262802
Epoch: 1 Training R2: -12.281577767527851
Epoch: 2 Training R2: -12.223871003208032
Epoch: 3 Training R2: -12.166427569898868
Epoch: 4 Training R2: -12.109246265706718
Epoch: 5 Training R2: -12.052325894223628
Epoch: 6 Training R2: -11.995665264502296
Epoch: 7 Training R2: -11.939263191031147
Epoch: 8 Training R2: -11.88311849370952
Epoch: 9 Training R2: -11.82722999782297
Epoch: 10 Training R2: -11.771596534018697
Epoch: 11 Training R2: -11.716216938281056
Epoch: 12 Training R2: -11.661090051907214
Epoch: 13 Training R2: -11.606214721482887
Epoch: 14 Training R2: -11.551589798858213
Epoch: 15 Training R2: -11.497214141123717
Epoch: 16 Training R2: -11.443086610586398
Epoch: 17 Training R2: -11.389206074745916
Epoch: 18 Training R2: -11.335571406270892
Epoch: 19 Training R2: -11.282181482975318
Epoch: 20 Training R2: -11.229035187795073
Epoch: 21 Training R2: -11.176131408764542
Epoch: 22 Training R2: -11.123469038993347
Epoch: 23 Training R2: -11.071046976643183
Epoch: 24 Training R2: -11.018864124904763
Epoch: 25 Training R2: -10.966919391974857
Epoch: 26 Training R2: -10.915211691033447
Epoch: 27 Training R2: -10.863739940220984
Epoch: 28 Training R2: -10.812503062615747
Epoch: 29 Training R2: -10.761499986211305
Epoch: 30 Training R2: -10.710729643894078
Epoch: 31 Training R2: -10.660190973421017
Epoch: 32 Training R2: -10.609882917397359
Epoch: 33 Training R2: -10.559804423254514
Epoch: 34 Training R2: -10.509954443228022
Epoch: 35 Training R2: -10.460331934335633
Epoch: 36 Training R2: -10.410935858355488
Epoch: 37 Training R2: -10.36176518180438
Epoch: 38 Training R2: -10.312818875916125
Epoch: 39 Training R2: -10.264095916620045
Epoch: 40 Training R2: -10.21559528451952
Epoch: 41 Training R2: -10.167315964870674
Epoch: 42 Training R2: -10.11925694756112
Epoch: 43 Training R2: -10.071417227088833
Epoch: 44 Training R2: -10.023795802541107
Epoch: 45 Training R2: -9.976391677573597
Epoch: 46 Training R2: -9.929203860389487
Epoch: 47 Training R2: -9.882231363718713
Epoch: 48 Training R2: -9.835473204797317
Epoch: 49 Training R2: -9.788928405346882
Epoch: 50 Training R2: -9.742595991554044
Epoch: 51 Training R2: -9.69647499405012
Epoch: 52 Training R2: -9.650564447890833
Epoch: 53 Training R2: -9.6048633925361
Epoch: 54 Training R2: -9.559370871829941
Epoch: 55 Training R2: -9.514085933980464
Epoch: 56 Training R2: -9.469007631539954
Epoch: 57 Training R2: -9.424135021385036
Epoch: 58 Training R2: -9.379467164696944
Epoch: 59 Training R2: -9.335003126941869
Epoch: 60 Training R2: -9.290741977851408
Epoch: 61 Training R2: -9.246682791403092
Epoch: 62 Training R2: -9.202824645801005
Epoch: 63 Training R2: -9.159166623456494
Epoch: 64 Training R2: -9.11570781096897
Epoch: 65 Training R2: -9.072447299106793
Epoch: 66 Training R2: -9.029384182788233
Epoch: 67 Training R2: -8.986517561062545
Epoch: 68 Training R2: -8.943846537091105
Epoch: 69 Training R2: -8.901370218128635
Epoch: 70 Training R2: -8.859087715504542
Epoch: 71 Training R2: -8.816998144604293
Epoch: 72 Training R2: -8.775100624850923
Epoch: 73 Training R2: -8.7333942796866
Epoch: 74 Training R2: -8.69187823655428
Epoch: 75 Training R2: -8.650551626879437
Epoch: 76 Training R2: -8.609413586051916
Epoch: 77 Training R2: -8.568463253407797
Epoch: 78 Training R2: -8.52769977221142
Epoch: 79 Training R2: -8.487122289637433
Epoch: 80 Training R2: -8.44672995675296
Epoch: 81 Training R2: -8.406521928499817
Epoch: 82 Training R2: -8.366497363676848
Epoch: 83 Training R2: -8.326655424922302
Epoch: 84 Training R2: -8.286995278696324
Epoch: 85 Training R2: -8.2475160952635
Epoch: 86 Training R2: -8.208217048675495
Epoch: 87 Training R2: -8.169097316753781
Epoch: 88 Training R2: -8.130156081072405
Epoch: 89 Training R2: -8.091392526940894
Epoch: 90 Training R2: -8.052805843387167
Epoch: 91 Training R2: -8.014395223140607
Epoch: 92 Training R2: -7.976159862615125
Epoch: 93 Training R2: -7.938098961892376
Epoch: 94 Training R2: -7.9002117247050005
Epoch: 95 Training R2: -7.862497358419958
Epoch: 96 Training R2: -7.824955074021961
Epoch: 97 Training R2: -7.787584086096935
Epoch: 98 Training R2: -7.750383612815604
Epoch: 99 Training R2: -7.7133528759171135
Epoch: 100 Training R2: -7.676491100692754
Epoch: 101 Training R2: -7.639797515969745
Epoch: 102 Training R2: -7.603271354095089
Epoch: 103 Training R2: -7.566911850919521
Epoch: 104 Training R2: -7.530718245781502
Epoch: 105 Training R2: -7.49468978149131
Epoch: 106 Training R2: -7.4588257043151955
Epoch: 107 Training R2: -7.423125263959593
Epoch: 108 Training R2: -7.387587713555437
Epoch: 109 Training R2: -7.352212309642525
Epoch: 110 Training R2: -7.316998312153949
Epoch: 111 Training R2: -7.28194498440063
Epoch: 112 Training R2: -7.247051593055877
Epoch: 113 Training R2: -7.212317408140059
Epoch: 114 Training R2: -7.177741703005314
Epoch: 115 Training R2: -7.143323754320349
Epoch: 116 Training R2: -7.109062842055311
Epoch: 117 Training R2: -7.0749582494667
Epoch: 118 Training R2: -7.04100926308238
Epoch: 119 Training R2: -7.0072151726866565
Epoch: 120 Training R2: -6.973575271305388
Epoch: 121 Training R2: -6.940088855191221
Epoch: 122 Training R2: -6.906755223808841
Epoch: 123 Training R2: -6.873573679820323
Epoch: 124 Training R2: -6.840543529070531
Epoch: 125 Training R2: -6.80766408057259
Epoch: 126 Training R2: -6.774934646493444
Epoch: 127 Training R2: -6.742354542139429
Epoch: 128 Training R2: -6.709923085941979
Epoch: 129 Training R2: -6.677639599443331
Epoch: 130 Training R2: -6.64550340728235
Epoch: 131 Training R2: -6.613513837180384
Epoch: 132 Training R2: -6.581670219927198
Epoch: 133 Training R2: -6.549971889366969
Epoch: 134 Training R2: -6.51841818238434
Epoch: 135 Training R2: -6.487008438890558
Epoch: 136 Training R2: -6.455742001809637
Epoch: 137 Training R2: -6.424618217064627
Epoch: 138 Training R2: -6.393636433563918
Epoch: 139 Training R2: -6.36279600318761
Epoch: 140 Training R2: -6.332096280773959
Epoch: 141 Training R2: -6.301536624105866
Epoch: 142 Training R2: -6.2711163938974455
Epoch: 143 Training R2: -6.240834953780642
Epoch: 144 Training R2: -6.210691670291907
Epoch: 145 Training R2: -6.18068591285896
Epoch: 146 Training R2: -6.150817053787571
Epoch: 147 Training R2: -6.121084468248435
Epoch: 148 Training R2: -6.091487534264103
Epoch: 149 Training R2: -6.0620256326959465
Epoch: 150 Training R2: -6.032698147231221
Epoch: 151 Training R2: -6.003504464370151
Epoch: 152 Training R2: -5.974443973413105
Epoch: 153 Training R2: -5.945516066447807
Epoch: 154 Training R2: -5.916720138336611
Epoch: 155 Training R2: -5.88805558670385
Epoch: 156 Training R2: -5.859521811923219
Epoch: 157 Training R2: -5.831118217105229
Epoch: 158 Training R2: -5.802844208084713
Epoch: 159 Training R2: -5.7746991934084
Epoch: 160 Training R2: -5.74668258432253
Epoch: 161 Training R2: -5.7187937947605345
Epoch: 162 Training R2: -5.69103224133077
Epoch: 163 Training R2: -5.663397343304316
Epoch: 164 Training R2: -5.635888522602811
Epoch: 165 Training R2: -5.608505203786366
Epoch: 166 Training R2: -5.581246814041513
Epoch: 167 Training R2: -5.554112783169222
Epoch: 168 Training R2: -5.527102543572967
Epoch: 169 Training R2: -5.50021553024685
Epoch: 170 Training R2: -5.473451180763775
Epoch: 171 Training R2: -5.446808935263672
Epoch: 172 Training R2: -5.420288236441792
Epoch: 173 Training R2: -5.393888529537038
Epoch: 174 Training R2: -5.36760926232035
Epoch: 175 Training R2: -5.34144988508316
Epoch: 176 Training R2: -5.31540985062588
Epoch: 177 Training R2: -5.289488614246448
Epoch: 178 Training R2: -5.263685633728938
Epoch: 179 Training R2: -5.238000369332206
Epoch: 180 Training R2: -5.212432283778596
Epoch: 181 Training R2: -5.186980842242696
Epoch: 182 Training R2: -5.161645512340146
Epoch: 183 Training R2: -5.136425764116498
Epoch: 184 Training R2: -5.111321070036124
Epoch: 185 Training R2: -5.08633090497117
Epoch: 186 Training R2: -5.061454746190581
Epoch: 187 Training R2: -5.0366920733491485
Epoch: 188 Training R2: -5.012042368476623
Epoch: 189 Training R2: -4.987505115966879
Epoch: 190 Training R2: -4.963079802567125
Epoch: 191 Training R2: -4.938765917367153
Epoch: 192 Training R2: -4.9145629517886595
Epoch: 193 Training R2: -4.890470399574591
Epoch: 194 Training R2: -4.866487756778556
Epoch: 195 Training R2: -4.842614521754276
Epoch: 196 Training R2: -4.8188501951450915
Epoch: 197 Training R2: -4.795194279873503
Epoch: 198 Training R2: -4.771646281130779
Epoch: 199 Training R2: -4.748205706366589
Epoch: 200 Training R2: -4.724872065278709
Epoch: 201 Training R2: -4.70164486980275
Epoch: 202 Training R2: -4.678523634101949
Epoch: 203 Training R2: -4.655507874557002
Epoch: 204 Training R2: -4.632597109755938
Epoch: 205 Training R2: -4.609790860484055
Epoch: 206 Training R2: -4.587088649713876
Epoch: 207 Training R2: -4.564490002595181
Epoch: 208 Training R2: -4.5419944464450595
Epoch: 209 Training R2: -4.519601510738022
Epoch: 210 Training R2: -4.497310727096154
Epoch: 211 Training R2: -4.475121629279312
Epoch: 212 Training R2: -4.453033753175369
Epoch: 213 Training R2: -4.431046636790497
Epoch: 214 Training R2: -4.4091598202395055
Epoch: 215 Training R2: -4.38737284573621
Epoch: 216 Training R2: -4.3656852575838565
Epoch: 217 Training R2: -4.3440966021655845
Epoch: 218 Training R2: -4.322606427934933
Epoch: 219 Training R2: -4.301214285406389
Epoch: 220 Training R2: -4.279919727145982
Epoch: 221 Training R2: -4.258722307761925
Epoch: 222 Training R2: -4.237621583895287
Epoch: 223 Training R2: -4.216617114210717
Epoch: 224 Training R2: -4.195708459387208
Epoch: 225 Training R2: -4.174895182108906
Epoch: 226 Training R2: -4.154176847055952
Epoch: 227 Training R2: -4.133553020895378
Epoch: 228 Training R2: -4.113023272272033
Epoch: 229 Training R2: -4.092587171799559
Epoch: 230 Training R2: -4.07224429205141
Epoch: 231 Training R2: -4.0519942075518935
Epoch: 232 Training R2: -4.031836494767279
Epoch: 233 Training R2: -4.011770732096927
Epoch: 234 Training R2: -3.991796499864475
Epoch: 235 Training R2: -3.971913380309042
Epoch: 236 Training R2: -3.9521209575764953
Epoch: 237 Training R2: -3.9324188177107464
Epoch: 238 Training R2: -3.912806548645083
Epoch: 239 Training R2: -3.893283740193552
Epoch: 240 Training R2: -3.87384998404237
Epoch: 241 Training R2: -3.8545048737413845
Epoch: 242 Training R2: -3.8352480046955586
Epoch: 243 Training R2: -3.816078974156513
Epoch: 244 Training R2: -3.7969973812140916
Epoch: 245 Training R2: -3.7780028267879784
Epoch: 246 Training R2: -3.7590949136193332
Epoch: 247 Training R2: -3.7402732462624932
Epoch: 248 Training R2: -3.721537431076685
Epoch: 249 Training R2: -3.702887076217797
Epoch: 250 Training R2: -3.6843217916301647
Epoch: 251 Training R2: -3.665841189038426
Epoch: 252 Training R2: -3.647444881939383
Epoch: 253 Training R2: -3.6291324855939155
Epoch: 254 Training R2: -3.6109036170189315
Epoch: 255 Training R2: -3.5927578949793535
Epoch: 256 Training R2: -3.5746949399801355
Epoch: 257 Training R2: -3.556714374258326
Epoch: 258 Training R2: -3.5388158217751577
Epoch: 259 Training R2: -3.5209989082081847
Epoch: 260 Training R2: -3.5032632609434424
Epoch: 261 Training R2: -3.4856085090676503
Epoch: 262 Training R2: -3.4680342833604554
Epoch: 263 Training R2: -3.450540216286697
Epoch: 264 Training R2: -3.433125941988725
Epoch: 265 Training R2: -3.4157910962787295
Epoch: 266 Training R2: -3.3985353166311363
Epoch: 267 Training R2: -3.381358242175007
Epoch: 268 Training R2: -3.364259513686493
Epoch: 269 Training R2: -3.3472387735813154
Epoch: 270 Training R2: -3.3302956659072818
Epoch: 271 Training R2: -3.313429836336839
Epoch: 272 Training R2: -3.296640932159658
Epoch: 273 Training R2: -3.2799286022752483
Epoch: 274 Training R2: -3.263292497185616
Epoch: 275 Training R2: -3.2467322689879454
Epoch: 276 Training R2: -3.23024757136732
Epoch: 277 Training R2: -3.2138380595894755
Epoch: 278 Training R2: -3.1975033904935843
Epoch: 279 Training R2: -3.181243222485074
Epoch: 280 Training R2: -3.165057215528482
Epoch: 281 Training R2: -3.1489450311403324
Epoch: 282 Training R2: -3.132906332382059
Epoch: 283 Training R2: -3.11694078385295
Epoch: 284 Training R2: -3.101048051683134
Epoch: 285 Training R2: -3.0852278035265854
Epoch: 286 Training R2: -3.0694797085541747
Epoch: 287 Training R2: -3.053803437446745
Epoch: 288 Training R2: -3.0381986623882176
Epoch: 289 Training R2: -3.022665057058733
Epoch: 290 Training R2: -3.0072022966278213
Epoch: 291 Training R2: -2.991810057747607
Epoch: 292 Training R2: -2.9764880185460374
Epoch: 293 Training R2: -2.96123585862015
Epoch: 294 Training R2: -2.946053259029367
Epoch: 295 Training R2: -2.930939902288817
Epoch: 296 Training R2: -2.9158954723627
Epoch: 297 Training R2: -2.900919654657664
Epoch: 298 Training R2: -2.886012136016222
Epoch: 299 Training R2: -2.871172604710206
Epoch: 300 Training R2: -2.8564007504342377
Epoch: 301 Training R2: -2.8416962642992334
Epoch: 302 Training R2: -2.827058838825944
Epoch: 303 Training R2: -2.8124881679385165
Epoch: 304 Training R2: -2.7979839469580914
Epoch: 305 Training R2: -2.783545872596425
Epoch: 306 Training R2: -2.7691736429495433
Epoch: 307 Training R2: -2.7548669574914193
Epoch: 308 Training R2: -2.740625517067693
Epoch: 309 Training R2: -2.7264490238894044
Epoch: 310 Training R2: -2.7123371815267605
Epoch: 311 Training R2: -2.698289694902935
Epoch: 312 Training R2: -2.6843062702878933
Epoch: 313 Training R2: -2.670386615292244
Epoch: 314 Training R2: -2.6565304388611173
Epoch: 315 Training R2: -2.642737451268081
Epoch: 316 Training R2: -2.629007364109072
Epoch: 317 Training R2: -2.615339890296358
Epoch: 318 Training R2: -2.6017347440525387
Epoch: 319 Training R2: -2.588191640904557
Epoch: 320 Training R2: -2.574710297677749
Epoch: 321 Training R2: -2.5612904324899173
Epoch: 322 Training R2: -2.5479317647454316
Epoch: 323 Training R2: -2.534634015129358
Epoch: 324 Training R2: -2.521396905601612
Epoch: 325 Training R2: -2.5082201593911404
Epoch: 326 Training R2: -2.49510350099013
Epoch: 327 Training R2: -2.482046656148239
Epoch: 328 Training R2: -2.4690493518668624
Epoch: 329 Training R2: -2.456111316393415
Epoch: 330 Training R2: -2.443232279215644
Epoch: 331 Training R2: -2.4304119710559724
Epoch: 332 Training R2: -2.417650123865858
Epoch: 333 Training R2: -2.404946470820188
Epoch: 334 Training R2: -2.3923007463116943
Epoch: 335 Training R2: -2.379712685945391
Epoch: 336 Training R2: -2.3671820265330483
Epoch: 337 Training R2: -2.354708506087678
Epoch: 338 Training R2: -2.3422918638180534
Epoch: 339 Training R2: -2.329931840123255
Epoch: 340 Training R2: -2.3176281765872337
Epoch: 341 Training R2: -2.3053806159734
Epoch: 342 Training R2: -2.293188902219248
Epoch: 343 Training R2: -2.2810527804309917
Epoch: 344 Training R2: -2.268971996878232
Epoch: 345 Training R2: -2.2569462989886477
Epoch: 346 Training R2: -2.2449754353427065
Epoch: 347 Training R2: -2.2330591556684096
Epoch: 348 Training R2: -2.2211972108360465
Epoch: 349 Training R2: -2.209389352852987
Epoch: 350 Training R2: -2.1976353348584903
Epoch: 351 Training R2: -2.1859349111185358
Epoch: 352 Training R2: -2.1742878370206853
Epoch: 353 Training R2: -2.162693869068959
Epoch: 354 Training R2: -2.151152764878743
Epoch: 355 Training R2: -2.139664283171717
Epoch: 356 Training R2: -2.128228183770802
Epoch: 357 Training R2: -2.116844227595138
Epoch: 358 Training R2: -2.1055121766550764
Epoch: 359 Training R2: -2.0942317940472024
Epoch: 360 Training R2: -2.0830028439493766
Epoch: 361 Training R2: -2.071825091615799
Epoch: 362 Training R2: -2.060698303372098
Epoch: 363 Training R2: -2.0496222466104377
Epoch: 364 Training R2: -2.0385966897846535
Epoch: 365 Training R2: -2.0276214024054027
Epoch: 366 Training R2: -2.016696155035343
Epoch: 367 Training R2: -2.0058207192843307
Epoch: 368 Training R2: -1.9949948678046412
Epoch: 369 Training R2: -1.9842183742862116
Epoch: 370 Training R2: -1.9734910134519024
Epoch: 371 Training R2: -1.9628125610527856
Epoch: 372 Training R2: -1.9521827938634506
Epoch: 373 Training R2: -1.9416014896773328
Epoch: 374 Training R2: -1.9310684273020637
Epoch: 375 Training R2: -1.9205833865548403
Epoch: 376 Training R2: -1.91014614825782
Epoch: 377 Training R2: -1.8997564942335305
Epoch: 378 Training R2: -1.8894142073003075
Epoch: 379 Training R2: -1.879119071267748
Epoch: 380 Training R2: -1.868870870932183
Epoch: 381 Training R2: -1.8586693920721804
Epoch: 382 Training R2: -1.8485144214440545
Epoch: 383 Training R2: -1.83840574677741
Epoch: 384 Training R2: -1.828343156770694
Epoch: 385 Training R2: -1.818326441086778
Epoch: 386 Training R2: -1.8083553903485559
Epoch: 387 Training R2: -1.7984297961345588
Epoch: 388 Training R2: -1.7885494509745965
Epoch: 389 Training R2: -1.7787141483454163
Epoch: 390 Training R2: -1.7689236826663768
Epoch: 391 Training R2: -1.7591778492951495
Epoch: 392 Training R2: -1.749476444523435
Epoch: 393 Training R2: -1.7398192655727
Epoch: 394 Training R2: -1.7302061105899331
Epoch: 395 Training R2: -1.7206367786434216
Epoch: 396 Training R2: -1.7111110697185437
Epoch: 397 Training R2: -1.7016287847135878
Epoch: 398 Training R2: -1.6921897254355796
Epoch: 399 Training R2: -1.6827936945961413
Epoch: 400 Training R2: -1.6734404958073559
Epoch: 401 Training R2: -1.6641299335776614
Epoch: 402 Training R2: -1.654861813307761
Epoch: 403 Training R2: -1.645635941286546
Epoch: 404 Training R2: -1.6364521246870454
Epoch: 405 Training R2: -1.6273101715623888
Epoch: 406 Training R2: -1.6182098908417912
Epoch: 407 Training R2: -1.6091510923265528
Epoch: 408 Training R2: -1.6001335866860793
Epoch: 409 Training R2: -1.5911571854539184
Epoch: 410 Training R2: -1.582221701023819
Epoch: 411 Training R2: -1.5733269466458006
Epoch: 412 Training R2: -1.5644727364222497
Epoch: 413 Training R2: -1.555658885304025
Epoch: 414 Training R2: -1.546885209086588
Epoch: 415 Training R2: -1.5381515244061466
Epoch: 416 Training R2: -1.5294576487358187
Epoch: 417 Training R2: -1.5208034003818112
Epoch: 418 Training R2: -1.5121885984796184
Epoch: 419 Training R2: -1.5036130629902367
Epoch: 420 Training R2: -1.4950766146963974
Epoch: 421 Training R2: -1.4865790751988146
Epoch: 422 Training R2: -1.4781202669124536
Epoch: 423 Training R2: -1.469700013062814
Epoch: 424 Training R2: -1.4613181376822295
Epoch: 425 Training R2: -1.4529744656061858
Epoch: 426 Training R2: -1.4446688224696547
Epoch: 427 Training R2: -1.436401034703446
Epoch: 428 Training R2: -1.4281709295305731
Epoch: 429 Training R2: -1.4199783349626398
Epoch: 430 Training R2: -1.4118230797962399
Epoch: 431 Training R2: -1.4037049936093715
Epoch: 432 Training R2: -1.3956239067578764
Epoch: 433 Training R2: -1.387579650371885
Epoch: 434 Training R2: -1.3795720563522842
Epoch: 435 Training R2: -1.3716009573671992
Epoch: 436 Training R2: -1.363666186848492
Epoch: 437 Training R2: -1.355767578988274
Epoch: 438 Training R2: -1.34790496873544
Epoch: 439 Training R2: -1.3400781917922084
Epoch: 440 Training R2: -1.3322870846106878
Epoch: 441 Training R2: -1.3245314843894507
Epoch: 442 Training R2: -1.3168112290701308
Epoch: 443 Training R2: -1.3091261573340263
Epoch: 444 Training R2: -1.3014761085987288
Epoch: 445 Training R2: -1.2938609230147589
Epoch: 446 Training R2: -1.2862804414622224
Epoch: 447 Training R2: -1.2787345055474808
Epoch: 448 Training R2: -1.2712229575998384
Epoch: 449 Training R2: -1.263745640668236
Epoch: 450 Training R2: -1.2563023985179744
Epoch: 451 Training R2: -1.2488930756274401
Epoch: 452 Training R2: -1.2415175171848496
Epoch: 453 Training R2: -1.234175569085016
Epoch: 454 Training R2: -1.2268670779261148
Epoch: 455 Training R2: -1.2195918910064818
Epoch: 456 Training R2: -1.2123498563214126
Epoch: 457 Training R2: -1.2051408225599838
Epoch: 458 Training R2: -1.1979646391018846
Epoch: 459 Training R2: -1.1908211560142652
Epoch: 460 Training R2: -1.1837102240486028
Epoch: 461 Training R2: -1.1766316946375706
Epoch: 462 Training R2: -1.1695854198919364
Epoch: 463 Training R2: -1.1625712525974627

c:\Users\Gaurish Garg\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\core\fromnumeric.py:88: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\Gaurish Garg\AppData\Local\Temp\ipykernel_21288\3653339755.py:16: RuntimeWarning: overflow encountered in square
  r2t = 1 - (np.sum((predictions-y_tr)**2))/((np.sum((y_tr-np.mean(y_tr))**2)))

Epoch: 1579 Training R2: -inf
Epoch: 1580 Training R2: -inf
Epoch: 1581 Training R2: -inf
Epoch: 1582 Training R2: -inf
Epoch: 1583 Training R2: -inf
Epoch: 1584 Training R2: -inf
Epoch: 1585 Training R2: -inf
Epoch: 1586 Training R2: -inf
Epoch: 1587 Training R2: -inf
Epoch: 1588 Training R2: -inf
Epoch: 1589 Training R2: -inf
Epoch: 1590 Training R2: -inf
Epoch: 1591 Training R2: -inf
Epoch: 1592 Training R2: -inf
Epoch: 1593 Training R2: -inf
Epoch: 1594 Training R2: -inf
Epoch: 1595 Training R2: -inf
Epoch: 1596 Training R2: -inf
Epoch: 1597 Training R2: -inf
Epoch: 1598 Training R2: -inf
Epoch: 1599 Training R2: -inf
Epoch: 1600 Training R2: -inf
Epoch: 1601 Training R2: -inf
Epoch: 1602 Training R2: -inf
Epoch: 1603 Training R2: -inf
Epoch: 1604 Training R2: -inf
Epoch: 1605 Training R2: -inf
Epoch: 1606 Training R2: -inf
Epoch: 1607 Training R2: -inf
Epoch: 1608 Training R2: -inf
Epoch: 1609 Training R2: -inf
Epoch: 1610 Training R2: -inf
Epoch: 1611 Training R2: -inf
Epoch: 1612 Training R2: -inf
Epoch: 1613 Training R2: -inf
Epoch: 1614 Training R2: -inf
Epoch: 1615 Training R2: -inf
Epoch: 1616 Training R2: -inf
Epoch: 1617 Training R2: -inf
Epoch: 1618 Training R2: -inf
Epoch: 1619 Training R2: -inf
Epoch: 1620 Training R2: -inf
Epoch: 1621 Training R2: -inf
Epoch: 1622 Training R2: -inf
Epoch: 1623 Training R2: -inf
Epoch: 1624 Training R2: -inf
Epoch: 1625 Training R2: -inf
Epoch: 1626 Training R2: -inf
Epoch: 1627 Training R2: -inf
Epoch: 1628 Training R2: -inf
Epoch: 1629 Training R2: -inf
Epoch: 1630 Training R2: -inf
Epoch: 1631 Training R2: -inf
Epoch: 1632 Training R2: -inf
Epoch: 1633 Training R2: -inf
Epoch: 1634 Training R2: -inf
Epoch: 1635 Training R2: -inf
Epoch: 1636 Training R2: -inf
Epoch: 1637 Training R2: -inf
Epoch: 1638 Training R2: -inf
Epoch: 1639 Training R2: -inf
Epoch: 1640 Training R2: -inf
Epoch: 1641 Training R2: -inf
Epoch: 1642 Training R2: -inf
Epoch: 1643 Training R2: -inf
Epoch: 1644 Training R2: -inf
Epoch: 1645 Training R2: -inf
Epoch: 1646 Training R2: -inf
Epoch: 1647 Training R2: -inf
Epoch: 1648 Training R2: -inf
Epoch: 1649 Training R2: -inf
Epoch: 1650 Training R2: -inf
Epoch: 1651 Training R2: -inf
Epoch: 1652 Training R2: -inf
Epoch: 1653 Training R2: -inf
Epoch: 1654 Training R2: -inf
Epoch: 1655 Training R2: -inf
Epoch: 1656 Training R2: -inf
Epoch: 1657 Training R2: -inf
Epoch: 1658 Training R2: -inf
Epoch: 1659 Training R2: -inf
Epoch: 1660 Training R2: -inf
Epoch: 1661 Training R2: -inf
Epoch: 1662 Training R2: -inf
Epoch: 1663 Training R2: -inf
Epoch: 1664 Training R2: -inf
Epoch: 1665 Training R2: -inf
Epoch: 1666 Training R2: -inf
Epoch: 1667 Training R2: -inf
Epoch: 1668 Training R2: -inf
Epoch: 1669 Training R2: -inf
Epoch: 1670 Training R2: -inf
Epoch: 1671 Training R2: -inf
Epoch: 1672 Training R2: -inf
Epoch: 1673 Training R2: -inf
Epoch: 1674 Training R2: -inf
Epoch: 1675 Training R2: -inf
Epoch: 1676 Training R2: -inf
Epoch: 1677 Training R2: -inf
Epoch: 1678 Training R2: -inf
Epoch: 1679 Training R2: -inf
Epoch: 1680 Training R2: -inf
Epoch: 1681 Training R2: -inf
Epoch: 1682 Training R2: -inf
Epoch: 1683 Training R2: -inf
Epoch: 1684 Training R2: -inf
Epoch: 1685 Training R2: -inf
Epoch: 1686 Training R2: -inf
Epoch: 1687 Training R2: -inf
Epoch: 1688 Training R2: -inf
Epoch: 1689 Training R2: -inf
Epoch: 1690 Training R2: -inf
Epoch: 1691 Training R2: -inf
Epoch: 1692 Training R2: -inf
Epoch: 1693 Training R2: -inf
Epoch: 1694 Training R2: -inf
Epoch: 1695 Training R2: -inf
Epoch: 1696 Training R2: -inf
Epoch: 1697 Training R2: -inf
Epoch: 1698 Training R2: -inf
Epoch: 1699 Training R2: -inf
Epoch: 1700 Training R2: -inf
Epoch: 1701 Training R2: -inf
Epoch: 1702 Training R2: -inf
Epoch: 1703 Training R2: -inf
Epoch: 1704 Training R2: -inf
Epoch: 1705 Training R2: -inf
Epoch: 1706 Training R2: -inf
Epoch: 1707 Training R2: -inf
Epoch: 1708 Training R2: -inf
Epoch: 1709 Training R2: -inf
Epoch: 1710 Training R2: -inf
Epoch: 1711 Training R2: -inf
Epoch: 1712 Training R2: -inf
Epoch: 1713 Training R2: -inf
Epoch: 1714 Training R2: -inf
Epoch: 1715 Training R2: -inf
Epoch: 1716 Training R2: -inf
Epoch: 1717 Training R2: -inf
Epoch: 1718 Training R2: -inf
Epoch: 1719 Training R2: -inf
Epoch: 1720 Training R2: -inf
Epoch: 1721 Training R2: -inf
Epoch: 1722 Training R2: -inf
Epoch: 1723 Training R2: -inf
Epoch: 1724 Training R2: -inf
Epoch: 1725 Training R2: -inf
Epoch: 1726 Training R2: -inf
Epoch: 1727 Training R2: -inf
Epoch: 1728 Training R2: -inf
Epoch: 1729 Training R2: -inf
Epoch: 1730 Training R2: -inf
Epoch: 1731 Training R2: -inf
Epoch: 1732 Training R2: -inf
Epoch: 1733 Training R2: -inf
Epoch: 1734 Training R2: -inf
Epoch: 1735 Training R2: -inf
Epoch: 1736 Training R2: -inf
Epoch: 1737 Training R2: -inf
Epoch: 1738 Training R2: -inf
Epoch: 1739 Training R2: -inf
Epoch: 1740 Training R2: -inf
Epoch: 1741 Training R2: -inf
Epoch: 1742 Training R2: -inf
Epoch: 1743 Training R2: -inf
Epoch: 1744 Training R2: -inf
Epoch: 1745 Training R2: -inf
Epoch: 1746 Training R2: -inf
Epoch: 1747 Training R2: -inf
Epoch: 1748 Training R2: -inf
Epoch: 1749 Training R2: -inf
Epoch: 1750 Training R2: -inf
Epoch: 1751 Training R2: -inf
Epoch: 1752 Training R2: -inf
Epoch: 1753 Training R2: -inf
Epoch: 1754 Training R2: -inf
Epoch: 1755 Training R2: -inf
Epoch: 1756 Training R2: -inf
Epoch: 1757 Training R2: -inf
Epoch: 1758 Training R2: -inf
Epoch: 1759 Training R2: -inf
Epoch: 1760 Training R2: -inf
Epoch: 1761 Training R2: -inf
Epoch: 1762 Training R2: -inf
Epoch: 1763 Training R2: -inf
Epoch: 1764 Training R2: -inf
Epoch: 1765 Training R2: -inf
Epoch: 1766 Training R2: -inf
Epoch: 1767 Training R2: -inf
Epoch: 1768 Training R2: -inf
Epoch: 1769 Training R2: -inf
Epoch: 1770 Training R2: -inf
Epoch: 1771 Training R2: -inf
Epoch: 1772 Training R2: -inf
Epoch: 1773 Training R2: -inf
Epoch: 1774 Training R2: -inf
Epoch: 1775 Training R2: -inf
Epoch: 1776 Training R2: -inf
Epoch: 1777 Training R2: -inf
Epoch: 1778 Training R2: -inf
Epoch: 1779 Training R2: -inf
Epoch: 1780 Training R2: -inf
Epoch: 1781 Training R2: -inf
Epoch: 1782 Training R2: -inf
Epoch: 1783 Training R2: -inf
Epoch: 1784 Training R2: -inf
Epoch: 1785 Training R2: -inf
Epoch: 1786 Training R2: -inf
Epoch: 1787 Training R2: -inf
Epoch: 1788 Training R2: -inf
Epoch: 1789 Training R2: -inf
Epoch: 1790 Training R2: -inf
Epoch: 1791 Training R2: -inf
Epoch: 1792 Training R2: -inf
Epoch: 1793 Training R2: -inf
Epoch: 1794 Training R2: -inf
Epoch: 1795 Training R2: -inf
Epoch: 1796 Training R2: -inf
Epoch: 1797 Training R2: -inf
Epoch: 1798 Training R2: -inf
Epoch: 1799 Training R2: -inf
Epoch: 1800 Training R2: -inf
Epoch: 1801 Training R2: -inf
Epoch: 1802 Training R2: -inf
Epoch: 1803 Training R2: -inf
Epoch: 1804 Training R2: -inf
Epoch: 1805 Training R2: -inf
Epoch: 1806 Training R2: -inf
Epoch: 1807 Training R2: -inf
Epoch: 1808 Training R2: -inf
Epoch: 1809 Training R2: -inf
Epoch: 1810 Training R2: -inf
Epoch: 1811 Training R2: -inf
Epoch: 1812 Training R2: -inf
Epoch: 1813 Training R2: -inf
Epoch: 1814 Training R2: -inf
Epoch: 1815 Training R2: -inf
Epoch: 1816 Training R2: -inf
Epoch: 1817 Training R2: -inf
Epoch: 1818 Training R2: -inf
Epoch: 1819 Training R2: -inf
Epoch: 1820 Training R2: -inf
Epoch: 1821 Training R2: -inf
Epoch: 1822 Training R2: -inf
Epoch: 1823 Training R2: -inf
Epoch: 1824 Training R2: -inf
Epoch: 1825 Training R2: -inf
Epoch: 1826 Training R2: -inf
Epoch: 1827 Training R2: -inf
Epoch: 1828 Training R2: -inf
Epoch: 1829 Training R2: -inf
Epoch: 1830 Training R2: -inf
Epoch: 1831 Training R2: -inf
Epoch: 1832 Training R2: -inf
Epoch: 1833 Training R2: -inf
Epoch: 1834 Training R2: -inf
Epoch: 1835 Training R2: -inf
Epoch: 1836 Training R2: -inf
Epoch: 1837 Training R2: -inf
Epoch: 1838 Training R2: -inf
Epoch: 1839 Training R2: -inf
Epoch: 1840 Training R2: -inf
Epoch: 1841 Training R2: -inf
Epoch: 1842 Training R2: -inf
Epoch: 1843 Training R2: -inf
Epoch: 1844 Training R2: -inf
Epoch: 1845 Training R2: -inf
Epoch: 1846 Training R2: -inf
Epoch: 1847 Training R2: -inf
Epoch: 1848 Training R2: -inf
Epoch: 1849 Training R2: -inf
Epoch: 1850 Training R2: -inf
Epoch: 1851 Training R2: -inf
Epoch: 1852 Training R2: -inf
Epoch: 1853 Training R2: -inf
Epoch: 1854 Training R2: -inf
Epoch: 1855 Training R2: -inf
Epoch: 1856 Training R2: -inf
Epoch: 1857 Training R2: -inf
Epoch: 1858 Training R2: -inf
Epoch: 1859 Training R2: -inf
Epoch: 1860 Training R2: -inf
Epoch: 1861 Training R2: -inf
Epoch: 1862 Training R2: -inf
Epoch: 1863 Training R2: -inf
Epoch: 1864 Training R2: -inf
Epoch: 1865 Training R2: -inf
Epoch: 1866 Training R2: -inf
Epoch: 1867 Training R2: -inf
Epoch: 1868 Training R2: -inf
Epoch: 1869 Training R2: -inf
Epoch: 1870 Training R2: -inf
Epoch: 1871 Training R2: -inf
Epoch: 1872 Training R2: -inf
Epoch: 1873 Training R2: -inf
Epoch: 1874 Training R2: -inf
Epoch: 1875 Training R2: -inf
Epoch: 1876 Training R2: -inf
Epoch: 1877 Training R2: -inf
Epoch: 1878 Training R2: -inf
Epoch: 1879 Training R2: -inf
Epoch: 1880 Training R2: -inf
Epoch: 1881 Training R2: -inf
Epoch: 1882 Training R2: -inf
Epoch: 1883 Training R2: -inf
Epoch: 1884 Training R2: -inf
Epoch: 1885 Training R2: -inf
Epoch: 1886 Training R2: -inf
Epoch: 1887 Training R2: -inf
Epoch: 1888 Training R2: -inf
Epoch: 1889 Training R2: -inf
Epoch: 1890 Training R2: -inf
Epoch: 1891 Training R2: -inf
Epoch: 1892 Training R2: -inf
Epoch: 1893 Training R2: -inf
Epoch: 1894 Training R2: -inf
Epoch: 1895 Training R2: -inf
Epoch: 1896 Training R2: -inf
Epoch: 1897 Training R2: -inf
Epoch: 1898 Training R2: -inf
Epoch: 1899 Training R2: -inf
Epoch: 1900 Training R2: -inf
Epoch: 1901 Training R2: -inf
Epoch: 1902 Training R2: -inf
Epoch: 1903 Training R2: -inf
Epoch: 1904 Training R2: -inf
Epoch: 1905 Training R2: -inf
Epoch: 1906 Training R2: -inf
Epoch: 1907 Training R2: -inf
Epoch: 1908 Training R2: -inf
Epoch: 1909 Training R2: -inf
Epoch: 1910 Training R2: -inf
Epoch: 1911 Training R2: -inf
Epoch: 1912 Training R2: -inf
Epoch: 1913 Training R2: -inf
Epoch: 1914 Training R2: -inf
Epoch: 1915 Training R2: -inf
Epoch: 1916 Training R2: -inf
Epoch: 1917 Training R2: -inf
Epoch: 1918 Training R2: -inf
Epoch: 1919 Training R2: -inf
Epoch: 1920 Training R2: -inf
Epoch: 1921 Training R2: -inf
Epoch: 1922 Training R2: -inf
Epoch: 1923 Training R2: -inf
Epoch: 1924 Training R2: -inf
Epoch: 1925 Training R2: -inf
Epoch: 1926 Training R2: -inf
Epoch: 1927 Training R2: -inf
Epoch: 1928 Training R2: -inf
Epoch: 1929 Training R2: -inf
Epoch: 1930 Training R2: -inf
Epoch: 1931 Training R2: -inf
Epoch: 1932 Training R2: -inf
Epoch: 1933 Training R2: -inf
Epoch: 1934 Training R2: -inf
Epoch: 1935 Training R2: -inf
Epoch: 1936 Training R2: -inf
Epoch: 1937 Training R2: -inf
Epoch: 1938 Training R2: -inf
Epoch: 1939 Training R2: -inf
Epoch: 1940 Training R2: -inf
Epoch: 1941 Training R2: -inf
Epoch: 1942 Training R2: -inf
Epoch: 1943 Training R2: -inf
Epoch: 1944 Training R2: -inf
Epoch: 1945 Training R2: -inf
Epoch: 1946 Training R2: -inf
Epoch: 1947 Training R2: -inf
Epoch: 1948 Training R2: -inf
Epoch: 1949 Training R2: -inf
Epoch: 1950 Training R2: -inf
Epoch: 1951 Training R2: -inf
Epoch: 1952 Training R2: -inf
Epoch: 1953 Training R2: -inf
Epoch: 1954 Training R2: -inf
Epoch: 1955 Training R2: -inf
Epoch: 1956 Training R2: -inf
Epoch: 1957 Training R2: -inf
Epoch: 1958 Training R2: -inf
Epoch: 1959 Training R2: -inf
Epoch: 1960 Training R2: -inf
Epoch: 1961 Training R2: -inf
Epoch: 1962 Training R2: -inf
Epoch: 1963 Training R2: -inf
Epoch: 1964 Training R2: -inf
Epoch: 1965 Training R2: -inf
Epoch: 1966 Training R2: -inf
Epoch: 1967 Training R2: -inf
Epoch: 1968 Training R2: -inf
Epoch: 1969 Training R2: -inf
Epoch: 1970 Training R2: -inf
Epoch: 1971 Training R2: -inf
Epoch: 1972 Training R2: -inf
Epoch: 1973 Training R2: -inf
Epoch: 1974 Training R2: -inf
Epoch: 1975 Training R2: -inf
Epoch: 1976 Training R2: -inf
Epoch: 1977 Training R2: -inf
Epoch: 1978 Training R2: -inf
Epoch: 1979 Training R2: -inf
Epoch: 1980 Training R2: -inf
Epoch: 1981 Training R2: -inf
Epoch: 1982 Training R2: -inf
Epoch: 1983 Training R2: -inf
Epoch: 1984 Training R2: -inf
Epoch: 1985 Training R2: -inf
Epoch: 1986 Training R2: -inf
Epoch: 1987 Training R2: -inf
Epoch: 1988 Training R2: -inf
Epoch: 1989 Training R2: -inf
Epoch: 1990 Training R2: -inf
Epoch: 1991 Training R2: -inf
Epoch: 1992 Training R2: -inf
Epoch: 1993 Training R2: -inf
Epoch: 1994 Training R2: -inf
Epoch: 1995 Training R2: -inf
Epoch: 1996 Training R2: -inf
Epoch: 1997 Training R2: -inf
Epoch: 1998 Training R2: -inf
Epoch: 1999 Training R2: -inf
Epoch: 2000 Training R2: -inf
Epoch: 2001 Training R2: -inf
Epoch: 2002 Training R2: -inf
Epoch: 2003 Training R2: -inf
Epoch: 2004 Training R2: -inf
Epoch: 2005 Training R2: -inf
Epoch: 2006 Training R2: -inf
Epoch: 2007 Training R2: -inf
Epoch: 2008 Training R2: -inf
Epoch: 2009 Training R2: -inf
Epoch: 2010 Training R2: -inf
Epoch: 2011 Training R2: -inf
Epoch: 2012 Training R2: -inf
Epoch: 2013 Training R2: -inf
Epoch: 2014 Training R2: -inf
Epoch: 2015 Training R2: -inf
Epoch: 2016 Training R2: -inf
Epoch: 2017 Training R2: -inf
Epoch: 2018 Training R2: -inf
Epoch: 2019 Training R2: -inf
Epoch: 2020 Training R2: -inf
Epoch: 2021 Training R2: -inf
Epoch: 2022 Training R2: -inf
Epoch: 2023 Training R2: -inf
Epoch: 2024 Training R2: -inf
Epoch: 2025 Training R2: -inf
Epoch: 2026 Training R2: -inf
Epoch: 2027 Training R2: -inf
Epoch: 2028 Training R2: -inf
Epoch: 2029 Training R2: -inf
Epoch: 2030 Training R2: -inf
Epoch: 2031 Training R2: -inf
Epoch: 2032 Training R2: -inf
Epoch: 2033 Training R2: -inf
Epoch: 2034 Training R2: -inf
Epoch: 2035 Training R2: -inf
Epoch: 2036 Training R2: -inf
Epoch: 2037 Training R2: -inf
Epoch: 2038 Training R2: -inf
Epoch: 2039 Training R2: -inf
Epoch: 2040 Training R2: -inf
Epoch: 2041 Training R2: -inf
Epoch: 2042 Training R2: -inf
Epoch: 2043 Training R2: -inf
Epoch: 2044 Training R2: -inf
Epoch: 2045 Training R2: -inf
Epoch: 2046 Training R2: -inf
Epoch: 2047 Training R2: -inf
Epoch: 2048 Training R2: -inf
Epoch: 2049 Training R2: -inf
Epoch: 2050 Training R2: -inf
Epoch: 2051 Training R2: -inf
Epoch: 2052 Training R2: -inf
Epoch: 2053 Training R2: -inf
Epoch: 2054 Training R2: -inf
Epoch: 2055 Training R2: -inf
Epoch: 2056 Training R2: -inf
Epoch: 2057 Training R2: -inf
Epoch: 2058 Training R2: -inf
Epoch: 2059 Training R2: -inf
Epoch: 2060 Training R2: -inf
Epoch: 2061 Training R2: -inf
Epoch: 2062 Training R2: -inf
Epoch: 2063 Training R2: -inf
Epoch: 2064 Training R2: -inf
Epoch: 2065 Training R2: -inf
Epoch: 2066 Training R2: -inf
Epoch: 2067 Training R2: -inf
Epoch: 2068 Training R2: -inf
Epoch: 2069 Training R2: -inf
Epoch: 2070 Training R2: -inf
Epoch: 2071 Training R2: -inf
Epoch: 2072 Training R2: -inf
Epoch: 2073 Training R2: -inf
Epoch: 2074 Training R2: -inf
Epoch: 2075 Training R2: -inf
Epoch: 2076 Training R2: -inf
Epoch: 2077 Training R2: -inf
Epoch: 2078 Training R2: -inf
Epoch: 2079 Training R2: -inf
Epoch: 2080 Training R2: -inf
Epoch: 2081 Training R2: -inf
Epoch: 2082 Training R2: -inf
Epoch: 2083 Training R2: -inf
Epoch: 2084 Training R2: -inf
Epoch: 2085 Training R2: -inf
Epoch: 2086 Training R2: -inf
Epoch: 2087 Training R2: -inf
Epoch: 2088 Training R2: -inf
Epoch: 2089 Training R2: -inf
Epoch: 2090 Training R2: -inf
Epoch: 2091 Training R2: -inf
Epoch: 2092 Training R2: -inf
Epoch: 2093 Training R2: -inf
Epoch: 2094 Training R2: -inf
Epoch: 2095 Training R2: -inf
Epoch: 2096 Training R2: -inf
Epoch: 2097 Training R2: -inf
Epoch: 2098 Training R2: -inf
Epoch: 2099 Training R2: -inf
Epoch: 2100 Training R2: -inf
Epoch: 2101 Training R2: -inf
Epoch: 2102 Training R2: -inf
Epoch: 2103 Training R2: -inf
Epoch: 2104 Training R2: -inf
Epoch: 2105 Training R2: -inf
Epoch: 2106 Training R2: -inf
Epoch: 2107 Training R2: -inf
Epoch: 2108 Training R2: -inf
Epoch: 2109 Training R2: -inf
Epoch: 2110 Training R2: -inf
Epoch: 2111 Training R2: -inf
Epoch: 2112 Training R2: -inf
Epoch: 2113 Training R2: -inf
Epoch: 2114 Training R2: -inf
Epoch: 2115 Training R2: -inf
Epoch: 2116 Training R2: -inf
Epoch: 2117 Training R2: -inf
Epoch: 2118 Training R2: -inf
Epoch: 2119 Training R2: -inf
Epoch: 2120 Training R2: -inf
Epoch: 2121 Training R2: -inf
Epoch: 2122 Training R2: -inf
Epoch: 2123 Training R2: -inf
Epoch: 2124 Training R2: -inf
Epoch: 2125 Training R2: -inf
Epoch: 2126 Training R2: -inf
Epoch: 2127 Training R2: -inf
Epoch: 2128 Training R2: -inf
Epoch: 2129 Training R2: -inf
Epoch: 2130 Training R2: -inf
Epoch: 2131 Training R2: -inf
Epoch: 2132 Training R2: -inf
Epoch: 2133 Training R2: -inf
Epoch: 2134 Training R2: -inf
Epoch: 2135 Training R2: -inf
Epoch: 2136 Training R2: -inf
Epoch: 2137 Training R2: -inf
Epoch: 2138 Training R2: -inf
Epoch: 2139 Training R2: -inf
Epoch: 2140 Training R2: -inf
Epoch: 2141 Training R2: -inf
Epoch: 2142 Training R2: -inf
Epoch: 2143 Training R2: -inf
Epoch: 2144 Training R2: -inf
Epoch: 2145 Training R2: -inf
Epoch: 2146 Training R2: -inf
Epoch: 2147 Training R2: -inf
Epoch: 2148 Training R2: -inf
Epoch: 2149 Training R2: -inf
Epoch: 2150 Training R2: -inf
Epoch: 2151 Training R2: -inf
Epoch: 2152 Training R2: -inf
Epoch: 2153 Training R2: -inf
Epoch: 2154 Training R2: -inf
Epoch: 2155 Training R2: -inf
Epoch: 2156 Training R2: -inf
Epoch: 2157 Training R2: -inf
Epoch: 2158 Training R2: -inf
Epoch: 2159 Training R2: -inf
Epoch: 2160 Training R2: -inf
Epoch: 2161 Training R2: -inf
Epoch: 2162 Training R2: -inf
Epoch: 2163 Training R2: -inf
Epoch: 2164 Training R2: -inf
Epoch: 2165 Training R2: -inf
Epoch: 2166 Training R2: -inf
Epoch: 2167 Training R2: -inf
Epoch: 2168 Training R2: -inf
Epoch: 2169 Training R2: -inf
Epoch: 2170 Training R2: -inf
Epoch: 2171 Training R2: -inf
Epoch: 2172 Training R2: -inf
Epoch: 2173 Training R2: -inf
Epoch: 2174 Training R2: -inf
Epoch: 2175 Training R2: -inf
Epoch: 2176 Training R2: -inf
Epoch: 2177 Training R2: -inf
Epoch: 2178 Training R2: -inf
Epoch: 2179 Training R2: -inf
Epoch: 2180 Training R2: -inf
Epoch: 2181 Training R2: -inf
Epoch: 2182 Training R2: -inf
Epoch: 2183 Training R2: -inf
Epoch: 2184 Training R2: -inf
Epoch: 2185 Training R2: -inf
Epoch: 2186 Training R2: -inf
Epoch: 2187 Training R2: -inf
Epoch: 2188 Training R2: -inf
Epoch: 2189 Training R2: -inf
Epoch: 2190 Training R2: -inf
Epoch: 2191 Training R2: -inf
Epoch: 2192 Training R2: -inf
Epoch: 2193 Training R2: -inf
Epoch: 2194 Training R2: -inf
Epoch: 2195 Training R2: -inf
Epoch: 2196 Training R2: -inf
Epoch: 2197 Training R2: -inf
Epoch: 2198 Training R2: -inf
Epoch: 2199 Training R2: -inf
Epoch: 2200 Training R2: -inf
Epoch: 2201 Training R2: -inf
Epoch: 2202 Training R2: -inf
Epoch: 2203 Training R2: -inf
Epoch: 2204 Training R2: -inf
Epoch: 2205 Training R2: -inf
Epoch: 2206 Training R2: -inf
Epoch: 2207 Training R2: -inf
Epoch: 2208 Training R2: -inf
Epoch: 2209 Training R2: -inf
Epoch: 2210 Training R2: -inf
Epoch: 2211 Training R2: -inf
Epoch: 2212 Training R2: -inf
Epoch: 2213 Training R2: -inf
Epoch: 2214 Training R2: -inf
Epoch: 2215 Training R2: -inf
Epoch: 2216 Training R2: -inf
Epoch: 2217 Training R2: -inf
Epoch: 2218 Training R2: -inf
Epoch: 2219 Training R2: -inf
Epoch: 2220 Training R2: -inf
Epoch: 2221 Training R2: -inf
Epoch: 2222 Training R2: -inf
Epoch: 2223 Training R2: -inf
Epoch: 2224 Training R2: -inf
Epoch: 2225 Training R2: -inf
Epoch: 2226 Training R2: -inf
Epoch: 2227 Training R2: -inf
Epoch: 2228 Training R2: -inf
Epoch: 2229 Training R2: -inf
Epoch: 2230 Training R2: -inf
Epoch: 2231 Training R2: -inf
Epoch: 2232 Training R2: -inf
Epoch: 2233 Training R2: -inf
Epoch: 2234 Training R2: -inf
Epoch: 2235 Training R2: -inf
Epoch: 2236 Training R2: -inf
Epoch: 2237 Training R2: -inf
Epoch: 2238 Training R2: -inf
Epoch: 2239 Training R2: -inf
Epoch: 2240 Training R2: -inf
Epoch: 2241 Training R2: -inf
Epoch: 2242 Training R2: -inf
Epoch: 2243 Training R2: -inf
Epoch: 2244 Training R2: -inf

C:\Users\Gaurish Garg\AppData\Local\Temp\ipykernel_21288\3653339755.py:14: RuntimeWarning: overflow encountered in matmul
  gradient = 1/n*np.matmul(x_tr1.transpose(),errors)
C:\Users\Gaurish Garg\AppData\Local\Temp\ipykernel_21288\3653339755.py:15: RuntimeWarning: invalid value encountered in subtract
  betas = betas - alpha*gradient

Epoch: 3627 Training R2: nan
Epoch: 3628 Training R2: nan
Epoch: 3629 Training R2: nan
Epoch: 3630 Training R2: nan
Epoch: 3631 Training R2: nan
Epoch: 3632 Training R2: nan
Epoch: 3633 Training R2: nan
Epoch: 3634 Training R2: nan
Epoch: 3635 Training R2: nan
Epoch: 3636 Training R2: nan
Epoch: 3637 Training R2: nan
Epoch: 3638 Training R2: nan
Epoch: 3639 Training R2: nan
Epoch: 3640 Training R2: nan
Epoch: 3641 Training R2: nan
Epoch: 3642 Training R2: nan
Epoch: 3643 Training R2: nan
Epoch: 3644 Training R2: nan
Epoch: 3645 Training R2: nan
Epoch: 3646 Training R2: nan
Epoch: 3647 Training R2: nan
Epoch: 3648 Training R2: nan
Epoch: 3649 Training R2: nan
Epoch: 3650 Training R2: nan
Epoch: 3651 Training R2: nan
Epoch: 3652 Training R2: nan
Epoch: 3653 Training R2: nan
Epoch: 3654 Training R2: nan
Epoch: 3655 Training R2: nan
Epoch: 3656 Training R2: nan
Epoch: 3657 Training R2: nan
Epoch: 3658 Training R2: nan
Epoch: 3659 Training R2: nan
Epoch: 3660 Training R2: nan
Epoch: 3661 Training R2: nan
Epoch: 3662 Training R2: nan
Epoch: 3663 Training R2: nan
Epoch: 3664 Training R2: nan
Epoch: 3665 Training R2: nan
Epoch: 3666 Training R2: nan
Epoch: 3667 Training R2: nan
Epoch: 3668 Training R2: nan
Epoch: 3669 Training R2: nan
Epoch: 3670 Training R2: nan
Epoch: 3671 Training R2: nan
Epoch: 3672 Training R2: nan
Epoch: 3673 Training R2: nan
Epoch: 3674 Training R2: nan
Epoch: 3675 Training R2: nan
Epoch: 3676 Training R2: nan
Epoch: 3677 Training R2: nan
Epoch: 3678 Training R2: nan
Epoch: 3679 Training R2: nan
Epoch: 3680 Training R2: nan
Epoch: 3681 Training R2: nan
Epoch: 3682 Training R2: nan
Epoch: 3683 Training R2: nan
Epoch: 3684 Training R2: nan
Epoch: 3685 Training R2: nan
Epoch: 3686 Training R2: nan
Epoch: 3687 Training R2: nan
Epoch: 3688 Training R2: nan
Epoch: 3689 Training R2: nan
Epoch: 3690 Training R2: nan
Epoch: 3691 Training R2: nan
Epoch: 3692 Training R2: nan
Epoch: 3693 Training R2: nan
Epoch: 3694 Training R2: nan
Epoch: 3695 Training R2: nan
Epoch: 3696 Training R2: nan
Epoch: 3697 Training R2: nan
Epoch: 3698 Training R2: nan
Epoch: 3699 Training R2: nan
Epoch: 3700 Training R2: nan
Epoch: 3701 Training R2: nan
Epoch: 3702 Training R2: nan
Epoch: 3703 Training R2: nan
Epoch: 3704 Training R2: nan
Epoch: 3705 Training R2: nan
Epoch: 3706 Training R2: nan
Epoch: 3707 Training R2: nan
Epoch: 3708 Training R2: nan
Epoch: 3709 Training R2: nan
Epoch: 3710 Training R2: nan
Epoch: 3711 Training R2: nan
Epoch: 3712 Training R2: nan
Epoch: 3713 Training R2: nan
Epoch: 3714 Training R2: nan
Epoch: 3715 Training R2: nan
Epoch: 3716 Training R2: nan
Epoch: 3717 Training R2: nan
Epoch: 3718 Training R2: nan
Epoch: 3719 Training R2: nan
Epoch: 3720 Training R2: nan
Epoch: 3721 Training R2: nan
Epoch: 3722 Training R2: nan
Epoch: 3723 Training R2: nan
Epoch: 3724 Training R2: nan
Epoch: 3725 Training R2: nan
Epoch: 3726 Training R2: nan
Epoch: 3727 Training R2: nan
Epoch: 3728 Training R2: nan
Epoch: 3729 Training R2: nan
Epoch: 3730 Training R2: nan
Epoch: 3731 Training R2: nan
Epoch: 3732 Training R2: nan
Epoch: 3733 Training R2: nan
Epoch: 3734 Training R2: nan
Epoch: 3735 Training R2: nan
Epoch: 3736 Training R2: nan
Epoch: 3737 Training R2: nan
Epoch: 3738 Training R2: nan
Epoch: 3739 Training R2: nan
Epoch: 3740 Training R2: nan
Epoch: 3741 Training R2: nan
Epoch: 3742 Training R2: nan
Epoch: 3743 Training R2: nan
Epoch: 3744 Training R2: nan
Epoch: 3745 Training R2: nan
Epoch: 3746 Training R2: nan
Epoch: 3747 Training R2: nan
Epoch: 3748 Training R2: nan
Epoch: 3749 Training R2: nan
Epoch: 3750 Training R2: nan
Epoch: 3751 Training R2: nan
Epoch: 3752 Training R2: nan
Epoch: 3753 Training R2: nan
Epoch: 3754 Training R2: nan
Epoch: 3755 Training R2: nan
Epoch: 3756 Training R2: nan
Epoch: 3757 Training R2: nan
Epoch: 3758 Training R2: nan
Epoch: 3759 Training R2: nan
Epoch: 3760 Training R2: nan
Epoch: 3761 Training R2: nan
Epoch: 3762 Training R2: nan
Epoch: 3763 Training R2: nan
Epoch: 3764 Training R2: nan
Epoch: 3765 Training R2: nan
Epoch: 3766 Training R2: nan
Epoch: 3767 Training R2: nan
Epoch: 3768 Training R2: nan
Epoch: 3769 Training R2: nan
Epoch: 3770 Training R2: nan
Epoch: 3771 Training R2: nan
Epoch: 3772 Training R2: nan
Epoch: 3773 Training R2: nan
Epoch: 3774 Training R2: nan
Epoch: 3775 Training R2: nan
Epoch: 3776 Training R2: nan
Epoch: 3777 Training R2: nan
Epoch: 3778 Training R2: nan
Epoch: 3779 Training R2: nan
Epoch: 3780 Training R2: nan
Epoch: 3781 Training R2: nan
Epoch: 3782 Training R2: nan
Epoch: 3783 Training R2: nan
Epoch: 3784 Training R2: nan
Epoch: 3785 Training R2: nan
Epoch: 3786 Training R2: nan
Epoch: 3787 Training R2: nan
Epoch: 3788 Training R2: nan
Epoch: 3789 Training R2: nan
Epoch: 3790 Training R2: nan
Epoch: 3791 Training R2: nan
Epoch: 3792 Training R2: nan
Epoch: 3793 Training R2: nan
Epoch: 3794 Training R2: nan
Epoch: 3795 Training R2: nan
Epoch: 3796 Training R2: nan
Epoch: 3797 Training R2: nan
Epoch: 3798 Training R2: nan
Epoch: 3799 Training R2: nan
Epoch: 3800 Training R2: nan
Epoch: 3801 Training R2: nan
Epoch: 3802 Training R2: nan
Epoch: 3803 Training R2: nan
Epoch: 3804 Training R2: nan
Epoch: 3805 Training R2: nan
Epoch: 3806 Training R2: nan
Epoch: 3807 Training R2: nan
Epoch: 3808 Training R2: nan
Epoch: 3809 Training R2: nan
Epoch: 3810 Training R2: nan
Epoch: 3811 Training R2: nan
Epoch: 3812 Training R2: nan
Epoch: 3813 Training R2: nan
Epoch: 3814 Training R2: nan
Epoch: 3815 Training R2: nan
Epoch: 3816 Training R2: nan
Epoch: 3817 Training R2: nan
Epoch: 3818 Training R2: nan
Epoch: 3819 Training R2: nan
Epoch: 3820 Training R2: nan
Epoch: 3821 Training R2: nan
Epoch: 3822 Training R2: nan
Epoch: 3823 Training R2: nan
Epoch: 3824 Training R2: nan
Epoch: 3825 Training R2: nan
Epoch: 3826 Training R2: nan
Epoch: 3827 Training R2: nan
Epoch: 3828 Training R2: nan
Epoch: 3829 Training R2: nan
Epoch: 3830 Training R2: nan
Epoch: 3831 Training R2: nan
Epoch: 3832 Training R2: nan
Epoch: 3833 Training R2: nan
Epoch: 3834 Training R2: nan
Epoch: 3835 Training R2: nan
Epoch: 3836 Training R2: nan
Epoch: 3837 Training R2: nan
Epoch: 3838 Training R2: nan
Epoch: 3839 Training R2: nan
Epoch: 3840 Training R2: nan
Epoch: 3841 Training R2: nan
Epoch: 3842 Training R2: nan
Epoch: 3843 Training R2: nan
Epoch: 3844 Training R2: nan
Epoch: 3845 Training R2: nan
Epoch: 3846 Training R2: nan
Epoch: 3847 Training R2: nan
Epoch: 3848 Training R2: nan
Epoch: 3849 Training R2: nan
Epoch: 3850 Training R2: nan
Epoch: 3851 Training R2: nan
Epoch: 3852 Training R2: nan
Epoch: 3853 Training R2: nan
Epoch: 3854 Training R2: nan
Epoch: 3855 Training R2: nan
Epoch: 3856 Training R2: nan
Epoch: 3857 Training R2: nan
Epoch: 3858 Training R2: nan
Epoch: 3859 Training R2: nan
Epoch: 3860 Training R2: nan
Epoch: 3861 Training R2: nan
Epoch: 3862 Training R2: nan
Epoch: 3863 Training R2: nan
Epoch: 3864 Training R2: nan
Epoch: 3865 Training R2: nan
Epoch: 3866 Training R2: nan
Epoch: 3867 Training R2: nan
Epoch: 3868 Training R2: nan
Epoch: 3869 Training R2: nan
Epoch: 3870 Training R2: nan
Epoch: 3871 Training R2: nan
Epoch: 3872 Training R2: nan
Epoch: 3873 Training R2: nan
Epoch: 3874 Training R2: nan
Epoch: 3875 Training R2: nan
Epoch: 3876 Training R2: nan
Epoch: 3877 Training R2: nan
Epoch: 3878 Training R2: nan
Epoch: 3879 Training R2: nan
Epoch: 3880 Training R2: nan
Epoch: 3881 Training R2: nan
Epoch: 3882 Training R2: nan
Epoch: 3883 Training R2: nan
Epoch: 3884 Training R2: nan
Epoch: 3885 Training R2: nan
Epoch: 3886 Training R2: nan
Epoch: 3887 Training R2: nan
Epoch: 3888 Training R2: nan
Epoch: 3889 Training R2: nan
Epoch: 3890 Training R2: nan
Epoch: 3891 Training R2: nan
Epoch: 3892 Training R2: nan
Epoch: 3893 Training R2: nan
Epoch: 3894 Training R2: nan
Epoch: 3895 Training R2: nan
Epoch: 3896 Training R2: nan
Epoch: 3897 Training R2: nan
Epoch: 3898 Training R2: nan
Epoch: 3899 Training R2: nan
Epoch: 3900 Training R2: nan
Epoch: 3901 Training R2: nan
Epoch: 3902 Training R2: nan
Epoch: 3903 Training R2: nan
Epoch: 3904 Training R2: nan
Epoch: 3905 Training R2: nan
Epoch: 3906 Training R2: nan
Epoch: 3907 Training R2: nan
Epoch: 3908 Training R2: nan
Epoch: 3909 Training R2: nan
Epoch: 3910 Training R2: nan
Epoch: 3911 Training R2: nan
Epoch: 3912 Training R2: nan
Epoch: 3913 Training R2: nan
Epoch: 3914 Training R2: nan
Epoch: 3915 Training R2: nan
Epoch: 3916 Training R2: nan
Epoch: 3917 Training R2: nan
Epoch: 3918 Training R2: nan
Epoch: 3919 Training R2: nan
Epoch: 3920 Training R2: nan
Epoch: 3921 Training R2: nan
Epoch: 3922 Training R2: nan
Epoch: 3923 Training R2: nan
Epoch: 3924 Training R2: nan
Epoch: 3925 Training R2: nan
Epoch: 3926 Training R2: nan
Epoch: 3927 Training R2: nan
Epoch: 3928 Training R2: nan
Epoch: 3929 Training R2: nan
Epoch: 3930 Training R2: nan
Epoch: 3931 Training R2: nan
Epoch: 3932 Training R2: nan
Epoch: 3933 Training R2: nan
Epoch: 3934 Training R2: nan
Epoch: 3935 Training R2: nan
Epoch: 3936 Training R2: nan
Epoch: 3937 Training R2: nan
Epoch: 3938 Training R2: nan
Epoch: 3939 Training R2: nan
Epoch: 3940 Training R2: nan
Epoch: 3941 Training R2: nan
Epoch: 3942 Training R2: nan
Epoch: 3943 Training R2: nan
Epoch: 3944 Training R2: nan
Epoch: 3945 Training R2: nan
Epoch: 3946 Training R2: nan
Epoch: 3947 Training R2: nan
Epoch: 3948 Training R2: nan
Epoch: 3949 Training R2: nan
Epoch: 3950 Training R2: nan
Epoch: 3951 Training R2: nan
Epoch: 3952 Training R2: nan
Epoch: 3953 Training R2: nan
Epoch: 3954 Training R2: nan
Epoch: 3955 Training R2: nan
Epoch: 3956 Training R2: nan
Epoch: 3957 Training R2: nan
Epoch: 3958 Training R2: nan
Epoch: 3959 Training R2: nan
Epoch: 3960 Training R2: nan
Epoch: 3961 Training R2: nan
Epoch: 3962 Training R2: nan
Epoch: 3963 Training R2: nan
Epoch: 3964 Training R2: nan
Epoch: 3965 Training R2: nan
Epoch: 3966 Training R2: nan
Epoch: 3967 Training R2: nan
Epoch: 3968 Training R2: nan
Epoch: 3969 Training R2: nan
Epoch: 3970 Training R2: nan
Epoch: 3971 Training R2: nan
Epoch: 3972 Training R2: nan
Epoch: 3973 Training R2: nan
Epoch: 3974 Training R2: nan
Epoch: 3975 Training R2: nan
Epoch: 3976 Training R2: nan
Epoch: 3977 Training R2: nan
Epoch: 3978 Training R2: nan
Epoch: 3979 Training R2: nan
Epoch: 3980 Training R2: nan
Epoch: 3981 Training R2: nan
Epoch: 3982 Training R2: nan
Epoch: 3983 Training R2: nan
Epoch: 3984 Training R2: nan
Epoch: 3985 Training R2: nan
Epoch: 3986 Training R2: nan
Epoch: 3987 Training R2: nan
Epoch: 3988 Training R2: nan
Epoch: 3989 Training R2: nan
Epoch: 3990 Training R2: nan
Epoch: 3991 Training R2: nan
Epoch: 3992 Training R2: nan
Epoch: 3993 Training R2: nan
Epoch: 3994 Training R2: nan
Epoch: 3995 Training R2: nan
Epoch: 3996 Training R2: nan
Epoch: 3997 Training R2: nan
Epoch: 3998 Training R2: nan
Epoch: 3999 Training R2: nan
Epoch: 4000 Training R2: nan
Epoch: 4001 Training R2: nan
Epoch: 4002 Training R2: nan
Epoch: 4003 Training R2: nan
Epoch: 4004 Training R2: nan
Epoch: 4005 Training R2: nan
Epoch: 4006 Training R2: nan
Epoch: 4007 Training R2: nan
Epoch: 4008 Training R2: nan
Epoch: 4009 Training R2: nan
Epoch: 4010 Training R2: nan
Epoch: 4011 Training R2: nan
Epoch: 4012 Training R2: nan
Epoch: 4013 Training R2: nan
Epoch: 4014 Training R2: nan
Epoch: 4015 Training R2: nan
Epoch: 4016 Training R2: nan
Epoch: 4017 Training R2: nan
Epoch: 4018 Training R2: nan
Epoch: 4019 Training R2: nan
Epoch: 4020 Training R2: nan
Epoch: 4021 Training R2: nan
Epoch: 4022 Training R2: nan
Epoch: 4023 Training R2: nan
Epoch: 4024 Training R2: nan
Epoch: 4025 Training R2: nan
Epoch: 4026 Training R2: nan
Epoch: 4027 Training R2: nan
Epoch: 4028 Training R2: nan
Epoch: 4029 Training R2: nan
Epoch: 4030 Training R2: nan
Epoch: 4031 Training R2: nan
Epoch: 4032 Training R2: nan
Epoch: 4033 Training R2: nan
Epoch: 4034 Training R2: nan
Epoch: 4035 Training R2: nan
Epoch: 4036 Training R2: nan
Epoch: 4037 Training R2: nan
Epoch: 4038 Training R2: nan
Epoch: 4039 Training R2: nan
Epoch: 4040 Training R2: nan
Epoch: 4041 Training R2: nan
Epoch: 4042 Training R2: nan
Epoch: 4043 Training R2: nan
Epoch: 4044 Training R2: nan
Epoch: 4045 Training R2: nan
Epoch: 4046 Training R2: nan
Epoch: 4047 Training R2: nan
Epoch: 4048 Training R2: nan
Epoch: 4049 Training R2: nan
Epoch: 4050 Training R2: nan
Epoch: 4051 Training R2: nan
Epoch: 4052 Training R2: nan
Epoch: 4053 Training R2: nan
Epoch: 4054 Training R2: nan
Epoch: 4055 Training R2: nan
Epoch: 4056 Training R2: nan
Epoch: 4057 Training R2: nan
Epoch: 4058 Training R2: nan
Epoch: 4059 Training R2: nan
Epoch: 4060 Training R2: nan
Epoch: 4061 Training R2: nan
Epoch: 4062 Training R2: nan
Epoch: 4063 Training R2: nan
Epoch: 4064 Training R2: nan
Epoch: 4065 Training R2: nan
Epoch: 4066 Training R2: nan
Epoch: 4067 Training R2: nan
Epoch: 4068 Training R2: nan
Epoch: 4069 Training R2: nan
Epoch: 4070 Training R2: nan
Epoch: 4071 Training R2: nan
Epoch: 4072 Training R2: nan
Epoch: 4073 Training R2: nan
Epoch: 4074 Training R2: nan
Epoch: 4075 Training R2: nan
Epoch: 4076 Training R2: nan
Epoch: 4077 Training R2: nan
Epoch: 4078 Training R2: nan
Epoch: 4079 Training R2: nan
Epoch: 4080 Training R2: nan
Epoch: 4081 Training R2: nan
Epoch: 4082 Training R2: nan
Epoch: 4083 Training R2: nan
Epoch: 4084 Training R2: nan
Epoch: 4085 Training R2: nan
Epoch: 4086 Training R2: nan
Epoch: 4087 Training R2: nan
Epoch: 4088 Training R2: nan
Epoch: 4089 Training R2: nan
Epoch: 4090 Training R2: nan
Epoch: 4091 Training R2: nan
Epoch: 4092 Training R2: nan
Epoch: 4093 Training R2: nan
Epoch: 4094 Training R2: nan
Epoch: 4095 Training R2: nan
Epoch: 4096 Training R2: nan
Epoch: 4097 Training R2: nan
Epoch: 4098 Training R2: nan
Epoch: 4099 Training R2: nan
Epoch: 4100 Training R2: nan
Epoch: 4101 Training R2: nan
Epoch: 4102 Training R2: nan
Epoch: 4103 Training R2: nan
Epoch: 4104 Training R2: nan
Epoch: 4105 Training R2: nan
Epoch: 4106 Training R2: nan
Epoch: 4107 Training R2: nan
Epoch: 4108 Training R2: nan
Epoch: 4109 Training R2: nan
Epoch: 4110 Training R2: nan
Epoch: 4111 Training R2: nan
Epoch: 4112 Training R2: nan
Epoch: 4113 Training R2: nan
Epoch: 4114 Training R2: nan
Epoch: 4115 Training R2: nan
Epoch: 4116 Training R2: nan
Epoch: 4117 Training R2: nan
Epoch: 4118 Training R2: nan
Epoch: 4119 Training R2: nan
Epoch: 4120 Training R2: nan
Epoch: 4121 Training R2: nan
Epoch: 4122 Training R2: nan
Epoch: 4123 Training R2: nan
Epoch: 4124 Training R2: nan
Epoch: 4125 Training R2: nan
Epoch: 4126 Training R2: nan
Epoch: 4127 Training R2: nan
Epoch: 4128 Training R2: nan
Epoch: 4129 Training R2: nan
Epoch: 4130 Training R2: nan
Epoch: 4131 Training R2: nan
Epoch: 4132 Training R2: nan
Epoch: 4133 Training R2: nan
Epoch: 4134 Training R2: nan
Epoch: 4135 Training R2: nan
Epoch: 4136 Training R2: nan
Epoch: 4137 Training R2: nan
Epoch: 4138 Training R2: nan
Epoch: 4139 Training R2: nan
Epoch: 4140 Training R2: nan
Epoch: 4141 Training R2: nan
Epoch: 4142 Training R2: nan
Epoch: 4143 Training R2: nan
Epoch: 4144 Training R2: nan
Epoch: 4145 Training R2: nan
Epoch: 4146 Training R2: nan
Epoch: 4147 Training R2: nan
Epoch: 4148 Training R2: nan
Epoch: 4149 Training R2: nan
Epoch: 4150 Training R2: nan
Epoch: 4151 Training R2: nan
Epoch: 4152 Training R2: nan
Epoch: 4153 Training R2: nan
Epoch: 4154 Training R2: nan
Epoch: 4155 Training R2: nan
Epoch: 4156 Training R2: nan
Epoch: 4157 Training R2: nan
Epoch: 4158 Training R2: nan
Epoch: 4159 Training R2: nan
Epoch: 4160 Training R2: nan
Epoch: 4161 Training R2: nan
Epoch: 4162 Training R2: nan
Epoch: 4163 Training R2: nan
Epoch: 4164 Training R2: nan
Epoch: 4165 Training R2: nan
Epoch: 4166 Training R2: nan
Epoch: 4167 Training R2: nan
Epoch: 4168 Training R2: nan
Epoch: 4169 Training R2: nan
Epoch: 4170 Training R2: nan
Epoch: 4171 Training R2: nan
Epoch: 4172 Training R2: nan
Epoch: 4173 Training R2: nan
Epoch: 4174 Training R2: nan
Epoch: 4175 Training R2: nan
Epoch: 4176 Training R2: nan
Epoch: 4177 Training R2: nan
Epoch: 4178 Training R2: nan
Epoch: 4179 Training R2: nan
Epoch: 4180 Training R2: nan
Epoch: 4181 Training R2: nan
Epoch: 4182 Training R2: nan
Epoch: 4183 Training R2: nan
Epoch: 4184 Training R2: nan
Epoch: 4185 Training R2: nan
Epoch: 4186 Training R2: nan
Epoch: 4187 Training R2: nan
Epoch: 4188 Training R2: nan
Epoch: 4189 Training R2: nan
Epoch: 4190 Training R2: nan
Epoch: 4191 Training R2: nan
Epoch: 4192 Training R2: nan
Epoch: 4193 Training R2: nan
Epoch: 4194 Training R2: nan
Epoch: 4195 Training R2: nan
Epoch: 4196 Training R2: nan
Epoch: 4197 Training R2: nan
Epoch: 4198 Training R2: nan
Epoch: 4199 Training R2: nan
Epoch: 4200 Training R2: nan
Epoch: 4201 Training R2: nan
Epoch: 4202 Training R2: nan
Epoch: 4203 Training R2: nan
Epoch: 4204 Training R2: nan
Epoch: 4205 Training R2: nan
Epoch: 4206 Training R2: nan
Epoch: 4207 Training R2: nan
Epoch: 4208 Training R2: nan
Epoch: 4209 Training R2: nan
Epoch: 4210 Training R2: nan
Epoch: 4211 Training R2: nan
Epoch: 4212 Training R2: nan
Epoch: 4213 Training R2: nan
Epoch: 4214 Training R2: nan
Epoch: 4215 Training R2: nan
Epoch: 4216 Training R2: nan
Epoch: 4217 Training R2: nan
Epoch: 4218 Training R2: nan
Epoch: 4219 Training R2: nan
Epoch: 4220 Training R2: nan
Epoch: 4221 Training R2: nan
Epoch: 4222 Training R2: nan
Epoch: 4223 Training R2: nan
Epoch: 4224 Training R2: nan
Epoch: 4225 Training R2: nan
Epoch: 4226 Training R2: nan
Epoch: 4227 Training R2: nan
Epoch: 4228 Training R2: nan
Epoch: 4229 Training R2: nan
Epoch: 4230 Training R2: nan
Epoch: 4231 Training R2: nan
Epoch: 4232 Training R2: nan
Epoch: 4233 Training R2: nan
Epoch: 4234 Training R2: nan
Epoch: 4235 Training R2: nan
Epoch: 4236 Training R2: nan
Epoch: 4237 Training R2: nan
Epoch: 4238 Training R2: nan
Epoch: 4239 Training R2: nan
Epoch: 4240 Training R2: nan
Epoch: 4241 Training R2: nan
Epoch: 4242 Training R2: nan
Epoch: 4243 Training R2: nan
Epoch: 4244 Training R2: nan
Epoch: 4245 Training R2: nan
Epoch: 4246 Training R2: nan
Epoch: 4247 Training R2: nan
Epoch: 4248 Training R2: nan
Epoch: 4249 Training R2: nan
Epoch: 4250 Training R2: nan
Epoch: 4251 Training R2: nan
Epoch: 4252 Training R2: nan
Epoch: 4253 Training R2: nan
Epoch: 4254 Training R2: nan
Epoch: 4255 Training R2: nan
Epoch: 4256 Training R2: nan
Epoch: 4257 Training R2: nan
Epoch: 4258 Training R2: nan
Epoch: 4259 Training R2: nan
Epoch: 4260 Training R2: nan
Epoch: 4261 Training R2: nan
Epoch: 4262 Training R2: nan
Epoch: 4263 Training R2: nan
Epoch: 4264 Training R2: nan
Epoch: 4265 Training R2: nan
Epoch: 4266 Training R2: nan
Epoch: 4267 Training R2: nan
Epoch: 4268 Training R2: nan
Epoch: 4269 Training R2: nan
Epoch: 4270 Training R2: nan
Epoch: 4271 Training R2: nan
Epoch: 4272 Training R2: nan
Epoch: 4273 Training R2: nan
Epoch: 4274 Training R2: nan
Epoch: 4275 Training R2: nan
Epoch: 4276 Training R2: nan
Epoch: 4277 Training R2: nan
Epoch: 4278 Training R2: nan
Epoch: 4279 Training R2: nan
Epoch: 4280 Training R2: nan
Epoch: 4281 Training R2: nan
Epoch: 4282 Training R2: nan
Epoch: 4283 Training R2: nan
Epoch: 4284 Training R2: nan
Epoch: 4285 Training R2: nan
Epoch: 4286 Training R2: nan
Epoch: 4287 Training R2: nan
Epoch: 4288 Training R2: nan
Epoch: 4289 Training R2: nan
Epoch: 4290 Training R2: nan
Epoch: 4291 Training R2: nan
Epoch: 4292 Training R2: nan
Epoch: 4293 Training R2: nan
Epoch: 4294 Training R2: nan
Epoch: 4295 Training R2: nan
Epoch: 4296 Training R2: nan
Epoch: 4297 Training R2: nan
Epoch: 4298 Training R2: nan
Epoch: 4299 Training R2: nan
Epoch: 4300 Training R2: nan
Epoch: 4301 Training R2: nan
Epoch: 4302 Training R2: nan
Epoch: 4303 Training R2: nan
Epoch: 4304 Training R2: nan
Epoch: 4305 Training R2: nan
Epoch: 4306 Training R2: nan
Epoch: 4307 Training R2: nan
Epoch: 4308 Training R2: nan
Epoch: 4309 Training R2: nan
Epoch: 4310 Training R2: nan
Epoch: 4311 Training R2: nan
Epoch: 4312 Training R2: nan
Epoch: 4313 Training R2: nan
Epoch: 4314 Training R2: nan
Epoch: 4315 Training R2: nan

In [106]:
r2vals

[0.40857862401138223, 0.6713439246278441, 0.9116817082993264, nan]

In [107]:
epochs = 10000
r2vals = []
alphas = [0.001,0.01,0.1,1]
params = []
for alpha in alphas:
    betas = np.zeros(x_tr.shape[1]+1)
    x_tr1 = np.c_[np.ones(x_tr.shape[0]),x_tr]    
    n = len(x_tr1)
    for i in range(0,epochs):

        ##training
        predictions = np.matmul(x_tr1,betas)
        errors = predictions - y_tr
        gradient = 1/n*np.matmul(x_tr1.transpose(),errors)
        betas = betas - alpha*gradient
        r2t = 1 - (np.sum((predictions-y_tr)**2))/((np.sum((y_tr-np.mean(y_tr))**2)))
        print("Epoch: " + str(i) + " Training R2: "+str(r2t))

    ##validation
    x_v1 = np.c_[np.ones(x_v.shape[0]),x_v]    
    val_predictions = np.matmul(x_v1,betas)
    r2v = 1 - (np.sum((val_predictions-y_v)**2))/((np.sum((y_v-np.mean(y_v))**2)))
    print("Validation R2: "+str(r2v))
    r2vals.append(r2v)
    params.append(betas)

Epoch: 0 Training R2: -12.339549070262802
Epoch: 1 Training R2: -12.281577767527851
Epoch: 2 Training R2: -12.223871003208032
Epoch: 3 Training R2: -12.166427569898868
Epoch: 4 Training R2: -12.109246265706718
Epoch: 5 Training R2: -12.052325894223628
Epoch: 6 Training R2: -11.995665264502296
Epoch: 7 Training R2: -11.939263191031147
Epoch: 8 Training R2: -11.88311849370952
Epoch: 9 Training R2: -11.82722999782297
Epoch: 10 Training R2: -11.771596534018697
Epoch: 11 Training R2: -11.716216938281056
Epoch: 12 Training R2: -11.661090051907214
Epoch: 13 Training R2: -11.606214721482887
Epoch: 14 Training R2: -11.551589798858213
Epoch: 15 Training R2: -11.497214141123717
Epoch: 16 Training R2: -11.443086610586398
Epoch: 17 Training R2: -11.389206074745916
Epoch: 18 Training R2: -11.335571406270892
Epoch: 19 Training R2: -11.282181482975318
Epoch: 20 Training R2: -11.229035187795073
Epoch: 21 Training R2: -11.176131408764542
Epoch: 22 Training R2: -11.123469038993347
Epoch: 23 Training R2: -11.071046976643183
Epoch: 24 Training R2: -11.018864124904763
Epoch: 25 Training R2: -10.966919391974857
Epoch: 26 Training R2: -10.915211691033447
Epoch: 27 Training R2: -10.863739940220984
Epoch: 28 Training R2: -10.812503062615747
Epoch: 29 Training R2: -10.761499986211305
Epoch: 30 Training R2: -10.710729643894078
Epoch: 31 Training R2: -10.660190973421017
Epoch: 32 Training R2: -10.609882917397359
Epoch: 33 Training R2: -10.559804423254514
Epoch: 34 Training R2: -10.509954443228022
Epoch: 35 Training R2: -10.460331934335633
Epoch: 36 Training R2: -10.410935858355488
Epoch: 37 Training R2: -10.36176518180438
Epoch: 38 Training R2: -10.312818875916125
Epoch: 39 Training R2: -10.264095916620045
Epoch: 40 Training R2: -10.21559528451952
Epoch: 41 Training R2: -10.167315964870674
Epoch: 42 Training R2: -10.11925694756112
Epoch: 43 Training R2: -10.071417227088833
Epoch: 44 Training R2: -10.023795802541107
Epoch: 45 Training R2: -9.976391677573597
Epoch: 46 Training R2: -9.929203860389487
Epoch: 47 Training R2: -9.882231363718713
Epoch: 48 Training R2: -9.835473204797317
Epoch: 49 Training R2: -9.788928405346882
Epoch: 50 Training R2: -9.742595991554044
Epoch: 51 Training R2: -9.69647499405012
Epoch: 52 Training R2: -9.650564447890833
Epoch: 53 Training R2: -9.6048633925361
Epoch: 54 Training R2: -9.559370871829941
Epoch: 55 Training R2: -9.514085933980464
Epoch: 56 Training R2: -9.469007631539954
Epoch: 57 Training R2: -9.424135021385036
Epoch: 58 Training R2: -9.379467164696944
Epoch: 59 Training R2: -9.335003126941869
Epoch: 60 Training R2: -9.290741977851408
Epoch: 61 Training R2: -9.246682791403092
Epoch: 62 Training R2: -9.202824645801005
Epoch: 63 Training R2: -9.159166623456494
Epoch: 64 Training R2: -9.11570781096897
Epoch: 65 Training R2: -9.072447299106793
Epoch: 66 Training R2: -9.029384182788233
Epoch: 67 Training R2: -8.986517561062545
Epoch: 68 Training R2: -8.943846537091105
Epoch: 69 Training R2: -8.901370218128635
Epoch: 70 Training R2: -8.859087715504542
Epoch: 71 Training R2: -8.816998144604293
Epoch: 72 Training R2: -8.775100624850923
Epoch: 73 Training R2: -8.7333942796866
Epoch: 74 Training R2: -8.69187823655428
Epoch: 75 Training R2: -8.650551626879437
Epoch: 76 Training R2: -8.609413586051916
Epoch: 77 Training R2: -8.568463253407797
Epoch: 78 Training R2: -8.52769977221142
Epoch: 79 Training R2: -8.487122289637433
Epoch: 80 Training R2: -8.44672995675296
Epoch: 81 Training R2: -8.406521928499817
Epoch: 82 Training R2: -8.366497363676848
Epoch: 83 Training R2: -8.326655424922302
Epoch: 84 Training R2: -8.286995278696324
Epoch: 85 Training R2: -8.2475160952635
Epoch: 86 Training R2: -8.208217048675495
Epoch: 87 Training R2: -8.169097316753781
Epoch: 88 Training R2: -8.130156081072405
Epoch: 89 Training R2: -8.091392526940894
Epoch: 90 Training R2: -8.052805843387167
Epoch: 91 Training R2: -8.014395223140607
Epoch: 92 Training R2: -7.976159862615125
Epoch: 93 Training R2: -7.938098961892376
Epoch: 94 Training R2: -7.9002117247050005
Epoch: 95 Training R2: -7.862497358419958
Epoch: 96 Training R2: -7.824955074021961
Epoch: 97 Training R2: -7.787584086096935
Epoch: 98 Training R2: -7.750383612815604
Epoch: 99 Training R2: -7.7133528759171135
Epoch: 100 Training R2: -7.676491100692754
Epoch: 101 Training R2: -7.639797515969745
Epoch: 102 Training R2: -7.603271354095089
Epoch: 103 Training R2: -7.566911850919521
Epoch: 104 Training R2: -7.530718245781502
Epoch: 105 Training R2: -7.49468978149131
Epoch: 106 Training R2: -7.4588257043151955
Epoch: 107 Training R2: -7.423125263959593
Epoch: 108 Training R2: -7.387587713555437
Epoch: 109 Training R2: -7.352212309642525
Epoch: 110 Training R2: -7.316998312153949
Epoch: 111 Training R2: -7.28194498440063
Epoch: 112 Training R2: -7.247051593055877
Epoch: 113 Training R2: -7.212317408140059
Epoch: 114 Training R2: -7.177741703005314
Epoch: 115 Training R2: -7.143323754320349
Epoch: 116 Training R2: -7.109062842055311
Epoch: 117 Training R2: -7.0749582494667
Epoch: 118 Training R2: -7.04100926308238
Epoch: 119 Training R2: -7.0072151726866565
Epoch: 120 Training R2: -6.973575271305388
Epoch: 121 Training R2: -6.940088855191221
Epoch: 122 Training R2: -6.906755223808841
Epoch: 123 Training R2: -6.873573679820323
Epoch: 124 Training R2: -6.840543529070531
Epoch: 125 Training R2: -6.80766408057259
Epoch: 126 Training R2: -6.774934646493444
Epoch: 127 Training R2: -6.742354542139429
Epoch: 128 Training R2: -6.709923085941979
Epoch: 129 Training R2: -6.677639599443331
Epoch: 130 Training R2: -6.64550340728235
Epoch: 131 Training R2: -6.613513837180384
Epoch: 132 Training R2: -6.581670219927198
Epoch: 133 Training R2: -6.549971889366969
Epoch: 134 Training R2: -6.51841818238434
Epoch: 135 Training R2: -6.487008438890558
Epoch: 136 Training R2: -6.455742001809637
Epoch: 137 Training R2: -6.424618217064627
Epoch: 138 Training R2: -6.393636433563918
Epoch: 139 Training R2: -6.36279600318761
Epoch: 140 Training R2: -6.332096280773959
Epoch: 141 Training R2: -6.301536624105866
Epoch: 142 Training R2: -6.2711163938974455
Epoch: 143 Training R2: -6.240834953780642
Epoch: 144 Training R2: -6.210691670291907
Epoch: 145 Training R2: -6.18068591285896
Epoch: 146 Training R2: -6.150817053787571
Epoch: 147 Training R2: -6.121084468248435
Epoch: 148 Training R2: -6.091487534264103
Epoch: 149 Training R2: -6.0620256326959465
Epoch: 150 Training R2: -6.032698147231221
Epoch: 151 Training R2: -6.003504464370151
Epoch: 152 Training R2: -5.974443973413105
Epoch: 153 Training R2: -5.945516066447807
Epoch: 154 Training R2: -5.916720138336611
Epoch: 155 Training R2: -5.88805558670385
Epoch: 156 Training R2: -5.859521811923219
Epoch: 157 Training R2: -5.831118217105229
Epoch: 158 Training R2: -5.802844208084713
Epoch: 159 Training R2: -5.7746991934084
Epoch: 160 Training R2: -5.74668258432253
Epoch: 161 Training R2: -5.7187937947605345
Epoch: 162 Training R2: -5.69103224133077
Epoch: 163 Training R2: -5.663397343304316
Epoch: 164 Training R2: -5.635888522602811
Epoch: 165 Training R2: -5.608505203786366
Epoch: 166 Training R2: -5.581246814041513
Epoch: 167 Training R2: -5.554112783169222
Epoch: 168 Training R2: -5.527102543572967
Epoch: 169 Training R2: -5.50021553024685
Epoch: 170 Training R2: -5.473451180763775
Epoch: 171 Training R2: -5.446808935263672
Epoch: 172 Training R2: -5.420288236441792
Epoch: 173 Training R2: -5.393888529537038
Epoch: 174 Training R2: -5.36760926232035
Epoch: 175 Training R2: -5.34144988508316
Epoch: 176 Training R2: -5.31540985062588
Epoch: 177 Training R2: -5.289488614246448
Epoch: 178 Training R2: -5.263685633728938
Epoch: 179 Training R2: -5.238000369332206
Epoch: 180 Training R2: -5.212432283778596
Epoch: 181 Training R2: -5.186980842242696
Epoch: 182 Training R2: -5.161645512340146
Epoch: 183 Training R2: -5.136425764116498
Epoch: 184 Training R2: -5.111321070036124
Epoch: 185 Training R2: -5.08633090497117
Epoch: 186 Training R2: -5.061454746190581
Epoch: 187 Training R2: -5.0366920733491485
Epoch: 188 Training R2: -5.012042368476623
Epoch: 189 Training R2: -4.987505115966879
Epoch: 190 Training R2: -4.963079802567125
Epoch: 191 Training R2: -4.938765917367153
Epoch: 192 Training R2: -4.9145629517886595
Epoch: 193 Training R2: -4.890470399574591
Epoch: 194 Training R2: -4.866487756778556
Epoch: 195 Training R2: -4.842614521754276
Epoch: 196 Training R2: -4.8188501951450915
Epoch: 197 Training R2: -4.795194279873503
Epoch: 198 Training R2: -4.771646281130779
Epoch: 199 Training R2: -4.748205706366589
Epoch: 200 Training R2: -4.724872065278709
Epoch: 201 Training R2: -4.70164486980275
Epoch: 202 Training R2: -4.678523634101949
Epoch: 203 Training R2: -4.655507874557002
Epoch: 204 Training R2: -4.632597109755938
Epoch: 205 Training R2: -4.609790860484055
Epoch: 206 Training R2: -4.587088649713876
Epoch: 207 Training R2: -4.564490002595181
Epoch: 208 Training R2: -4.5419944464450595
Epoch: 209 Training R2: -4.519601510738022
Epoch: 210 Training R2: -4.497310727096154
Epoch: 211 Training R2: -4.475121629279312
Epoch: 212 Training R2: -4.453033753175369
Epoch: 213 Training R2: -4.431046636790497
Epoch: 214 Training R2: -4.4091598202395055
Epoch: 215 Training R2: -4.38737284573621
Epoch: 216 Training R2: -4.3656852575838565
Epoch: 217 Training R2: -4.3440966021655845
Epoch: 218 Training R2: -4.322606427934933
Epoch: 219 Training R2: -4.301214285406389
Epoch: 220 Training R2: -4.279919727145982
Epoch: 221 Training R2: -4.258722307761925
Epoch: 222 Training R2: -4.237621583895287
Epoch: 223 Training R2: -4.216617114210717
Epoch: 224 Training R2: -4.195708459387208
Epoch: 225 Training R2: -4.174895182108906
Epoch: 226 Training R2: -4.154176847055952
Epoch: 227 Training R2: -4.133553020895378
Epoch: 228 Training R2: -4.113023272272033
Epoch: 229 Training R2: -4.092587171799559
Epoch: 230 Training R2: -4.07224429205141
Epoch: 231 Training R2: -4.0519942075518935
Epoch: 232 Training R2: -4.031836494767279
Epoch: 233 Training R2: -4.011770732096927
Epoch: 234 Training R2: -3.991796499864475
Epoch: 235 Training R2: -3.971913380309042
Epoch: 236 Training R2: -3.9521209575764953
Epoch: 237 Training R2: -3.9324188177107464
Epoch: 238 Training R2: -3.912806548645083
Epoch: 239 Training R2: -3.893283740193552
Epoch: 240 Training R2: -3.87384998404237
Epoch: 241 Training R2: -3.8545048737413845
Epoch: 242 Training R2: -3.8352480046955586
Epoch: 243 Training R2: -3.816078974156513
Epoch: 244 Training R2: -3.7969973812140916
Epoch: 245 Training R2: -3.7780028267879784
Epoch: 246 Training R2: -3.7590949136193332
Epoch: 247 Training R2: -3.7402732462624932
Epoch: 248 Training R2: -3.721537431076685
Epoch: 249 Training R2: -3.702887076217797
Epoch: 250 Training R2: -3.6843217916301647
Epoch: 251 Training R2: -3.665841189038426
Epoch: 252 Training R2: -3.647444881939383
Epoch: 253 Training R2: -3.6291324855939155
Epoch: 254 Training R2: -3.6109036170189315
Epoch: 255 Training R2: -3.5927578949793535
Epoch: 256 Training R2: -3.5746949399801355
Epoch: 257 Training R2: -3.556714374258326
Epoch: 258 Training R2: -3.5388158217751577
Epoch: 259 Training R2: -3.5209989082081847
Epoch: 260 Training R2: -3.5032632609434424
Epoch: 261 Training R2: -3.4856085090676503
Epoch: 262 Training R2: -3.4680342833604554
Epoch: 263 Training R2: -3.450540216286697
Epoch: 264 Training R2: -3.433125941988725
Epoch: 265 Training R2: -3.4157910962787295
Epoch: 266 Training R2: -3.3985353166311363
Epoch: 267 Training R2: -3.381358242175007
Epoch: 268 Training R2: -3.364259513686493
Epoch: 269 Training R2: -3.3472387735813154
Epoch: 270 Training R2: -3.3302956659072818
Epoch: 271 Training R2: -3.313429836336839
Epoch: 272 Training R2: -3.296640932159658
Epoch: 273 Training R2: -3.2799286022752483
Epoch: 274 Training R2: -3.263292497185616
Epoch: 275 Training R2: -3.2467322689879454
Epoch: 276 Training R2: -3.23024757136732
Epoch: 277 Training R2: -3.2138380595894755
Epoch: 278 Training R2: -3.1975033904935843
Epoch: 279 Training R2: -3.181243222485074
Epoch: 280 Training R2: -3.165057215528482
Epoch: 281 Training R2: -3.1489450311403324
Epoch: 282 Training R2: -3.132906332382059
Epoch: 283 Training R2: -3.11694078385295
Epoch: 284 Training R2: -3.101048051683134
Epoch: 285 Training R2: -3.0852278035265854
Epoch: 286 Training R2: -3.0694797085541747
Epoch: 287 Training R2: -3.053803437446745
Epoch: 288 Training R2: -3.0381986623882176
Epoch: 289 Training R2: -3.022665057058733
Epoch: 290 Training R2: -3.0072022966278213
Epoch: 291 Training R2: -2.991810057747607
Epoch: 292 Training R2: -2.9764880185460374
Epoch: 293 Training R2: -2.96123585862015
Epoch: 294 Training R2: -2.946053259029367
Epoch: 295 Training R2: -2.930939902288817
Epoch: 296 Training R2: -2.9158954723627
Epoch: 297 Training R2: -2.900919654657664
Epoch: 298 Training R2: -2.886012136016222
Epoch: 299 Training R2: -2.871172604710206
Epoch: 300 Training R2: -2.8564007504342377
Epoch: 301 Training R2: -2.8416962642992334
Epoch: 302 Training R2: -2.827058838825944
Epoch: 303 Training R2: -2.8124881679385165
Epoch: 304 Training R2: -2.7979839469580914
Epoch: 305 Training R2: -2.783545872596425
Epoch: 306 Training R2: -2.7691736429495433
Epoch: 307 Training R2: -2.7548669574914193
Epoch: 308 Training R2: -2.740625517067693
Epoch: 309 Training R2: -2.7264490238894044
Epoch: 310 Training R2: -2.7123371815267605
Epoch: 311 Training R2: -2.698289694902935
Epoch: 312 Training R2: -2.6843062702878933
Epoch: 313 Training R2: -2.670386615292244
Epoch: 314 Training R2: -2.6565304388611173
Epoch: 315 Training R2: -2.642737451268081
Epoch: 316 Training R2: -2.629007364109072
Epoch: 317 Training R2: -2.615339890296358
Epoch: 318 Training R2: -2.6017347440525387
Epoch: 319 Training R2: -2.588191640904557
Epoch: 320 Training R2: -2.574710297677749
Epoch: 321 Training R2: -2.5612904324899173
Epoch: 322 Training R2: -2.5479317647454316
Epoch: 323 Training R2: -2.534634015129358
Epoch: 324 Training R2: -2.521396905601612
Epoch: 325 Training R2: -2.5082201593911404
Epoch: 326 Training R2: -2.49510350099013
Epoch: 327 Training R2: -2.482046656148239
Epoch: 328 Training R2: -2.4690493518668624
Epoch: 329 Training R2: -2.456111316393415
Epoch: 330 Training R2: -2.443232279215644
Epoch: 331 Training R2: -2.4304119710559724
Epoch: 332 Training R2: -2.417650123865858
Epoch: 333 Training R2: -2.404946470820188
Epoch: 334 Training R2: -2.3923007463116943
Epoch: 335 Training R2: -2.379712685945391
Epoch: 336 Training R2: -2.3671820265330483
Epoch: 337 Training R2: -2.354708506087678
Epoch: 338 Training R2: -2.3422918638180534
Epoch: 339 Training R2: -2.329931840123255
Epoch: 340 Training R2: -2.3176281765872337
Epoch: 341 Training R2: -2.3053806159734
Epoch: 342 Training R2: -2.293188902219248
Epoch: 343 Training R2: -2.2810527804309917
Epoch: 344 Training R2: -2.268971996878232
Epoch: 345 Training R2: -2.2569462989886477
Epoch: 346 Training R2: -2.2449754353427065
Epoch: 347 Training R2: -2.2330591556684096
Epoch: 348 Training R2: -2.2211972108360465
Epoch: 349 Training R2: -2.209389352852987
Epoch: 350 Training R2: -2.1976353348584903
Epoch: 351 Training R2: -2.1859349111185358
Epoch: 352 Training R2: -2.1742878370206853
Epoch: 353 Training R2: -2.162693869068959
Epoch: 354 Training R2: -2.151152764878743
Epoch: 355 Training R2: -2.139664283171717
Epoch: 356 Training R2: -2.128228183770802
Epoch: 357 Training R2: -2.116844227595138
Epoch: 358 Training R2: -2.1055121766550764
Epoch: 359 Training R2: -2.0942317940472024
Epoch: 360 Training R2: -2.0830028439493766
Epoch: 361 Training R2: -2.071825091615799
Epoch: 362 Training R2: -2.060698303372098
Epoch: 363 Training R2: -2.0496222466104377
Epoch: 364 Training R2: -2.0385966897846535
Epoch: 365 Training R2: -2.0276214024054027
Epoch: 366 Training R2: -2.016696155035343
Epoch: 367 Training R2: -2.0058207192843307
Epoch: 368 Training R2: -1.9949948678046412
Epoch: 369 Training R2: -1.9842183742862116
Epoch: 370 Training R2: -1.9734910134519024
Epoch: 371 Training R2: -1.9628125610527856
Epoch: 372 Training R2: -1.9521827938634506
Epoch: 373 Training R2: -1.9416014896773328
Epoch: 374 Training R2: -1.9310684273020637
Epoch: 375 Training R2: -1.9205833865548403
Epoch: 376 Training R2: -1.91014614825782
Epoch: 377 Training R2: -1.8997564942335305
Epoch: 378 Training R2: -1.8894142073003075
Epoch: 379 Training R2: -1.879119071267748
Epoch: 380 Training R2: -1.868870870932183
Epoch: 381 Training R2: -1.8586693920721804
Epoch: 382 Training R2: -1.8485144214440545
Epoch: 383 Training R2: -1.83840574677741
Epoch: 384 Training R2: -1.828343156770694
Epoch: 385 Training R2: -1.818326441086778
Epoch: 386 Training R2: -1.8083553903485559
Epoch: 387 Training R2: -1.7984297961345588
Epoch: 388 Training R2: -1.7885494509745965
Epoch: 389 Training R2: -1.7787141483454163
Epoch: 390 Training R2: -1.7689236826663768
Epoch: 391 Training R2: -1.7591778492951495
Epoch: 392 Training R2: -1.749476444523435
Epoch: 393 Training R2: -1.7398192655727
Epoch: 394 Training R2: -1.7302061105899331
Epoch: 395 Training R2: -1.7206367786434216
Epoch: 396 Training R2: -1.7111110697185437
Epoch: 397 Training R2: -1.7016287847135878
Epoch: 398 Training R2: -1.6921897254355796
Epoch: 399 Training R2: -1.6827936945961413
Epoch: 400 Training R2: -1.6734404958073559
Epoch: 401 Training R2: -1.6641299335776614
Epoch: 402 Training R2: -1.654861813307761
Epoch: 403 Training R2: -1.645635941286546
Epoch: 404 Training R2: -1.6364521246870454
Epoch: 405 Training R2: -1.6273101715623888
Epoch: 406 Training R2: -1.6182098908417912
Epoch: 407 Training R2: -1.6091510923265528
Epoch: 408 Training R2: -1.6001335866860793
Epoch: 409 Training R2: -1.5911571854539184
Epoch: 410 Training R2: -1.582221701023819
Epoch: 411 Training R2: -1.5733269466458006
Epoch: 412 Training R2: -1.5644727364222497
Epoch: 413 Training R2: -1.555658885304025
Epoch: 414 Training R2: -1.546885209086588
Epoch: 415 Training R2: -1.5381515244061466
Epoch: 416 Training R2: -1.5294576487358187
Epoch: 417 Training R2: -1.5208034003818112
Epoch: 418 Training R2: -1.5121885984796184
Epoch: 419 Training R2: -1.5036130629902367
Epoch: 420 Training R2: -1.4950766146963974
Epoch: 421 Training R2: -1.4865790751988146
Epoch: 422 Training R2: -1.4781202669124536
Epoch: 423 Training R2: -1.469700013062814
Epoch: 424 Training R2: -1.4613181376822295
Epoch: 425 Training R2: -1.4529744656061858
Epoch: 426 Training R2: -1.4446688224696547
Epoch: 427 Training R2: -1.436401034703446
Epoch: 428 Training R2: -1.4281709295305731
Epoch: 429 Training R2: -1.4199783349626398
Epoch: 430 Training R2: -1.4118230797962399
Epoch: 431 Training R2: -1.4037049936093715
Epoch: 432 Training R2: -1.3956239067578764
Epoch: 433 Training R2: -1.387579650371885
Epoch: 434 Training R2: -1.3795720563522842
Epoch: 435 Training R2: -1.3716009573671992
Epoch: 436 Training R2: -1.363666186848492
Epoch: 437 Training R2: -1.355767578988274
Epoch: 438 Training R2: -1.34790496873544
Epoch: 439 Training R2: -1.3400781917922084
Epoch: 440 Training R2: -1.3322870846106878
Epoch: 441 Training R2: -1.3245314843894507
Epoch: 442 Training R2: -1.3168112290701308
Epoch: 443 Training R2: -1.3091261573340263
Epoch: 444 Training R2: -1.3014761085987288
Epoch: 445 Training R2: -1.2938609230147589
Epoch: 446 Training R2: -1.2862804414622224
Epoch: 447 Training R2: -1.2787345055474808
Epoch: 448 Training R2: -1.2712229575998384
Epoch: 449 Training R2: -1.263745640668236
Epoch: 450 Training R2: -1.2563023985179744
Epoch: 451 Training R2: -1.2488930756274401
Epoch: 452 Training R2: -1.2415175171848496
Epoch: 453 Training R2: -1.234175569085016
Epoch: 454 Training R2: -1.2268670779261148
Epoch: 455 Training R2: -1.2195918910064818
Epoch: 456 Training R2: -1.2123498563214126
Epoch: 457 Training R2: -1.2051408225599838
Epoch: 458 Training R2: -1.1979646391018846
Epoch: 459 Training R2: -1.1908211560142652
Epoch: 460 Training R2: -1.1837102240486028
Epoch: 461 Training R2: -1.1766316946375706
Epoch: 462 Training R2: -1.1695854198919364
Epoch: 463 Training R2: -1.1625712525974627

c:\Users\Gaurish Garg\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\core\fromnumeric.py:88: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\Gaurish Garg\AppData\Local\Temp\ipykernel_21288\3078470972.py:16: RuntimeWarning: overflow encountered in square
  r2t = 1 - (np.sum((predictions-y_tr)**2))/((np.sum((y_tr-np.mean(y_tr))**2)))

Epoch: 2364 Training R2: -inf
Epoch: 2365 Training R2: -inf
Epoch: 2366 Training R2: -inf
Epoch: 2367 Training R2: -inf
Epoch: 2368 Training R2: -inf
Epoch: 2369 Training R2: -inf
Epoch: 2370 Training R2: -inf
Epoch: 2371 Training R2: -inf
Epoch: 2372 Training R2: -inf
Epoch: 2373 Training R2: -inf
Epoch: 2374 Training R2: -inf
Epoch: 2375 Training R2: -inf
Epoch: 2376 Training R2: -inf
Epoch: 2377 Training R2: -inf
Epoch: 2378 Training R2: -inf
Epoch: 2379 Training R2: -inf
Epoch: 2380 Training R2: -inf
Epoch: 2381 Training R2: -inf
Epoch: 2382 Training R2: -inf
Epoch: 2383 Training R2: -inf
Epoch: 2384 Training R2: -inf
Epoch: 2385 Training R2: -inf
Epoch: 2386 Training R2: -inf
Epoch: 2387 Training R2: -inf
Epoch: 2388 Training R2: -inf
Epoch: 2389 Training R2: -inf
Epoch: 2390 Training R2: -inf
Epoch: 2391 Training R2: -inf
Epoch: 2392 Training R2: -inf
Epoch: 2393 Training R2: -inf
Epoch: 2394 Training R2: -inf
Epoch: 2395 Training R2: -inf
Epoch: 2396 Training R2: -inf
Epoch: 2397 Training R2: -inf
Epoch: 2398 Training R2: -inf
Epoch: 2399 Training R2: -inf
Epoch: 2400 Training R2: -inf
Epoch: 2401 Training R2: -inf
Epoch: 2402 Training R2: -inf
Epoch: 2403 Training R2: -inf
Epoch: 2404 Training R2: -inf
Epoch: 2405 Training R2: -inf
Epoch: 2406 Training R2: -inf
Epoch: 2407 Training R2: -inf
Epoch: 2408 Training R2: -inf
Epoch: 2409 Training R2: -inf
Epoch: 2410 Training R2: -inf
Epoch: 2411 Training R2: -inf
Epoch: 2412 Training R2: -inf
Epoch: 2413 Training R2: -inf
Epoch: 2414 Training R2: -inf
Epoch: 2415 Training R2: -inf
Epoch: 2416 Training R2: -inf
Epoch: 2417 Training R2: -inf
Epoch: 2418 Training R2: -inf
Epoch: 2419 Training R2: -inf
Epoch: 2420 Training R2: -inf
Epoch: 2421 Training R2: -inf
Epoch: 2422 Training R2: -inf
Epoch: 2423 Training R2: -inf
Epoch: 2424 Training R2: -inf
Epoch: 2425 Training R2: -inf
Epoch: 2426 Training R2: -inf
Epoch: 2427 Training R2: -inf
Epoch: 2428 Training R2: -inf
Epoch: 2429 Training R2: -inf
Epoch: 2430 Training R2: -inf
Epoch: 2431 Training R2: -inf
Epoch: 2432 Training R2: -inf
Epoch: 2433 Training R2: -inf
Epoch: 2434 Training R2: -inf
Epoch: 2435 Training R2: -inf
Epoch: 2436 Training R2: -inf
Epoch: 2437 Training R2: -inf
Epoch: 2438 Training R2: -inf
Epoch: 2439 Training R2: -inf
Epoch: 2440 Training R2: -inf
Epoch: 2441 Training R2: -inf
Epoch: 2442 Training R2: -inf
Epoch: 2443 Training R2: -inf
Epoch: 2444 Training R2: -inf
Epoch: 2445 Training R2: -inf
Epoch: 2446 Training R2: -inf
Epoch: 2447 Training R2: -inf
Epoch: 2448 Training R2: -inf
Epoch: 2449 Training R2: -inf
Epoch: 2450 Training R2: -inf
Epoch: 2451 Training R2: -inf
Epoch: 2452 Training R2: -inf
Epoch: 2453 Training R2: -inf
Epoch: 2454 Training R2: -inf
Epoch: 2455 Training R2: -inf
Epoch: 2456 Training R2: -inf
Epoch: 2457 Training R2: -inf
Epoch: 2458 Training R2: -inf
Epoch: 2459 Training R2: -inf
Epoch: 2460 Training R2: -inf
Epoch: 2461 Training R2: -inf
Epoch: 2462 Training R2: -inf
Epoch: 2463 Training R2: -inf
Epoch: 2464 Training R2: -inf
Epoch: 2465 Training R2: -inf
Epoch: 2466 Training R2: -inf
Epoch: 2467 Training R2: -inf
Epoch: 2468 Training R2: -inf
Epoch: 2469 Training R2: -inf
Epoch: 2470 Training R2: -inf
Epoch: 2471 Training R2: -inf
Epoch: 2472 Training R2: -inf
Epoch: 2473 Training R2: -inf
Epoch: 2474 Training R2: -inf
Epoch: 2475 Training R2: -inf
Epoch: 2476 Training R2: -inf
Epoch: 2477 Training R2: -inf
Epoch: 2478 Training R2: -inf
Epoch: 2479 Training R2: -inf
Epoch: 2480 Training R2: -inf
Epoch: 2481 Training R2: -inf
Epoch: 2482 Training R2: -inf
Epoch: 2483 Training R2: -inf
Epoch: 2484 Training R2: -inf
Epoch: 2485 Training R2: -inf
Epoch: 2486 Training R2: -inf
Epoch: 2487 Training R2: -inf
Epoch: 2488 Training R2: -inf
Epoch: 2489 Training R2: -inf
Epoch: 2490 Training R2: -inf
Epoch: 2491 Training R2: -inf
Epoch: 2492 Training R2: -inf
Epoch: 2493 Training R2: -inf
Epoch: 2494 Training R2: -inf
Epoch: 2495 Training R2: -inf
Epoch: 2496 Training R2: -inf
Epoch: 2497 Training R2: -inf
Epoch: 2498 Training R2: -inf
Epoch: 2499 Training R2: -inf
Epoch: 2500 Training R2: -inf
Epoch: 2501 Training R2: -inf
Epoch: 2502 Training R2: -inf
Epoch: 2503 Training R2: -inf
Epoch: 2504 Training R2: -inf
Epoch: 2505 Training R2: -inf
Epoch: 2506 Training R2: -inf
Epoch: 2507 Training R2: -inf
Epoch: 2508 Training R2: -inf
Epoch: 2509 Training R2: -inf
Epoch: 2510 Training R2: -inf
Epoch: 2511 Training R2: -inf
Epoch: 2512 Training R2: -inf
Epoch: 2513 Training R2: -inf
Epoch: 2514 Training R2: -inf
Epoch: 2515 Training R2: -inf
Epoch: 2516 Training R2: -inf
Epoch: 2517 Training R2: -inf
Epoch: 2518 Training R2: -inf
Epoch: 2519 Training R2: -inf
Epoch: 2520 Training R2: -inf
Epoch: 2521 Training R2: -inf
Epoch: 2522 Training R2: -inf
Epoch: 2523 Training R2: -inf
Epoch: 2524 Training R2: -inf
Epoch: 2525 Training R2: -inf
Epoch: 2526 Training R2: -inf
Epoch: 2527 Training R2: -inf
Epoch: 2528 Training R2: -inf
Epoch: 2529 Training R2: -inf
Epoch: 2530 Training R2: -inf
Epoch: 2531 Training R2: -inf
Epoch: 2532 Training R2: -inf
Epoch: 2533 Training R2: -inf
Epoch: 2534 Training R2: -inf
Epoch: 2535 Training R2: -inf
Epoch: 2536 Training R2: -inf
Epoch: 2537 Training R2: -inf
Epoch: 2538 Training R2: -inf
Epoch: 2539 Training R2: -inf
Epoch: 2540 Training R2: -inf
Epoch: 2541 Training R2: -inf
Epoch: 2542 Training R2: -inf
Epoch: 2543 Training R2: -inf
Epoch: 2544 Training R2: -inf
Epoch: 2545 Training R2: -inf
Epoch: 2546 Training R2: -inf
Epoch: 2547 Training R2: -inf
Epoch: 2548 Training R2: -inf
Epoch: 2549 Training R2: -inf
Epoch: 2550 Training R2: -inf
Epoch: 2551 Training R2: -inf
Epoch: 2552 Training R2: -inf
Epoch: 2553 Training R2: -inf
Epoch: 2554 Training R2: -inf
Epoch: 2555 Training R2: -inf
Epoch: 2556 Training R2: -inf
Epoch: 2557 Training R2: -inf
Epoch: 2558 Training R2: -inf
Epoch: 2559 Training R2: -inf
Epoch: 2560 Training R2: -inf
Epoch: 2561 Training R2: -inf
Epoch: 2562 Training R2: -inf
Epoch: 2563 Training R2: -inf
Epoch: 2564 Training R2: -inf
Epoch: 2565 Training R2: -inf
Epoch: 2566 Training R2: -inf
Epoch: 2567 Training R2: -inf
Epoch: 2568 Training R2: -inf
Epoch: 2569 Training R2: -inf
Epoch: 2570 Training R2: -inf
Epoch: 2571 Training R2: -inf
Epoch: 2572 Training R2: -inf
Epoch: 2573 Training R2: -inf
Epoch: 2574 Training R2: -inf
Epoch: 2575 Training R2: -inf
Epoch: 2576 Training R2: -inf
Epoch: 2577 Training R2: -inf
Epoch: 2578 Training R2: -inf
Epoch: 2579 Training R2: -inf
Epoch: 2580 Training R2: -inf
Epoch: 2581 Training R2: -inf
Epoch: 2582 Training R2: -inf
Epoch: 2583 Training R2: -inf
Epoch: 2584 Training R2: -inf
Epoch: 2585 Training R2: -inf
Epoch: 2586 Training R2: -inf
Epoch: 2587 Training R2: -inf
Epoch: 2588 Training R2: -inf
Epoch: 2589 Training R2: -inf
Epoch: 2590 Training R2: -inf
Epoch: 2591 Training R2: -inf
Epoch: 2592 Training R2: -inf
Epoch: 2593 Training R2: -inf
Epoch: 2594 Training R2: -inf
Epoch: 2595 Training R2: -inf
Epoch: 2596 Training R2: -inf
Epoch: 2597 Training R2: -inf
Epoch: 2598 Training R2: -inf
Epoch: 2599 Training R2: -inf
Epoch: 2600 Training R2: -inf
Epoch: 2601 Training R2: -inf
Epoch: 2602 Training R2: -inf
Epoch: 2603 Training R2: -inf
Epoch: 2604 Training R2: -inf
Epoch: 2605 Training R2: -inf
Epoch: 2606 Training R2: -inf
Epoch: 2607 Training R2: -inf
Epoch: 2608 Training R2: -inf
Epoch: 2609 Training R2: -inf
Epoch: 2610 Training R2: -inf
Epoch: 2611 Training R2: -inf
Epoch: 2612 Training R2: -inf
Epoch: 2613 Training R2: -inf
Epoch: 2614 Training R2: -inf
Epoch: 2615 Training R2: -inf
Epoch: 2616 Training R2: -inf
Epoch: 2617 Training R2: -inf
Epoch: 2618 Training R2: -inf
Epoch: 2619 Training R2: -inf
Epoch: 2620 Training R2: -inf
Epoch: 2621 Training R2: -inf
Epoch: 2622 Training R2: -inf
Epoch: 2623 Training R2: -inf
Epoch: 2624 Training R2: -inf
Epoch: 2625 Training R2: -inf
Epoch: 2626 Training R2: -inf
Epoch: 2627 Training R2: -inf
Epoch: 2628 Training R2: -inf
Epoch: 2629 Training R2: -inf
Epoch: 2630 Training R2: -inf
Epoch: 2631 Training R2: -inf
Epoch: 2632 Training R2: -inf
Epoch: 2633 Training R2: -inf
Epoch: 2634 Training R2: -inf
Epoch: 2635 Training R2: -inf
Epoch: 2636 Training R2: -inf
Epoch: 2637 Training R2: -inf
Epoch: 2638 Training R2: -inf
Epoch: 2639 Training R2: -inf
Epoch: 2640 Training R2: -inf
Epoch: 2641 Training R2: -inf
Epoch: 2642 Training R2: -inf
Epoch: 2643 Training R2: -inf
Epoch: 2644 Training R2: -inf
Epoch: 2645 Training R2: -inf
Epoch: 2646 Training R2: -inf
Epoch: 2647 Training R2: -inf
Epoch: 2648 Training R2: -inf
Epoch: 2649 Training R2: -inf
Epoch: 2650 Training R2: -inf
Epoch: 2651 Training R2: -inf
Epoch: 2652 Training R2: -inf
Epoch: 2653 Training R2: -inf
Epoch: 2654 Training R2: -inf
Epoch: 2655 Training R2: -inf
Epoch: 2656 Training R2: -inf
Epoch: 2657 Training R2: -inf
Epoch: 2658 Training R2: -inf
Epoch: 2659 Training R2: -inf
Epoch: 2660 Training R2: -inf
Epoch: 2661 Training R2: -inf
Epoch: 2662 Training R2: -inf
Epoch: 2663 Training R2: -inf
Epoch: 2664 Training R2: -inf
Epoch: 2665 Training R2: -inf
Epoch: 2666 Training R2: -inf
Epoch: 2667 Training R2: -inf
Epoch: 2668 Training R2: -inf
Epoch: 2669 Training R2: -inf
Epoch: 2670 Training R2: -inf
Epoch: 2671 Training R2: -inf
Epoch: 2672 Training R2: -inf
Epoch: 2673 Training R2: -inf
Epoch: 2674 Training R2: -inf
Epoch: 2675 Training R2: -inf
Epoch: 2676 Training R2: -inf
Epoch: 2677 Training R2: -inf
Epoch: 2678 Training R2: -inf
Epoch: 2679 Training R2: -inf
Epoch: 2680 Training R2: -inf
Epoch: 2681 Training R2: -inf
Epoch: 2682 Training R2: -inf
Epoch: 2683 Training R2: -inf
Epoch: 2684 Training R2: -inf
Epoch: 2685 Training R2: -inf
Epoch: 2686 Training R2: -inf
Epoch: 2687 Training R2: -inf
Epoch: 2688 Training R2: -inf
Epoch: 2689 Training R2: -inf
Epoch: 2690 Training R2: -inf
Epoch: 2691 Training R2: -inf
Epoch: 2692 Training R2: -inf
Epoch: 2693 Training R2: -inf
Epoch: 2694 Training R2: -inf
Epoch: 2695 Training R2: -inf
Epoch: 2696 Training R2: -inf
Epoch: 2697 Training R2: -inf
Epoch: 2698 Training R2: -inf
Epoch: 2699 Training R2: -inf
Epoch: 2700 Training R2: -inf
Epoch: 2701 Training R2: -inf
Epoch: 2702 Training R2: -inf
Epoch: 2703 Training R2: -inf
Epoch: 2704 Training R2: -inf
Epoch: 2705 Training R2: -inf
Epoch: 2706 Training R2: -inf
Epoch: 2707 Training R2: -inf
Epoch: 2708 Training R2: -inf
Epoch: 2709 Training R2: -inf
Epoch: 2710 Training R2: -inf
Epoch: 2711 Training R2: -inf
Epoch: 2712 Training R2: -inf
Epoch: 2713 Training R2: -inf
Epoch: 2714 Training R2: -inf
Epoch: 2715 Training R2: -inf
Epoch: 2716 Training R2: -inf
Epoch: 2717 Training R2: -inf
Epoch: 2718 Training R2: -inf
Epoch: 2719 Training R2: -inf
Epoch: 2720 Training R2: -inf
Epoch: 2721 Training R2: -inf
Epoch: 2722 Training R2: -inf
Epoch: 2723 Training R2: -inf
Epoch: 2724 Training R2: -inf
Epoch: 2725 Training R2: -inf
Epoch: 2726 Training R2: -inf
Epoch: 2727 Training R2: -inf
Epoch: 2728 Training R2: -inf
Epoch: 2729 Training R2: -inf
Epoch: 2730 Training R2: -inf
Epoch: 2731 Training R2: -inf
Epoch: 2732 Training R2: -inf
Epoch: 2733 Training R2: -inf
Epoch: 2734 Training R2: -inf
Epoch: 2735 Training R2: -inf
Epoch: 2736 Training R2: -inf
Epoch: 2737 Training R2: -inf
Epoch: 2738 Training R2: -inf
Epoch: 2739 Training R2: -inf
Epoch: 2740 Training R2: -inf
Epoch: 2741 Training R2: -inf
Epoch: 2742 Training R2: -inf
Epoch: 2743 Training R2: -inf
Epoch: 2744 Training R2: -inf
Epoch: 2745 Training R2: -inf
Epoch: 2746 Training R2: -inf
Epoch: 2747 Training R2: -inf
Epoch: 2748 Training R2: nan
Epoch: 2749 Training R2: nan
Epoch: 2750 Training R2: nan
Epoch: 2751 Training R2: nan
Epoch: 2752 Training R2: nan
Epoch: 2753 Training R2: nan
Epoch: 2754 Training R2: nan
Epoch: 2755 Training R2: nan
Epoch: 2756 Training R2: nan
Epoch: 2757 Training R2: nan
Epoch: 2758 Training R2: nan
Epoch: 2759 Training R2: nan
Epoch: 2760 Training R2: nan
Epoch: 2761 Training R2: nan
Epoch: 2762 Training R2: nan
Epoch: 2763 Training R2: nan
Epoch: 2764 Training R2: nan
Epoch: 2765 Training R2: nan
Epoch: 2766 Training R2: nan
Epoch: 2767 Training R2: nan
Epoch: 2768 Training R2: nan
Epoch: 2769 Training R2: nan
Epoch: 2770 Training R2: nan
Epoch: 2771 Training R2: nan
Epoch: 2772 Training R2: nan
Epoch: 2773 Training R2: nan
Epoch: 2774 Training R2: nan
Epoch: 2775 Training R2: nan
Epoch: 2776 Training R2: nan
Epoch: 2777 Training R2: nan
Epoch: 2778 Training R2: nan
Epoch: 2779 Training R2: nan
Epoch: 2780 Training R2: nan
Epoch: 2781 Training R2: nan
Epoch: 2782 Training R2: nan
Epoch: 2783 Training R2: nan
Epoch: 2784 Training R2: nan
Epoch: 2785 Training R2: nan
Epoch: 2786 Training R2: nan
Epoch: 2787 Training R2: nan
Epoch: 2788 Training R2: nan
Epoch: 2789 Training R2: nan
Epoch: 2790 Training R2: nan
Epoch: 2791 Training R2: nan
Epoch: 2792 Training R2: nan
Epoch: 2793 Training R2: nan
Epoch: 2794 Training R2: nan
Epoch: 2795 Training R2: nan
Epoch: 2796 Training R2: nan
Epoch: 2797 Training R2: nan
Epoch: 2798 Training R2: nan
Epoch: 2799 Training R2: nan
Epoch: 2800 Training R2: nan
Epoch: 2801 Training R2: nan
Epoch: 2802 Training R2: nan
Epoch: 2803 Training R2: nan
Epoch: 2804 Training R2: nan
Epoch: 2805 Training R2: nan
Epoch: 2806 Training R2: nan
Epoch: 2807 Training R2: nan
Epoch: 2808 Training R2: nan
Epoch: 2809 Training R2: nan
Epoch: 2810 Training R2: nan
Epoch: 2811 Training R2: nan
Epoch: 2812 Training R2: nan
Epoch: 2813 Training R2: nan
Epoch: 2814 Training R2: nan
Epoch: 2815 Training R2: nan
Epoch: 2816 Training R2: nan
Epoch: 2817 Training R2: nan
Epoch: 2818 Training R2: nan
Epoch: 2819 Training R2: nan
Epoch: 2820 Training R2: nan
Epoch: 2821 Training R2: nan
Epoch: 2822 Training R2: nan
Epoch: 2823 Training R2: nan
Epoch: 2824 Training R2: nan
Epoch: 2825 Training R2: nan
Epoch: 2826 Training R2: nan
Epoch: 2827 Training R2: nan
Epoch: 2828 Training R2: nan
Epoch: 2829 Training R2: nan
Epoch: 2830 Training R2: nan
Epoch: 2831 Training R2: nan
Epoch: 2832 Training R2: nan
Epoch: 2833 Training R2: nan
Epoch: 2834 Training R2: nan
Epoch: 2835 Training R2: nan
Epoch: 2836 Training R2: nan
Epoch: 2837 Training R2: nan
Epoch: 2838 Training R2: nan
Epoch: 2839 Training R2: nan
Epoch: 2840 Training R2: nan
Epoch: 2841 Training R2: nan
Epoch: 2842 Training R2: nan
Epoch: 2843 Training R2: nan
Epoch: 2844 Training R2: nan
Epoch: 2845 Training R2: nan
Epoch: 2846 Training R2: nan
Epoch: 2847 Training R2: nan
Epoch: 2848 Training R2: nan
Epoch: 2849 Training R2: nan
Epoch: 2850 Training R2: nan
Epoch: 2851 Training R2: nan
Epoch: 2852 Training R2: nan
Epoch: 2853 Training R2: nan
Epoch: 2854 Training R2: nan
Epoch: 2855 Training R2: nan
Epoch: 2856 Training R2: nan
Epoch: 2857 Training R2: nan
Epoch: 2858 Training R2: nan
Epoch: 2859 Training R2: nan
Epoch: 2860 Training R2: nan
Epoch: 2861 Training R2: nan
Epoch: 2862 Training R2: nan
Epoch: 2863 Training R2: nan
Epoch: 2864 Training R2: nan
Epoch: 2865 Training R2: nan
Epoch: 2866 Training R2: nan
Epoch: 2867 Training R2: nan
Epoch: 2868 Training R2: nan
Epoch: 2869 Training R2: nan
Epoch: 2870 Training R2: nan
Epoch: 2871 Training R2: nan
Epoch: 2872 Training R2: nan
Epoch: 2873 Training R2: nan
Epoch: 2874 Training R2: nan
Epoch: 2875 Training R2: nan
Epoch: 2876 Training R2: nan
Epoch: 2877 Training R2: nan
Epoch: 2878 Training R2: nan
Epoch: 2879 Training R2: nan
Epoch: 2880 Training R2: nan
Epoch: 2881 Training R2: nan
Epoch: 2882 Training R2: nan
Epoch: 2883 Training R2: nan
Epoch: 2884 Training R2: nan
Epoch: 2885 Training R2: nan
Epoch: 2886 Training R2: nan
Epoch: 2887 Training R2: nan
Epoch: 2888 Training R2: nan
Epoch: 2889 Training R2: nan
Epoch: 2890 Training R2: nan
Epoch: 2891 Training R2: nan
Epoch: 2892 Training R2: nan
Epoch: 2893 Training R2: nan
Epoch: 2894 Training R2: nan
Epoch: 2895 Training R2: nan
Epoch: 2896 Training R2: nan
Epoch: 2897 Training R2: nan
Epoch: 2898 Training R2: nan
Epoch: 2899 Training R2: nan
Epoch: 2900 Training R2: nan
Epoch: 2901 Training R2: nan
Epoch: 2902 Training R2: nan
Epoch: 2903 Training R2: nan
Epoch: 2904 Training R2: nan
Epoch: 2905 Training R2: nan
Epoch: 2906 Training R2: nan
Epoch: 2907 Training R2: nan
Epoch: 2908 Training R2: nan
Epoch: 2909 Training R2: nan
Epoch: 2910 Training R2: nan
Epoch: 2911 Training R2: nan
Epoch: 2912 Training R2: nan
Epoch: 2913 Training R2: nan
Epoch: 2914 Training R2: nan
Epoch: 2915 Training R2: nan
Epoch: 2916 Training R2: nan
Epoch: 2917 Training R2: nan
Epoch: 2918 Training R2: nan
Epoch: 2919 Training R2: nan
Epoch: 2920 Training R2: nan
Epoch: 2921 Training R2: nan
Epoch: 2922 Training R2: nan
Epoch: 2923 Training R2: nan
Epoch: 2924 Training R2: nan
Epoch: 2925 Training R2: nan
Epoch: 2926 Training R2: nan
Epoch: 2927 Training R2: nan
Epoch: 2928 Training R2: nan
Epoch: 2929 Training R2: nan
Epoch: 2930 Training R2: nan
Epoch: 2931 Training R2: nan
Epoch: 2932 Training R2: nan
Epoch: 2933 Training R2: nan
Epoch: 2934 Training R2: nan
Epoch: 2935 Training R2: nan
Epoch: 2936 Training R2: nan
Epoch: 2937 Training R2: nan
Epoch: 2938 Training R2: nan
Epoch: 2939 Training R2: nan
Epoch: 2940 Training R2: nan
Epoch: 2941 Training R2: nan
Epoch: 2942 Training R2: nan
Epoch: 2943 Training R2: nan
Epoch: 2944 Training R2: nan
Epoch: 2945 Training R2: nan
Epoch: 2946 Training R2: nan
Epoch: 2947 Training R2: nan
Epoch: 2948 Training R2: nan
Epoch: 2949 Training R2: nan
Epoch: 2950 Training R2: nan
Epoch: 2951 Training R2: nan
Epoch: 2952 Training R2: nan
Epoch: 2953 Training R2: nan
Epoch: 2954 Training R2: nan
Epoch: 2955 Training R2: nan
Epoch: 2956 Training R2: nan
Epoch: 2957 Training R2: nan
Epoch: 2958 Training R2: nan
Epoch: 2959 Training R2: nan
Epoch: 2960 Training R2: nan
Epoch: 2961 Training R2: nan
Epoch: 2962 Training R2: nan
Epoch: 2963 Training R2: nan
Epoch: 2964 Training R2: nan
Epoch: 2965 Training R2: nan
Epoch: 2966 Training R2: nan
Epoch: 2967 Training R2: nan
Epoch: 2968 Training R2: nan
Epoch: 2969 Training R2: nan
Epoch: 2970 Training R2: nan
Epoch: 2971 Training R2: nan
Epoch: 2972 Training R2: nan
Epoch: 2973 Training R2: nan
Epoch: 2974 Training R2: nan
Epoch: 2975 Training R2: nan
Epoch: 2976 Training R2: nan
Epoch: 2977 Training R2: nan
Epoch: 2978 Training R2: nan
Epoch: 2979 Training R2: nan
Epoch: 2980 Training R2: nan
Epoch: 2981 Training R2: nan
Epoch: 2982 Training R2: nan
Epoch: 2983 Training R2: nan
Epoch: 2984 Training R2: nan
Epoch: 2985 Training R2: nan
Epoch: 2986 Training R2: nan
Epoch: 2987 Training R2: nan
Epoch: 2988 Training R2: nan
Epoch: 2989 Training R2: nan
Epoch: 2990 Training R2: nan
Epoch: 2991 Training R2: nan
Epoch: 2992 Training R2: nan
Epoch: 2993 Training R2: nan
Epoch: 2994 Training R2: nan
Epoch: 2995 Training R2: nan
Epoch: 2996 Training R2: nan
Epoch: 2997 Training R2: nan
Epoch: 2998 Training R2: nan
Epoch: 2999 Training R2: nan
Epoch: 3000 Training R2: nan
Epoch: 3001 Training R2: nan
Epoch: 3002 Training R2: nan
Epoch: 3003 Training R2: nan
Epoch: 3004 Training R2: nan
Epoch: 3005 Training R2: nan
Epoch: 3006 Training R2: nan
Epoch: 3007 Training R2: nan
Epoch: 3008 Training R2: nan
Epoch: 3009 Training R2: nan
Epoch: 3010 Training R2: nan
Epoch: 3011 Training R2: nan
Epoch: 3012 Training R2: nan
Epoch: 3013 Training R2: nan
Epoch: 3014 Training R2: nan
Epoch: 3015 Training R2: nan
Epoch: 3016 Training R2: nan
Epoch: 3017 Training R2: nan
Epoch: 3018 Training R2: nan
Epoch: 3019 Training R2: nan
Epoch: 3020 Training R2: nan
Epoch: 3021 Training R2: nan
Epoch: 3022 Training R2: nan
Epoch: 3023 Training R2: nan
Epoch: 3024 Training R2: nan
Epoch: 3025 Training R2: nan
Epoch: 3026 Training R2: nan
Epoch: 3027 Training R2: nan
Epoch: 3028 Training R2: nan
Epoch: 3029 Training R2: nan
Epoch: 3030 Training R2: nan
Epoch: 3031 Training R2: nan
Epoch: 3032 Training R2: nan
Epoch: 3033 Training R2: nan
Epoch: 3034 Training R2: nan
Epoch: 3035 Training R2: nan
Epoch: 3036 Training R2: nan
Epoch: 3037 Training R2: nan
Epoch: 3038 Training R2: nan
Epoch: 3039 Training R2: nan

C:\Users\Gaurish Garg\AppData\Local\Temp\ipykernel_21288\3078470972.py:14: RuntimeWarning: overflow encountered in matmul
  gradient = 1/n*np.matmul(x_tr1.transpose(),errors)
C:\Users\Gaurish Garg\AppData\Local\Temp\ipykernel_21288\3078470972.py:15: RuntimeWarning: invalid value encountered in subtract
  betas = betas - alpha*gradient

Epoch: 3241 Training R2: nan
Epoch: 3242 Training R2: nan
Epoch: 3243 Training R2: nan
Epoch: 3244 Training R2: nan
Epoch: 3245 Training R2: nan
Epoch: 3246 Training R2: nan
Epoch: 3247 Training R2: nan
Epoch: 3248 Training R2: nan
Epoch: 3249 Training R2: nan
Epoch: 3250 Training R2: nan
Epoch: 3251 Training R2: nan
Epoch: 3252 Training R2: nan
Epoch: 3253 Training R2: nan
Epoch: 3254 Training R2: nan
Epoch: 3255 Training R2: nan
Epoch: 3256 Training R2: nan
Epoch: 3257 Training R2: nan
Epoch: 3258 Training R2: nan
Epoch: 3259 Training R2: nan
Epoch: 3260 Training R2: nan
Epoch: 3261 Training R2: nan
Epoch: 3262 Training R2: nan
Epoch: 3263 Training R2: nan
Epoch: 3264 Training R2: nan
Epoch: 3265 Training R2: nan
Epoch: 3266 Training R2: nan
Epoch: 3267 Training R2: nan
Epoch: 3268 Training R2: nan
Epoch: 3269 Training R2: nan
Epoch: 3270 Training R2: nan
Epoch: 3271 Training R2: nan
Epoch: 3272 Training R2: nan
Epoch: 3273 Training R2: nan
Epoch: 3274 Training R2: nan
Epoch: 3275 Training R2: nan
Epoch: 3276 Training R2: nan
Epoch: 3277 Training R2: nan
Epoch: 3278 Training R2: nan
Epoch: 3279 Training R2: nan
Epoch: 3280 Training R2: nan
Epoch: 3281 Training R2: nan
Epoch: 3282 Training R2: nan
Epoch: 3283 Training R2: nan
Epoch: 3284 Training R2: nan
Epoch: 3285 Training R2: nan
Epoch: 3286 Training R2: nan
Epoch: 3287 Training R2: nan
Epoch: 3288 Training R2: nan
Epoch: 3289 Training R2: nan
Epoch: 3290 Training R2: nan
Epoch: 3291 Training R2: nan
Epoch: 3292 Training R2: nan
Epoch: 3293 Training R2: nan
Epoch: 3294 Training R2: nan
Epoch: 3295 Training R2: nan
Epoch: 3296 Training R2: nan
Epoch: 3297 Training R2: nan
Epoch: 3298 Training R2: nan
Epoch: 3299 Training R2: nan
Epoch: 3300 Training R2: nan
Epoch: 3301 Training R2: nan
Epoch: 3302 Training R2: nan
Epoch: 3303 Training R2: nan
Epoch: 3304 Training R2: nan
Epoch: 3305 Training R2: nan
Epoch: 3306 Training R2: nan
Epoch: 3307 Training R2: nan
Epoch: 3308 Training R2: nan
Epoch: 3309 Training R2: nan
Epoch: 3310 Training R2: nan
Epoch: 3311 Training R2: nan
Epoch: 3312 Training R2: nan
Epoch: 3313 Training R2: nan
Epoch: 3314 Training R2: nan
Epoch: 3315 Training R2: nan
Epoch: 3316 Training R2: nan
Epoch: 3317 Training R2: nan
Epoch: 3318 Training R2: nan
Epoch: 3319 Training R2: nan
Epoch: 3320 Training R2: nan
Epoch: 3321 Training R2: nan
Epoch: 3322 Training R2: nan
Epoch: 3323 Training R2: nan
Epoch: 3324 Training R2: nan
Epoch: 3325 Training R2: nan
Epoch: 3326 Training R2: nan
Epoch: 3327 Training R2: nan
Epoch: 3328 Training R2: nan
Epoch: 3329 Training R2: nan
Epoch: 3330 Training R2: nan
Epoch: 3331 Training R2: nan
Epoch: 3332 Training R2: nan
Epoch: 3333 Training R2: nan
Epoch: 3334 Training R2: nan
Epoch: 3335 Training R2: nan
Epoch: 3336 Training R2: nan
Epoch: 3337 Training R2: nan
Epoch: 3338 Training R2: nan
Epoch: 3339 Training R2: nan
Epoch: 3340 Training R2: nan
Epoch: 3341 Training R2: nan
Epoch: 3342 Training R2: nan
Epoch: 3343 Training R2: nan
Epoch: 3344 Training R2: nan
Epoch: 3345 Training R2: nan
Epoch: 3346 Training R2: nan
Epoch: 3347 Training R2: nan
Epoch: 3348 Training R2: nan
Epoch: 3349 Training R2: nan
Epoch: 3350 Training R2: nan
Epoch: 3351 Training R2: nan
Epoch: 3352 Training R2: nan
Epoch: 3353 Training R2: nan
Epoch: 3354 Training R2: nan
Epoch: 3355 Training R2: nan
Epoch: 3356 Training R2: nan
Epoch: 3357 Training R2: nan
Epoch: 3358 Training R2: nan
Epoch: 3359 Training R2: nan
Epoch: 3360 Training R2: nan
Epoch: 3361 Training R2: nan
Epoch: 3362 Training R2: nan
Epoch: 3363 Training R2: nan
Epoch: 3364 Training R2: nan
Epoch: 3365 Training R2: nan
Epoch: 3366 Training R2: nan
Epoch: 3367 Training R2: nan
Epoch: 3368 Training R2: nan
Epoch: 3369 Training R2: nan
Epoch: 3370 Training R2: nan
Epoch: 3371 Training R2: nan
Epoch: 3372 Training R2: nan
Epoch: 3373 Training R2: nan
Epoch: 3374 Training R2: nan
Epoch: 3375 Training R2: nan
Epoch: 3376 Training R2: nan
Epoch: 3377 Training R2: nan
Epoch: 3378 Training R2: nan
Epoch: 3379 Training R2: nan
Epoch: 3380 Training R2: nan
Epoch: 3381 Training R2: nan
Epoch: 3382 Training R2: nan
Epoch: 3383 Training R2: nan
Epoch: 3384 Training R2: nan
Epoch: 3385 Training R2: nan
Epoch: 3386 Training R2: nan
Epoch: 3387 Training R2: nan
Epoch: 3388 Training R2: nan
Epoch: 3389 Training R2: nan
Epoch: 3390 Training R2: nan
Epoch: 3391 Training R2: nan
Epoch: 3392 Training R2: nan
Epoch: 3393 Training R2: nan
Epoch: 3394 Training R2: nan
Epoch: 3395 Training R2: nan
Epoch: 3396 Training R2: nan
Epoch: 3397 Training R2: nan
Epoch: 3398 Training R2: nan
Epoch: 3399 Training R2: nan
Epoch: 3400 Training R2: nan
Epoch: 3401 Training R2: nan
Epoch: 3402 Training R2: nan
Epoch: 3403 Training R2: nan
Epoch: 3404 Training R2: nan
Epoch: 3405 Training R2: nan
Epoch: 3406 Training R2: nan
Epoch: 3407 Training R2: nan
Epoch: 3408 Training R2: nan
Epoch: 3409 Training R2: nan
Epoch: 3410 Training R2: nan
Epoch: 3411 Training R2: nan
Epoch: 3412 Training R2: nan
Epoch: 3413 Training R2: nan
Epoch: 3414 Training R2: nan
Epoch: 3415 Training R2: nan
Epoch: 3416 Training R2: nan
Epoch: 3417 Training R2: nan
Epoch: 3418 Training R2: nan
Epoch: 3419 Training R2: nan
Epoch: 3420 Training R2: nan
Epoch: 3421 Training R2: nan
Epoch: 3422 Training R2: nan
Epoch: 3423 Training R2: nan
Epoch: 3424 Training R2: nan
Epoch: 3425 Training R2: nan
Epoch: 3426 Training R2: nan
Epoch: 3427 Training R2: nan
Epoch: 3428 Training R2: nan
Epoch: 3429 Training R2: nan
Epoch: 3430 Training R2: nan
Epoch: 3431 Training R2: nan
Epoch: 3432 Training R2: nan
Epoch: 3433 Training R2: nan
Epoch: 3434 Training R2: nan
Epoch: 3435 Training R2: nan
Epoch: 3436 Training R2: nan
Epoch: 3437 Training R2: nan
Epoch: 3438 Training R2: nan
Epoch: 3439 Training R2: nan
Epoch: 3440 Training R2: nan
Epoch: 3441 Training R2: nan
Epoch: 3442 Training R2: nan
Epoch: 3443 Training R2: nan
Epoch: 3444 Training R2: nan
Epoch: 3445 Training R2: nan
Epoch: 3446 Training R2: nan
Epoch: 3447 Training R2: nan
Epoch: 3448 Training R2: nan
Epoch: 3449 Training R2: nan
Epoch: 3450 Training R2: nan
Epoch: 3451 Training R2: nan
Epoch: 3452 Training R2: nan
Epoch: 3453 Training R2: nan
Epoch: 3454 Training R2: nan
Epoch: 3455 Training R2: nan
Epoch: 3456 Training R2: nan
Epoch: 3457 Training R2: nan
Epoch: 3458 Training R2: nan
Epoch: 3459 Training R2: nan
Epoch: 3460 Training R2: nan
Epoch: 3461 Training R2: nan
Epoch: 3462 Training R2: nan
Epoch: 3463 Training R2: nan
Epoch: 3464 Training R2: nan
Epoch: 3465 Training R2: nan
Epoch: 3466 Training R2: nan
Epoch: 3467 Training R2: nan
Epoch: 3468 Training R2: nan
Epoch: 3469 Training R2: nan
Epoch: 3470 Training R2: nan
Epoch: 3471 Training R2: nan
Epoch: 3472 Training R2: nan
Epoch: 3473 Training R2: nan
Epoch: 3474 Training R2: nan
Epoch: 3475 Training R2: nan
Epoch: 3476 Training R2: nan
Epoch: 3477 Training R2: nan
Epoch: 3478 Training R2: nan
Epoch: 3479 Training R2: nan
Epoch: 3480 Training R2: nan
Epoch: 3481 Training R2: nan
Epoch: 3482 Training R2: nan
Epoch: 3483 Training R2: nan
Epoch: 3484 Training R2: nan
Epoch: 3485 Training R2: nan
Epoch: 3486 Training R2: nan
Epoch: 3487 Training R2: nan
Epoch: 3488 Training R2: nan
Epoch: 3489 Training R2: nan
Epoch: 3490 Training R2: nan
Epoch: 3491 Training R2: nan
Epoch: 3492 Training R2: nan
Epoch: 3493 Training R2: nan
Epoch: 3494 Training R2: nan
Epoch: 3495 Training R2: nan
Epoch: 3496 Training R2: nan
Epoch: 3497 Training R2: nan
Epoch: 3498 Training R2: nan
Epoch: 3499 Training R2: nan
Epoch: 3500 Training R2: nan
Epoch: 3501 Training R2: nan
Epoch: 3502 Training R2: nan
Epoch: 3503 Training R2: nan
Epoch: 3504 Training R2: nan
Epoch: 3505 Training R2: nan
Epoch: 3506 Training R2: nan
Epoch: 3507 Training R2: nan
Epoch: 3508 Training R2: nan
Epoch: 3509 Training R2: nan
Epoch: 3510 Training R2: nan
Epoch: 3511 Training R2: nan
Epoch: 3512 Training R2: nan
Epoch: 3513 Training R2: nan
Epoch: 3514 Training R2: nan
Epoch: 3515 Training R2: nan
Epoch: 3516 Training R2: nan
Epoch: 3517 Training R2: nan
Epoch: 3518 Training R2: nan
Epoch: 3519 Training R2: nan
Epoch: 3520 Training R2: nan
Epoch: 3521 Training R2: nan
Epoch: 3522 Training R2: nan
Epoch: 3523 Training R2: nan
Epoch: 3524 Training R2: nan
Epoch: 3525 Training R2: nan
Epoch: 3526 Training R2: nan
Epoch: 3527 Training R2: nan
Epoch: 3528 Training R2: nan
Epoch: 3529 Training R2: nan
Epoch: 3530 Training R2: nan
Epoch: 3531 Training R2: nan
Epoch: 3532 Training R2: nan
Epoch: 3533 Training R2: nan
Epoch: 3534 Training R2: nan
Epoch: 3535 Training R2: nan
Epoch: 3536 Training R2: nan
Epoch: 3537 Training R2: nan
Epoch: 3538 Training R2: nan
Epoch: 3539 Training R2: nan
Epoch: 3540 Training R2: nan
Epoch: 3541 Training R2: nan
Epoch: 3542 Training R2: nan
Epoch: 3543 Training R2: nan
Epoch: 3544 Training R2: nan
Epoch: 3545 Training R2: nan
Epoch: 3546 Training R2: nan
Epoch: 3547 Training R2: nan
Epoch: 3548 Training R2: nan
Epoch: 3549 Training R2: nan
Epoch: 3550 Training R2: nan
Epoch: 3551 Training R2: nan
Epoch: 3552 Training R2: nan
Epoch: 3553 Training R2: nan
Epoch: 3554 Training R2: nan
Epoch: 3555 Training R2: nan
Epoch: 3556 Training R2: nan
Epoch: 3557 Training R2: nan
Epoch: 3558 Training R2: nan
Epoch: 3559 Training R2: nan
Epoch: 3560 Training R2: nan
Epoch: 3561 Training R2: nan
Epoch: 3562 Training R2: nan
Epoch: 3563 Training R2: nan
Epoch: 3564 Training R2: nan
Epoch: 3565 Training R2: nan
Epoch: 3566 Training R2: nan
Epoch: 3567 Training R2: nan
Epoch: 3568 Training R2: nan
Epoch: 3569 Training R2: nan
Epoch: 3570 Training R2: nan
Epoch: 3571 Training R2: nan
Epoch: 3572 Training R2: nan
Epoch: 3573 Training R2: nan
Epoch: 3574 Training R2: nan
Epoch: 3575 Training R2: nan
Epoch: 3576 Training R2: nan
Epoch: 3577 Training R2: nan
Epoch: 3578 Training R2: nan
Epoch: 3579 Training R2: nan
Epoch: 3580 Training R2: nan
Epoch: 3581 Training R2: nan
Epoch: 3582 Training R2: nan
Epoch: 3583 Training R2: nan
Epoch: 3584 Training R2: nan
Epoch: 3585 Training R2: nan
Epoch: 3586 Training R2: nan
Epoch: 3587 Training R2: nan
Epoch: 3588 Training R2: nan
Epoch: 3589 Training R2: nan
Epoch: 3590 Training R2: nan
Epoch: 3591 Training R2: nan
Epoch: 3592 Training R2: nan
Epoch: 3593 Training R2: nan
Epoch: 3594 Training R2: nan
Epoch: 3595 Training R2: nan
Epoch: 3596 Training R2: nan
Epoch: 3597 Training R2: nan
Epoch: 3598 Training R2: nan
Epoch: 3599 Training R2: nan
Epoch: 3600 Training R2: nan
Epoch: 3601 Training R2: nan
Epoch: 3602 Training R2: nan
Epoch: 3603 Training R2: nan
Epoch: 3604 Training R2: nan
Epoch: 3605 Training R2: nan
Epoch: 3606 Training R2: nan
Epoch: 3607 Training R2: nan
Epoch: 3608 Training R2: nan
Epoch: 3609 Training R2: nan
Epoch: 3610 Training R2: nan
Epoch: 3611 Training R2: nan
Epoch: 3612 Training R2: nan
Epoch: 3613 Training R2: nan
Epoch: 3614 Training R2: nan
Epoch: 3615 Training R2: nan
Epoch: 3616 Training R2: nan
Epoch: 3617 Training R2: nan
Epoch: 3618 Training R2: nan
Epoch: 3619 Training R2: nan
Epoch: 3620 Training R2: nan
Epoch: 3621 Training R2: nan
Epoch: 3622 Training R2: nan
Epoch: 3623 Training R2: nan
Epoch: 3624 Training R2: nan
Epoch: 3625 Training R2: nan
Epoch: 3626 Training R2: nan
Epoch: 3627 Training R2: nan
Epoch: 3628 Training R2: nan
Epoch: 3629 Training R2: nan
Epoch: 3630 Training R2: nan
Epoch: 3631 Training R2: nan
Epoch: 3632 Training R2: nan
Epoch: 3633 Training R2: nan
Epoch: 3634 Training R2: nan
Epoch: 3635 Training R2: nan
Epoch: 3636 Training R2: nan
Epoch: 3637 Training R2: nan
Epoch: 3638 Training R2: nan
Epoch: 3639 Training R2: nan
Epoch: 3640 Training R2: nan
Epoch: 3641 Training R2: nan
Epoch: 3642 Training R2: nan
Epoch: 3643 Training R2: nan
Epoch: 3644 Training R2: nan
Epoch: 3645 Training R2: nan
Epoch: 3646 Training R2: nan
Epoch: 3647 Training R2: nan
Epoch: 3648 Training R2: nan
Epoch: 3649 Training R2: nan
Epoch: 3650 Training R2: nan
Epoch: 3651 Training R2: nan
Epoch: 3652 Training R2: nan
Epoch: 3653 Training R2: nan
Epoch: 3654 Training R2: nan
Epoch: 3655 Training R2: nan
Epoch: 3656 Training R2: nan
Epoch: 3657 Training R2: nan
Epoch: 3658 Training R2: nan
Epoch: 3659 Training R2: nan
Epoch: 3660 Training R2: nan
Epoch: 3661 Training R2: nan
Epoch: 3662 Training R2: nan
Epoch: 3663 Training R2: nan
Epoch: 3664 Training R2: nan
Epoch: 3665 Training R2: nan
Epoch: 3666 Training R2: nan
Epoch: 3667 Training R2: nan
Epoch: 3668 Training R2: nan
Epoch: 3669 Training R2: nan
Epoch: 3670 Training R2: nan
Epoch: 3671 Training R2: nan
Epoch: 3672 Training R2: nan
Epoch: 3673 Training R2: nan
Epoch: 3674 Training R2: nan
Epoch: 3675 Training R2: nan
Epoch: 3676 Training R2: nan
Epoch: 3677 Training R2: nan
Epoch: 3678 Training R2: nan
Epoch: 3679 Training R2: nan
Epoch: 3680 Training R2: nan
Epoch: 3681 Training R2: nan
Epoch: 3682 Training R2: nan
Epoch: 3683 Training R2: nan
Epoch: 3684 Training R2: nan
Epoch: 3685 Training R2: nan
Epoch: 3686 Training R2: nan
Epoch: 3687 Training R2: nan
Epoch: 3688 Training R2: nan
Epoch: 3689 Training R2: nan
Epoch: 3690 Training R2: nan
Epoch: 3691 Training R2: nan
Epoch: 3692 Training R2: nan
Epoch: 3693 Training R2: nan
Epoch: 3694 Training R2: nan
Epoch: 3695 Training R2: nan
Epoch: 3696 Training R2: nan
Epoch: 3697 Training R2: nan
Epoch: 3698 Training R2: nan
Epoch: 3699 Training R2: nan
Epoch: 3700 Training R2: nan
Epoch: 3701 Training R2: nan
Epoch: 3702 Training R2: nan
Epoch: 3703 Training R2: nan
Epoch: 3704 Training R2: nan
Epoch: 3705 Training R2: nan
Epoch: 3706 Training R2: nan
Epoch: 3707 Training R2: nan
Epoch: 3708 Training R2: nan
Epoch: 3709 Training R2: nan
Epoch: 3710 Training R2: nan
Epoch: 3711 Training R2: nan
Epoch: 3712 Training R2: nan
Epoch: 3713 Training R2: nan
Epoch: 3714 Training R2: nan
Epoch: 3715 Training R2: nan
Epoch: 3716 Training R2: nan
Epoch: 3717 Training R2: nan
Epoch: 3718 Training R2: nan
Epoch: 3719 Training R2: nan
Epoch: 3720 Training R2: nan
Epoch: 3721 Training R2: nan
Epoch: 3722 Training R2: nan
Epoch: 3723 Training R2: nan
Epoch: 3724 Training R2: nan
Epoch: 3725 Training R2: nan
Epoch: 3726 Training R2: nan
Epoch: 3727 Training R2: nan
Epoch: 3728 Training R2: nan
Epoch: 3729 Training R2: nan
Epoch: 3730 Training R2: nan
Epoch: 3731 Training R2: nan
Epoch: 3732 Training R2: nan
Epoch: 3733 Training R2: nan
Epoch: 3734 Training R2: nan
Epoch: 3735 Training R2: nan
Epoch: 3736 Training R2: nan
Epoch: 3737 Training R2: nan
Epoch: 3738 Training R2: nan
Epoch: 3739 Training R2: nan
Epoch: 3740 Training R2: nan
Epoch: 3741 Training R2: nan
Epoch: 3742 Training R2: nan
Epoch: 3743 Training R2: nan
Epoch: 3744 Training R2: nan
Epoch: 3745 Training R2: nan
Epoch: 3746 Training R2: nan
Epoch: 3747 Training R2: nan
Epoch: 3748 Training R2: nan
Epoch: 3749 Training R2: nan
Epoch: 3750 Training R2: nan
Epoch: 3751 Training R2: nan
Epoch: 3752 Training R2: nan
Epoch: 3753 Training R2: nan
Epoch: 3754 Training R2: nan
Epoch: 3755 Training R2: nan
Epoch: 3756 Training R2: nan
Epoch: 3757 Training R2: nan
Epoch: 3758 Training R2: nan
Epoch: 3759 Training R2: nan
Epoch: 3760 Training R2: nan
Epoch: 3761 Training R2: nan
Epoch: 3762 Training R2: nan
Epoch: 3763 Training R2: nan
Epoch: 3764 Training R2: nan
Epoch: 3765 Training R2: nan
Epoch: 3766 Training R2: nan
Epoch: 3767 Training R2: nan
Epoch: 3768 Training R2: nan
Epoch: 3769 Training R2: nan
Epoch: 3770 Training R2: nan
Epoch: 3771 Training R2: nan
Epoch: 3772 Training R2: nan
Epoch: 3773 Training R2: nan
Epoch: 3774 Training R2: nan
Epoch: 3775 Training R2: nan
Epoch: 3776 Training R2: nan
Epoch: 3777 Training R2: nan
Epoch: 3778 Training R2: nan
Epoch: 3779 Training R2: nan
Epoch: 3780 Training R2: nan
Epoch: 3781 Training R2: nan
Epoch: 3782 Training R2: nan
Epoch: 3783 Training R2: nan
Epoch: 3784 Training R2: nan
Epoch: 3785 Training R2: nan
Epoch: 3786 Training R2: nan
Epoch: 3787 Training R2: nan
Epoch: 3788 Training R2: nan
Epoch: 3789 Training R2: nan
Epoch: 3790 Training R2: nan
Epoch: 3791 Training R2: nan
Epoch: 3792 Training R2: nan
Epoch: 3793 Training R2: nan
Epoch: 3794 Training R2: nan
Epoch: 3795 Training R2: nan
Epoch: 3796 Training R2: nan
Epoch: 3797 Training R2: nan
Epoch: 3798 Training R2: nan
Epoch: 3799 Training R2: nan
Epoch: 3800 Training R2: nan
Epoch: 3801 Training R2: nan
Epoch: 3802 Training R2: nan
Epoch: 3803 Training R2: nan
Epoch: 3804 Training R2: nan
Epoch: 3805 Training R2: nan
Epoch: 3806 Training R2: nan
Epoch: 3807 Training R2: nan
Epoch: 3808 Training R2: nan
Epoch: 3809 Training R2: nan
Epoch: 3810 Training R2: nan
Epoch: 3811 Training R2: nan
Epoch: 3812 Training R2: nan
Epoch: 3813 Training R2: nan
Epoch: 3814 Training R2: nan
Epoch: 3815 Training R2: nan
Epoch: 3816 Training R2: nan
Epoch: 3817 Training R2: nan
Epoch: 3818 Training R2: nan
Epoch: 3819 Training R2: nan
Epoch: 3820 Training R2: nan
Epoch: 3821 Training R2: nan
Epoch: 3822 Training R2: nan
Epoch: 3823 Training R2: nan
Epoch: 3824 Training R2: nan
Epoch: 3825 Training R2: nan
Epoch: 3826 Training R2: nan
Epoch: 3827 Training R2: nan
Epoch: 3828 Training R2: nan
Epoch: 3829 Training R2: nan
Epoch: 3830 Training R2: nan
Epoch: 3831 Training R2: nan
Epoch: 3832 Training R2: nan
Epoch: 3833 Training R2: nan
Epoch: 3834 Training R2: nan
Epoch: 3835 Training R2: nan
Epoch: 3836 Training R2: nan
Epoch: 3837 Training R2: nan
Epoch: 3838 Training R2: nan
Epoch: 3839 Training R2: nan
Epoch: 3840 Training R2: nan
Epoch: 3841 Training R2: nan
Epoch: 3842 Training R2: nan
Epoch: 3843 Training R2: nan
Epoch: 3844 Training R2: nan
Epoch: 3845 Training R2: nan
Epoch: 3846 Training R2: nan
Epoch: 3847 Training R2: nan
Epoch: 3848 Training R2: nan
Epoch: 3849 Training R2: nan
Epoch: 3850 Training R2: nan
Epoch: 3851 Training R2: nan
Epoch: 3852 Training R2: nan
Epoch: 3853 Training R2: nan
Epoch: 3854 Training R2: nan
Epoch: 3855 Training R2: nan
Epoch: 3856 Training R2: nan
Epoch: 3857 Training R2: nan
Epoch: 3858 Training R2: nan
Epoch: 3859 Training R2: nan
Epoch: 3860 Training R2: nan
Epoch: 3861 Training R2: nan
Epoch: 3862 Training R2: nan
Epoch: 3863 Training R2: nan
Epoch: 3864 Training R2: nan
Epoch: 3865 Training R2: nan
Epoch: 3866 Training R2: nan
Epoch: 3867 Training R2: nan
Epoch: 3868 Training R2: nan
Epoch: 3869 Training R2: nan
Epoch: 3870 Training R2: nan
Epoch: 3871 Training R2: nan
Epoch: 3872 Training R2: nan
Epoch: 3873 Training R2: nan
Epoch: 3874 Training R2: nan
Epoch: 3875 Training R2: nan
Epoch: 3876 Training R2: nan
Epoch: 3877 Training R2: nan
Epoch: 3878 Training R2: nan
Epoch: 3879 Training R2: nan
Epoch: 3880 Training R2: nan
Epoch: 3881 Training R2: nan
Epoch: 3882 Training R2: nan
Epoch: 3883 Training R2: nan
Epoch: 3884 Training R2: nan
Epoch: 3885 Training R2: nan
Epoch: 3886 Training R2: nan
Epoch: 3887 Training R2: nan
Epoch: 3888 Training R2: nan
Epoch: 3889 Training R2: nan
Epoch: 3890 Training R2: nan
Epoch: 3891 Training R2: nan
Epoch: 3892 Training R2: nan
Epoch: 3893 Training R2: nan
Epoch: 3894 Training R2: nan
Epoch: 3895 Training R2: nan
Epoch: 3896 Training R2: nan
Epoch: 3897 Training R2: nan
Epoch: 3898 Training R2: nan
Epoch: 3899 Training R2: nan
Epoch: 3900 Training R2: nan
Epoch: 3901 Training R2: nan
Epoch: 3902 Training R2: nan
Epoch: 3903 Training R2: nan
Epoch: 3904 Training R2: nan
Epoch: 3905 Training R2: nan
Epoch: 3906 Training R2: nan
Epoch: 3907 Training R2: nan
Epoch: 3908 Training R2: nan
Epoch: 3909 Training R2: nan
Epoch: 3910 Training R2: nan
Epoch: 3911 Training R2: nan
Epoch: 3912 Training R2: nan
Epoch: 3913 Training R2: nan
Epoch: 3914 Training R2: nan
Epoch: 3915 Training R2: nan
Epoch: 3916 Training R2: nan
Epoch: 3917 Training R2: nan
Epoch: 3918 Training R2: nan
Epoch: 3919 Training R2: nan
Epoch: 3920 Training R2: nan
Epoch: 3921 Training R2: nan
Epoch: 3922 Training R2: nan
Epoch: 3923 Training R2: nan
Epoch: 3924 Training R2: nan
Epoch: 3925 Training R2: nan
Epoch: 3926 Training R2: nan
Epoch: 3927 Training R2: nan
Epoch: 3928 Training R2: nan
Epoch: 3929 Training R2: nan

In [108]:
r2vals

[0.4523644750284309, 0.8020457599189692, 0.9118602430458679, nan]

In [110]:
index = np.nanargmax(r2vals)
index

2

In [111]:
best_alpha = alphas[index]
best_alpha

0.1

In [112]:
best_params = params[index]
best_params

array([-1420757.33632194,  1935924.5078461 ,  1124960.2605968 ,
         919071.97821889,     6662.8027308 ,  1064408.51927216])

In [113]:
x_t1 = np.c_[np.ones(x_t.shape[0]),x_t]    
test_predictions = np.matmul(x_t1,best_params)
r2v = 1 - (np.sum((test_predictions-y_t)**2))/((np.sum((y_t-np.mean(y_t))**2)))
print("Test R2: "+str(r2v))

Test R2: 0.9205123253830161

In [114]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

model = LinearRegression()
model.fit(x_tr, y_tr)

y_pred = model.predict(x_t)

r2 = r2_score(y_t, y_pred)

print("Sklearn Test R2:", r2)

Sklearn Test R2: 0.9205114448054168